### ISSUE TITLE
Kratos Debug mode compiling error -"cannot open python310_d.lib" 

### ISSUE THREAD

**Issue by akhilkmat** [KratosMultiphysics/Kratos#10055]
I am trying to compile Kratos in Debug mode, I am getting an error which says "cannot open python310_d.lib" (image 1); Although the file is contained in the python libs folder(image 2). I am running as administrator and the file has all the permissions ticked.  Did anyone have such an issue?
![image1](https://user-images.githubusercontent.com/69186170/180206699-aeb0469b-a12b-49ef-8369-3874031654b8.png)
![image2](https://user-images.githubusercontent.com/69186170/180206703-3a83ceb7-8309-45a3-8deb-ff58a57e8a62.png)
[configure.txt](https://github.com/KratosMultiphysics/Kratos/files/9159038/configure.txt)

**Comment by ddiezrod** [comment]
I think it works if you copy the lib inside your kratos build/Debug folder. Maybe there is a better solution though...

**Comment by akhilkmat** [comment]
> I think it works if you copy the lib inside your kratos build/Debug folder. Maybe there is a better solution though...

thank you, tried that but still didn't work.
update:
-tried older versions of python ( didn't work).
-Also added /lib and /libpath for libs folder as the environment variables ( didn't work)

**Comment by matekelemen** [comment]
I've run into this problem too and it seems quite obnoxious. If you feel like diving into the details, [here](https://github.com/pybind/pybind11/issues/3403)'s a discussion of the problem but there aren't any good solutions yet.

**Comment by roigcarlo** [comment]
As this is related to runkratos I am going to close the issue. Runkratos is currently deprecated and will be deleted in december. 
In order to debug with python in windows you need to use the debug executable of python (python_d.exe)

Note that this is only usefull to intercept pybind11 class, or have a deeper look at the call stack, normal python with debug mode Kratos should allow you to debug as well as long as runkratos is not compiled or used to launch the code.
