### ISSUE TITLE
an excellent example of misleading formatting :-(

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1015]
Hi @KratosMultiphysics/technical-committee 

take a look at this:

https://github.com/AMatrix/AMatrix/blob/master/include/matrix.h#L179

here the formatting gives the impression that the temporary is passed in the function signature. That would not happen if we had the { symbol on the next line, or if we somhow changed the indentation.

do you think we can do something to avoid this behaviour in the automatic formatting?

**Comment by RiccardoRossi** [comment]
for example one possible option could be (preserving the { on the top line)

    template <typename TMatrixType1, typename TMatrixType2>
    inline Matrix<typename TMatrixType1::value_type, TMatrixType1::size1(), TMatrixType2::size2()> operator*(
        TMatrixType1 const& First,
        TMatrixType2 const& Second) {
            Matrix<typename TMatrixType1::value_type, TMatrixType1::size1(), TMatrixType2::size2()> result;
        
            for (std::size_t i = 0; i < TMatrixType1::size1(); i++)      
                for (std::size_t j = 0; j < TMatrixType2::size2(); j++) {      
                    typename TMatrixType1::value_type temp = typename TMatrixType1::value_type();
                     for (std::size_t k = 0; k < TMatrixType1::size2(); k++)
                         temp += First(i, k) * Second(k, j);
                    result(i, j) = temp;
                }

            return result;
        }

**Comment by jcotela** [comment]
@RiccardoRossi to be honest I'm not too concerned by this particular example, since the function arguments would never end in `;` (and, if they do, the remainder of the function is on the cpp, which is the best option anyway).

Having said that, I'm starting to think that the google style is too compact for its own good. Your "confusion" would also never happen if the `{` was on the next line, and I would prefer that to introducing an extra level of indentation.

**Comment by roigcarlo** [comment]
Indeed this is a problem but in my opinion this problem was introduced by us. Our **base** styling uses the options:
- `{` in the same line
- header arguments indented 4 spaces
- rest of the code intended using 2 spaces

But we decided to indent everything with 4 so this sort of things may happen.
I don't see it as a major issue but we are still in time to change it. I understand why you want to move `{` to newline to avoid this, provided the other options will remain as is. But I would also want to propose other solutions:
- Move `{` to newline
- Move `{` to newline only in function and class definitions
- Add a newline between the header an the code
- Indent with 2 :D

**Comment by RiccardoRossi** [comment]
as you know... my vote is for:

Move { to newline

!!!! :-p

**Comment by loumalouomega** [comment]
https://en.wikipedia.org/wiki/Indentation_style#Allman_style 4THEWIN

**Comment by roigcarlo** [comment]
Just for the record, I like neither Allman nor K&R. I prefer TBS. That said I won't oppose if everyone wants to use Allman.

Maybe one day history will find a way to forgive you. :cry: 

P.s. Jokes apart, I ordered my solutions from "worst" to "better", so you know what are my preferences

**Comment by RiccardoRossi** [comment]
@roigcarlo 

of your proposals, the only one that i don't love is the last one (the 2 spaces)

**Comment by pooyan-dadvand** [comment]
My first option would be:
1. indenting the function argument by 2 and the rest by 4. 

and then 

2. Move `{ `to newline only in function and class definitions

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee prefers option 1 of Pooyan's comments
