### ISSUE TITLE
MultilevelMonteCarlo nightly build fail

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#10450]
**Description**
The `MultilevelMonteCarlo` nightly build keeps randomly failing since some weeks ago. The report says that the tests take too long. However, there are some warnings that seem to be related to the MMG remeshing. I'm not sure if any change in this regard could have affected the total time of the tests.

**Comment by marcnunezc** [comment]
I will take a look asap. Timings are suspicious:
- With 2 procs tests take 16 sec
- With 3 procs tests take 460 sec!
- With 4 procs it runs out of time

**Comment by marcnunezc** [comment]
I think the issue is that the nighly build MPI test are run with OMP_NUM_THREADS=2.

Here are the timings: 
OMP_NUM_THREADS=2 (current):
[Run log](https://github.com/KratosMultiphysics/Kratos/actions/runs/3511017786/jobs/5881386313)
- 2 procs: 17 s
- 3 procs: 327 s
- 4 procs: 686 s

OMP_NUM_THREADS=1 (tested in [ci/marcnunezc-patch-2](https://github.com/KratosMultiphysics/Kratos/tree/ci/marcnunezc-patch-2))
[Run log](https://github.com/KratosMultiphysics/Kratos/actions/runs/3509996634/jobs/5879477313)
- 2 procs: 17 s
- 3 procs: 30 s
- 4 procs: 34 s

Do you agree on limiting the OMP_THREADS to 1 when running the MPI tests?

**Comment by rubenzorrilla** [comment]
> I think the issue is that the nighly build MPI test are run with OMP_NUM_THREADS=2.
> 
> Here are the timings: OMP_NUM_THREADS=2 (current): [Run log](https://github.com/KratosMultiphysics/Kratos/actions/runs/3511017786/jobs/5881386313)
> 
>     * 2 procs: 17 s
> 
>     * 3 procs: 327 s
> 
>     * 4 procs: 686 s
> 
> 
> OMP_NUM_THREADS=1 (tested in [ci/marcnunezc-patch-2](https://github.com/KratosMultiphysics/Kratos/tree/ci/marcnunezc-patch-2)) [Run log](https://github.com/KratosMultiphysics/Kratos/actions/runs/3509996634/jobs/5879477313)
> 
>     * 2 procs: 17 s
> 
>     * 3 procs: 30 s
> 
>     * 4 procs: 34 s
> 
> 
> Do you agree on limiting the OMP_THREADS to 1 when running the MPI tests?
> 
> Btw, I took the chance to upgrade both mmg and parmmg versions which will remove all the annoying warnings

I think this makes very much sense. :+1:

**Comment by philbucher** [comment]
I intentionally did not set it to 1 to also check the interoperability of MPI and OpenMP, but I agree that for the moment it makes more sense to restrict it
