### ISSUE TITLE
Restart in Kratos

### ISSUE THREAD

**Issue by MicheleBarucca97** [KratosMultiphysics/Kratos#10603]
**Description**
I am running an FSI simulation and I am using Kratos as structural solver. Due to problme with a CFL number I start with a very small delta_t. I want to enlarge it. 

**Scope**
My question is: how can I deserialize the .rest file in order to change the delta_t?

Thanks in advance for the help.

**Comment by rubenzorrilla** [comment]
Hi @MicheleBarucca97,

Just to make sure, you are running an FSI simulation in which Kratos is only used to solve the structure (not the CFD nor the coupling) right? If so, to load the structure you need to change the following in the .json settings:

- `start_time` in the problem data section to the point at which you want to start the deserialized simulation.
- `input_type` to `rest` instead of `mdpa` in the `solver_settings` section. You also need to specify in here a new field `restart_load_file_label` containing the label of the corresponding restart file.
- of course you also need to change the delta time to the new enlarged value.

I wrote this by heart so I could have missed something (we should write a "how to" note about this in the documentation). Let us now if any issue raises.

@sunethwarna @philbucher if you have some time, can you confirm that everything I wrote here is correct? Thanks!

**Comment by rubenzorrilla** [comment]
mmm... I think there is a little misunderstanding here. This change occurs at runtime, there shouldn't be any complaint from the compiler.

**Comment by MicheleBarucca97** [comment]
Ok thanks a lot for the clarification, I lost the log of that try, I will try again.
