### ISSUE TITLE
[Builder and Solver] passing constant Damping and mass matrix

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10804]
In a situation where my mass and damping matrix are constant throughout solution steps/ non-linear iterations. I would like to pass the damping and mass matrix through the function "CalculateRHSContribution" in a scheme.  Currently every non-linear iteration I call "CalculateRHSContribution", this function then requires to recalculate the mass and damping matrix, to add the mass and damping contribution to the RHS. 

Is there a way to pass existing mass and damping matrices to "CalculateRHSContribution", such that I don't have to recalculate?

**Comment by AlejandroCornejo** [comment]
Hey!! I'm glad that you make this question. A couple of years ago (see that issue https://github.com/KratosMultiphysics/Kratos/issues/4833) I noticed that in non-linear solid simulations (dynamic) the damping matrix was being re-computed at each iteration according to the Rayleigh approach (alpha*M + beta*K) in which K is changing at each iteration.

IMO, this should not be this way since we should be using the initial stiffness K0. We leave it like it was but maybe not it can be revisited.

Regards

**Comment by aronnoordam** [comment]
Thank you for the reference to the issue, interesting discussion. The suggestions made in that issue say that we should store the damping (in my case also mass) matrix within the element. However, for my issue im mostly interested in performance, storing the damping and mass matrix in dense form per element, does not seem to improve this. 

IMO there should be a method in the builder which just builds the mass matrix and another for the damping matrix and another to combine them in the LHS (I don't see this as a replacement for the current method of building the LHS, but as an additional method) . When the mass and damping matrix are built seperatly, we can use them as we want it in our solver.

**Comment by loumalouomega** [comment]
Hello, IMO we should add to the `Scheme` and `BuilderAndSolver` the possibility to assemble M and D and use it in a global manner instead of a local manner. First because usually these matrices are constant during all simulation, and second because they add a significant cost in assembling step (as we are adding extra steps and recomputing the same over and over). I would not advocate to change the default, but to add the possibility to use global computation as an option.

FYI @KratosMultiphysics/technical-committee 

NOTE: I have been thinking about this long time ago
NOTE2: @KratosMultiphysics/altair this may affect us, and could be interesting to consider

**Comment by matekelemen** [comment]
Or we could just separate the tasks of assembling and solving => leave the decision of when to build what and when to solve, up to the `Scheme`.

**Comment by loumalouomega** [comment]
> Or we could just separate the tasks of assembling and solving => leave the decision of when to build what and when to solve, up to the `Scheme`.

Yes, but would require some "engineering"
