### ISSUE TITLE
[Core] Calling Clear model part "breaks" model part in FullDebug in Windows

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#10880]
This code throws an error in Windows in FullDebug (I have not checked on other platforms) when calling the second AddElement.

```
import KratosMultiphysics as KM


model = KM.Model()
model_part = model.CreateModelPart("main")
model_part.CreateNewNode(1,0,0,0)
model_part.CreateNewNode(2,0,0,0)
model_part.CreateNewNode(3,0,0,0)
model_part.CreateNewNode(4,0,0,0)
prop = model_part.CreateNewProperties(0)
new_elem = model_part.CreateNewElement("Element3D4N",1,[1,2,3,4],prop)
model_part.AddElement(new_elem)
model_part.Clear()
model_part.AddElement(new_elem)
print(model_part)
```

![image](https://user-images.githubusercontent.com/25667299/225359418-e966b28b-1b22-45cd-a858-99c68883fe32.png)

I think the reason is that when we call the Clear we are removing all mMeshes in model part 
https://github.com/KratosMultiphysics/Kratos/blob/94dfc0a01c20aae6e9949bb63934bc261fc28b49/kratos/sources/model_part.cpp#L84

but model part should always have at least one mesh (id 0) 
https://github.com/KratosMultiphysics/Kratos/blob/94dfc0a01c20aae6e9949bb63934bc261fc28b49/kratos/sources/model_part.cpp#L56

Is it really necessary to clear the meshes? Would we break anything if we remove that line?

ping @KratosMultiphysics/implementation-committee  @KratosMultiphysics/technical-committee @philbucher

**Comment by matekelemen** [comment]
`clear` should leave an object in a default constructed state. `ModelPart` doesn't have a default constructor so I'd go with the constructor you pointed out => instead of removing the line, I'd follow it up with what the constructor does:
```cpp
mMeshes.clear();
MeshType mesh;
mMeshes.push_back(Kratos::make_shared<MeshType>(mesh.Clone()));
``` 

P.S.: maybe this is a good time to reflect on why we need to allocate memory 3 times and construct a `MeshType` twice, just to append an array with an empty object. How about this instead:
```diff
- MeshType mesh;
- mMeshes.push_back(Kratos::make_shared<MeshType>(mesh.Clone()));
+ mMeshes.emplace_back(Kratos::make_shared<MeshType>());
```

**Comment by ddiezrod** [comment]
@matekelemen that makes a lot of sense, I will create the PR

**Comment by ddiezrod** [comment]
I was thinking... I am not sure if in pointer vector (as mMeshes) it really makes sense to do emplace_back instead of push_back. Is not it basically the same? @matekelemen

**Comment by loumalouomega** [comment]
Emplace_backs calls the constructor

**Comment by matekelemen** [comment]
I didn't check the type of `mMeshes` and assumed it was just an `std::vector`.

It looks like `PointerVector` doesn't have `emplace_back` so we don't really have an option and must use `push_back` instead. That's quite unfortunate because `PointerVector::push_back` looks like this:
https://github.com/KratosMultiphysics/Kratos/blob/52b5d888cd65fd2cf2f5b8ea72c7f5b56c265a2c/kratos/containers/pointer_vector.h#L270-L273

Since `x` is taken by value, there's immediately an implicit copy. Then, `mData.push_back(x)` passes `x` by value again, instead of moving it, so a second implicit copy is made. Keep in mind that every time a smart pointer is copied, there's a non-negligible overhead with reference counting.

I suggest adding `emplace_back` to `PointerVector`, or at least the following change:
```diff
void push_back(TPointerType x)
    {
-        mData.push_back(x);
+       mData.push_back(std::move(x));
    }
```
