### ISSUE TITLE
Compilation / Linking error  kratos_python.cpp

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1125]
![screenshot from 2017-12-05 14-43-37](https://user-images.githubusercontent.com/23210788/33610162-ef456d70-d9ca-11e7-80d4-42784cde47ec.png)

**Comment by roigcarlo** [comment]
Python version in boost is no the same as the one used in kratos.

**Comment by loumalouomega** [comment]
Have you updated recently your linux?, the lastest releases of Ubuntu use python 3.6 instead of 3.5

Greetings

Vicente Mataix Ferrándiz

**Comment by josep-m-carbonell** [comment]
I was my fault, an space in the configure.sh   :-1:

**Comment by josep-m-carbonell** [comment]
There is no error, I just detected it now testing COTIRE

**Comment by roigcarlo** [comment]
Ok

**Comment by roigcarlo** [comment]
I am lost now. Cotire is not ment to be used by anyone yet but travis, nor is recommended for a daily workflow or even is it finished for kratos. Moreover, activating cotire will make no difference unless you specifically change other parts of the configure file.

As for the screen error, it happens when linking the boost wrappers with python. If the boost lib is not compiled agains the same version of python as kratos it will not find the Py_init function (among others, but that's the one will be reported).

There may be many causes for that. A space ( as you say ) or a update of the system that have changed the default python version if it was not set in the configure explicitly are the most common. It may also be happening that the version you put in the configure no longer exists and cmake is detecting the default system version, which can be different from the one you used to compile boost.

Can you check if any of these are the cause?

**Comment by josep-m-carbonell** [comment]
The cause was that the "configure.sh" had an extra space and it was not taken correctly by the cmake. Correcting that space the error was solved.  (I added the space by mistake when I have written -DUSE_COTIRE=ON to the configure.sh ). As you say, it does no difference. I would like to know what I have to change to compile faster.

**Comment by roigcarlo** [comment]
Ok, I understand now the problem.

If you really want to use cotire you need the `DUSE_COTIRE=ON` but you have to compile using `make all_unity`, `make runkratos` and then `make install/fast`. You can still use -jX if you want to compile in parallel.

This way you will be able to compile the applications and the core in unity mode. That mode is not active for all apps, so you will have to modify the CMakeLists.txt of your application/s to look something like this (taking the PFEM application as example):

```CMake
# This needs to be just before the install statement
if(USE_COTIRE MATCHES ON)
  cotire(KratosPfemApplication)
endif(USE_COTIRE MATCHES ON)

install(TARGETS KratosPfemApplication DESTINATION libs )
```

If you don't do that but you application is ON in the configure, it will not compile anyway. That should be everything.

As a final note, just comment that this uses **A LOT** of ram, specially if you run with -jX. (you can have spikes of 12G>)

**Comment by josep-m-carbonell** [comment]
@roigcarlo  Thank you for the explanation I will try to do it.
