### ISSUE TITLE
Model cannot delete a sub model part

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#11307]
I found that you cannot delete a submodel part from the model. If you run this code you will see that the submodelpart is still there after calling 

```
import KratosMultiphysics


model = KratosMultiphysics.Model()
mp1 = model.CreateModelPart("main_1")
mp2 = mp1.CreateSubModelPart("sub")

model.DeleteModelPart("main_1.sub")
print(mp1)
```

I understand that this is not the expected behaviour so this should be fixed somehow.
@KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee @philbucher

**Comment by matekelemen** [comment]
Good catch!

https://github.com/KratosMultiphysics/Kratos/blob/219f62479324324df8d2d33e0ad705b01cd545f4/kratos/containers/model.cpp#L80-L91

https://github.com/KratosMultiphysics/Kratos/blob/219f62479324324df8d2d33e0ad705b01cd545f4/kratos/containers/model.cpp#L221-L245

The problem is that `Model::HasModelPart` does a recursive search (and successfully finds the sub model part you want to delete) but `Model::DeleteModelPart` **only** attempts to erase from its own map. This is a bug. `Model::DeleteModelPart` should be recursive too.

**Comment by loumalouomega** [comment]
Who fixes this?, @ddiezrod for finding the bug?

**Comment by ddiezrod** [comment]
> Who fixes this?, @ddiezrod for finding the bug?

Yep I can fix it if we agree this is a "bug" (I think so)

**Comment by philbucher** [comment]
Can a submodelpart even be deleted?

Afaik two ModelParts could hold it at the same time, thats why the ModelPart only has a RemoveSubModelPart interface

**Comment by matekelemen** [comment]
> Can a submodelpart even be deleted?
> 
> Afaik two ModelParts could hold it at the same time, thats why the ModelPart only has a RemoveSubModelPart interface

Two `ModelPart`s sharing the same child `ModelPart`? How is that possible?

**Comment by ddiezrod** [comment]
This was fixed in https://github.com/KratosMultiphysics/Kratos/pull/11309
