### ISSUE TITLE
Making a new problemtype for GID

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#114]
Hi together,

as stated in our last Skype meeting on last Thursday we would like to compile a problem type of the Kratos for GID ourself. The reason for this is, we want to use it for teaching and it would be very helpful for us in order to give changes we make directly to our students without waiting for an update of the original problemtype or make them compile the code by themselves.

It would be very nice, if you could help us in this regard.

Thank you in advance.

Ciao

Andreas

**Comment by loumalouomega** [comment]
I added @jginternational, he is our GiD problem type main developer

**Comment by jginternational** [comment]
Hi @AndreasWinterstein ,

Just one question. Are you planning to create a new GiD problemtype for your needs or do you want to pack the current one? 
Remember that the current GiD Interface can be found here:
[https://github.com/KratosMultiphysics/GiDInterface](https://github.com/KratosMultiphysics/GiDInterface)

If you want to use the current, I can help you, but take into account that it's in a beta version.

Glad to help you
Javi G

**Comment by AndreasWinterstein** [comment]
Hi Javi,

sorry for the late reply. I do not want to create my own problemtype I want to pack the current one. The reason is, we also want to use it for teaching. If I do some changes in the code I want the students to have it would be nice to be able to create the problemtype once again so the students can use GID and do not have to compile the code themselves.

Thank you for helping.

Andreas

**Comment by pooyan-dadvand** [comment]
If you want only to pack it I think that @roigcarlo would share with you his experience about this. 

Meanwhile I think that we should prepare a release soon.

**Comment by roigcarlo** [comment]
Hi, @AndreasWinterstein.

The process is a bit different for win a linux. Which os are you using?

**Comment by AndreasWinterstein** [comment]
Hi @roigcarlo,

I will have to do it on windows and linux.

**Comment by roigcarlo** [comment]
@AndreasWinterstein In this case I have a couple of scripts you will need in a laptop at the office, I will just send it to you tomorror and show you how they work (can't grab them right now sorry).

If you already compiled kratos is a very simple process

**Comment by roigcarlo** [comment]
@AndreasWinterstein , I copy you here the most basic script (Powershell) we use to make releases on win:

```PowerShell
# This script packs and upload a compiled version of kratos.
# Instructions: Set the proper paths under "Defines" and run.

# Defines
$KRATOS_MAJOR = 5
$KRATOS_MINOR = 0
$KRATOS_ARCHY = 64
$KRATOS_NEWSD = "Interal refactoring and new interface"
$KRATOS_TVERS = "5.0"
$KRATOS_TDATE = "$((Get-Date).AddDays(-1).ToString('dd-MM-yyy'))"

# Paths
$KRATOS_RLS = "C:\KratosStage\Pack64"                           # Local folder where the release will be packed
$KRATOS_SRC = "C:\KratosSource"	                                # Kratos source
$KRATOS_CMP = "C:\KratosStage\Release64"                        # Kratos install directory
$KRATOS_AUX = "C:\KratosStage\LibsForPack64"                    # Kratos additional libraries.
$GIDINT_SRC = "C:\KratosSource\interfaces\GiD\kratos.gid"	# GID Interface
$GIDINT_KTS = "kratos.gid\exec"			        										# GiD Kratos Interface install dir
$GIDINT_DEM = "UNUSED"			            												# GiD DEM Interface install dir
$DEPLOY_DIR = "C:\KratosDeploy"               	                # Deploy directory (masterdisc).
$env:Path  += ";C:\Program Files\7-Zip" 	                        # Winrar/winzip binaries
$GIDINT_ARR = @("$GIDINT_KTS")			                # List of all the places where kratos has to be copied

# Obtain the svn release number
# Note: This part is out of date
$SVN_REV = "0"

# Clean old releases to avoid conflicts
Remove-Item -Force -Recurse "$KRATOS_RLS\*"

# Copy Kratos, Kratos.Gid and additional libraries to the local release directory
xcopy /s/e/h/y "$GIDINT_SRC"   "$KRATOS_RLS\kratos.gid\"

for ($i=0; $i -lt $GIDINT_ARR.length; $i++) {
	$GITINT_DIR = $GIDINT_ARR[$i]

	xcopy /s/e/h/y "$KRATOS_CMP"   "$KRATOS_RLS\$GITINT_DIR\kratos\"
	xcopy /s/e/h/y "$KRATOS_AUX\*" "$KRATOS_RLS\$GITINT_DIR\kratos\"

	# Remove trash (.lib, .svn)
	get-childitem "$KRATOS_RLS\$GITINT_DIR\" -Force -Include *.svn -Recurse | remove-item -Force -Recurse
	get-childitem "$KRATOS_RLS\$GITINT_DIR\" -Force -Include *.lib -Recurse | remove-item -Force -Recurse
}

# Update the xml file with the correct svn release number
[xml]$kratosxml = Get-content "$KRATOS_RLS\kratos.gid\kratos.xml"

$kratosxml.Infoproblemtype.Program.Version               = "$KRATOS_MAJOR.$KRATOS_MINOR.$SVN_REV"
$kratosxml.save("$KRATOS_RLS\kratos.gid\kratos.xml")

# Creathe the zip file
7z a -r "$KRATOS_RLS\kratos-$KRATOS_MAJOR.$KRATOS_MINOR.$SVN_REV-win-$KRATOS_ARCHY.zip" "$KRATOS_RLS\kratos.gid"
```

Now a little explanation how this works.
First you have to fill the `Defines` section. Variables there mean;

```PowerShell
$KRATOS_MAJOR # Major release number.
$KRATOS_MINOR # Minor release number.
$KRATOS_ARCHY # Arch, must be 32 or 64.
$KRATOS_NEWSD # Short string with info about the new release.
$KRATOS_TVERS # Git interface version. Leave this as in the example
$KRATOS_TDATE # Git interface date. Leave this as in the example
```

Once this is set you have to define the location of every file from the release. This is slightly different from normal kratos since, as people will tipically not have most of the libraries we need to ship them along with kratos. Also notice that the script asumes that kratos has been installed in a diferent location and NOT along with the source code. This is important here because I copy all the files by default and we usually want to avoid to copy the source along with the binaries.

```PowerShell
$KRATOS_RLS # Local folder where the release will be packed: The result of the script will be here
$KRATOS_SRC # Source of the code, but not compiled libs
$KRATOS_CMP # Result of the compilation, binaries, libs, runkratos, etc
$KRATOS_AUX # Additional libraries that need to be shipped along with kratos.

# You shouldn't touch these:
$GIDINT_SRC # GID interface source.
$GIDINT_KTS # GiD Kratos Interface install dir
$GIDINT_DEM # GiD DEM Interface install dir.
$DEPLOY_DIR # Deploy dir.

# Add this if you want to automatically zip the result. It must point to winzip/winrar/7zip or similar
$env:Path  += ";C:\Program Files\7-Zip" 	                    	# Winrar/winzip binaries
```

Please notice that, at least the directory with $KRATOS_AUX need to have (with XX,YY and ZZ being the versions of VS and Boost and python):
* boost_python_vc1XX-mt-1_YY.dll
* msvcp1XX.dll
* pythonZZ.dll
* vcamp1XX.dll
* vccorlib1XX.dll
* vcomp1XX.dll
* vcruntime1XX.dll

Apart from that, the script should handle the rest of details, like building the interface folder etc, etc...

I understand that this may be a little complicated since is not intended to be used outside CIMNE and very tailored for our release machine, and probably I missed some details, so please if you find any problem just ping me

**Comment by AndreasWinterstein** [comment]
@roigcarlo Thank you very much. Can you also forward the skripts for Linux please.

**Comment by roigcarlo** [comment]
Linux script is already in git: https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/build/compile_and_pack_linux_x86_64.sh

The idea is the same with some tweaks for linux, pack kratos and copy the shared libs. SVN options may be out of date since we didn't made any release with git yet so it hasn't been updated.

Probably you will want to comment:
* https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/build/compile_and_pack_linux_x86_64.sh#L154-L158 (used to distribute with mpi support)

and change all hardcoded paths `/home/odin/****` ( odin was our old release machine for linux )

**Comment by armingeiser** [comment]
Hello @roigcarlo,

thanks for the scripts, i tried the Windows one. I could pack everything and now i tried to just copy the problemtype to another Windows machine without python installed.

if i try to run an example on a Windows machine with no Python installed, i get the following error:

> Fatal Python error: Py_Initialize: unable to load the file system codec
> ImportError: No module named 'encodings'
> 
> Current thread 0x00000a60 (most recent call first):

Appearently the pythonXX.dll does not find some expected python installation files.

Do I need to consider any special settings when building Kratos and or installing python?

Armin

**Comment by roigcarlo** [comment]
Yep, copy the "Lib" folder from the python dir to $KRATOS_AUX along with the other DLL's.

**Comment by armingeiser** [comment]
@roigcarlo Thanks a lot for the help, it works for me under Windows!

Hint:
Make sure that the .dlls mentioned fit to the adress model chosen for the Kratos installation (32/64bit), because they exist many times on a Windows machine in 32 and 64 bit and cannot be distinguished by their name.

**Comment by roigcarlo** [comment]
Glad to hear :smile: 

Also, thx for the hint, I will have this into account when we upload this to Git and for the doc.

I'll leave the issue open in case you want to check linux as well. If not feel free to close.

**Comment by roigcarlo** [comment]
Closing this since since was solved and there hasn't been any other issue.
