### ISSUE TITLE
[Core] Tests in MPIDataCommunicator

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#11432]
**Description**
I found out in few of the tests in `test_mpi_data_communicator.cpp`, there are some variables which are declared but not used, and they do not throw the variable unused warning as well. I was wondering whether there was a specific reason for them to be there? As far as I see, they are not required. (All the tests passes without those variables).

In the case  of `wrong_send`, it throws an error as expected, but for the wrong reasons (It throws the error because the `recv_buffer` is wrong, not because the `send_buffer` is wrong).

Puzzling point for me is, why these do not throw the unused variable warnings?

any ideas @jcotela @roigcarlo @philbucher @RiccardoRossi @pooyan-dadvand @loumalouomega @matekelemen 

Followings are the places:
1. In here `wrong_recv` is declared and initialized, but never used.
https://github.com/KratosMultiphysics/Kratos/blob/f8aeb637293ce5177d6bca41d629fd31a8b4a24b/kratos/mpi/tests/cpp_tests/sources/test_mpi_data_communicator.cpp#L1634-L1641
https://github.com/KratosMultiphysics/Kratos/blob/f8aeb637293ce5177d6bca41d629fd31a8b4a24b/kratos/mpi/tests/cpp_tests/sources/test_mpi_data_communicator.cpp#L1708-L1714
2. In here the `wrong_send` is declared and initialized, but never used
https://github.com/KratosMultiphysics/Kratos/blob/f8aeb637293ce5177d6bca41d629fd31a8b4a24b/kratos/mpi/tests/cpp_tests/sources/test_mpi_data_communicator.cpp#L1644-L1649
https://github.com/KratosMultiphysics/Kratos/blob/f8aeb637293ce5177d6bca41d629fd31a8b4a24b/kratos/mpi/tests/cpp_tests/sources/test_mpi_data_communicator.cpp#L1717-L1722

**Scope**
- Core

**Comment by loumalouomega** [comment]
I don't know, when I extended the tests I keep it as it is... (@jcotela maybe knows)

**Comment by matekelemen** [comment]
oh no, all of those linked cases are in `#ifdef KRATOS_DEBUG` blocks. Maybe `KRATOS_DEBUG` is not defined in the CI?

**Comment by sunethwarna** [comment]
The thing is, even in my PC i dont get the warnings. Furthermore, I can fail them manually by changing some params meaning they are getting compiled.

**Comment by jcotela** [comment]
Some observations:
1. The tests are wrong, as @sunethwarna is saying. Will push a branch bringing them closer to the original intent.
2. I think @matekelemen is right and the unused variable warnings do not trigger for complex types. If I declare an extra double variable on the same test, next to the unused vector, it is correctly reported. Some searching turned up an answer to [this](https://stackoverflow.com/questions/22112784/why-is-unused-variable-warning-not-reported-for-all-variables) stackoverflow question for gcc that also agrees.
3. I am getting a lot of warnings of the type 
```
/home/jcotela/dev/Kratos/kratos/includes/data_communicator.h:940:40: warning: ‘void Kratos::DataCommunicator::CheckSerializationForSimpleType(const T&, Kratos::DataCommunicator::TypeFromBool<false>) const [with T = long unsigned int]’ is deprecated: Calling serialization-based communication for a simple type. Please implement direct communication support for this type. [-Wdeprecated-declarations]
  940 |         CheckSerializationForSimpleType(rSendObject, TypeFromBool<serialization_is_required<TObject>::value>());
```
These worry me quite a bit, because it means that we are serializing the `long unsinged int`s (in this case, but I see those for doubles too) using the Kratos serializer and sending them as text instead of using the correct MPI type. Are you guys also getting those?

**Comment by jcotela** [comment]
Ok, regarding the last point (sending data through serialized streams instead of using the correct mpi type), it looks like it was an issue only for Send/Recv using a single value (not a vector of values), which was being used in the tests but did not have a specialized implementation, so it was defaulting to the streams. I created a separate PR for this, see #11440

**Comment by jcotela** [comment]
Closing since I believe that the points discussed here have all been addressed. Feel free to reopen otherwise.
