### ISSUE TITLE
Point::Coordinate() method inconsistency?

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#1152]
The Point class has a set of Coordinate() and Coordinates() methods that seem somewhat inconsistent

```
CoordinatesArrayType &Coordinates()
```

and 

```
/** This is an access method to get a reference to point's coordinate by
    indices. For example this function return references to x, y and z coordinate whith 1, 2
    and 3 as input respectively.
    */
    double &Coordinate(IndexType CoordinateIndex)
    {
        KRATOS_DEBUG_ERROR_IF((CoordinateIndex > 3)||(CoordinateIndex == 0)) << "Coordinate index = " << CoordinateIndex << " is out of range [1..3]";
        return this->operator[](CoordinateIndex - 1);
}
```

Note that the first returns an array and the second uses Fortran (?!) numbering, so that

```
auto r_coordinates = point.Coordinates();
r_coordintates[0] == point.Coordinate(1);
r_coordintates[1] == point.Coordinate(2);
r_coordintates[2] == point.Coordinate(3);
```

Which seems needlessly confusing...

Which is the use case for the `Coordinate` methods? It seems to me that anything they can do can be also achieved with `Coordinates` or the `X()` `Y()` and `Z()` member functions.

@KratosMultiphysics/technical-committee Can we remove the `Coordinate` methods?

**Comment by pooyan-dadvand** [comment]
This is my fault! On time of implementing the point for compatibility reason with a some library (that I cannot remember which was after 15 years...) I have put this numbering and afterward I have always avoid using it because it was confusing for me also. So I agree that we can remove it and use the [] operator instead.

**Comment by ipouplana** [comment]
Hi @jcotela , Lorenzo just told me that you will change the processes in the DamApplication that used the Coordinate(i) method (thanks!). The thing is that I also used that method in a couple of processes in the PoromechanicsApplication, but since they are related to a .tcl I use for the problemtype, I prefer to change them myself (only those in the PoromechanicsApplication).
Regards

**Comment by loumalouomega** [comment]
I am very concerned of this issue. I had many problems when I started with Kratos because of this. The proper thing would be to use the deprecated macro instead of throwing the error?

**Comment by pooyan-dadvand** [comment]
Talking in technical committee we will make it deprecated until January 15th and then it will be removed for release 5.3.

**Comment by jcotela** [comment]
@loumalouomega The plan is to deprecate it, then remove the `Coordinate()` method altogether.

**Comment by jcotela** [comment]
@KratosMultiphysics/technical-committee The plan was to remove the deprecated methods by Jan 15. If you give me the OK, I'll go ahead and delete them.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/structural-mechanics saying yes!
