### ISSUE TITLE
[External] VexCL out of date

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#11795]
The version of `VexCL` we have right now is incompatible with our `AMGCL` version. I've said this before, but our dependencies could use an update.

@roigcarlo is there a special trick to updating our dependencies, or can I go ahead and grab a copy of `VexCL`, copy it into `Kratos` and open a PR myself?

By the way, I'm not much of a fan of `git submodule`, but it's a lot more appropriate than just copying parts of other repositories into Kratos. We're lacking basic information of our dependencies (version, license, etc.) that make debugging extremely difficult. Furthermore, it makes `Kratos` more difficult to be adopted by companies since they must vet any software they're using (including dependencies), and they're completely in the blind about our external libs.

**Comment by loumalouomega** [comment]
In certain moment we decided not t use submodules because we had very bad experiencies with it. People doesn't know how to interant with them and everyone corrupted the repo.

**Comment by roigcarlo** [comment]
Yep, just copy paste the new version and run all the tests. 

As @loumalouomega says we are against submodules because most people don't know how to properly initialize the repo if we add them (is sad, but it is what it is)

I understand the worries about the lacking of info, but the way we decided to go is that, if the library is hosted in our repo, that is the version you have to use ( which is the case for AMGCL ) for example. Other versions are specified in the realme.

Anyway, we have an open discussion about ways to improving versioning so feel to say it there, so we can take a look at all the problem as a whole https://github.com/KratosMultiphysics/Kratos/discussions/11776

That being said VexCL is not widely used so I supose there will be no issuses.

**Comment by matekelemen** [comment]
I understand all the hate for submodules, but then we need an alternative to getting version info about external libs. I'm continuing the discussion in #11776.
