### ISSUE TITLE
[GeoMechanicsApplication] Investigate extracting the drainage functionality from the elements

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#12067]
As a developer, I want to investigate how to separate the drainage functionality from the elements, such that the elements become more maintainable and configurable.

In discussions we discussed the following proposal for the drainage policy structure:
![Image](https://github.com/KratosMultiphysics/Kratos/assets/56549273/81a0e960-260e-4bae-af08-06871a9f1f92)

In this investigation, the feasibility and (if possible) concrete steps to implement this structure are documented

### Acceptance criteria
- A follow-up issue is created and refined for the implementation or further investigations
- Investigation is documented

**Comment by markelov208** [comment]
Currently, DrainedUPwSmallStrainElement and UndrainedUPwSmallStrainElement implement the drainage behaviour. Their base class, UPwSmallStrainElement, implements a general case. The difference between these classes is a content of CalculateAndAddLHS and CalculateAndAddLRHS functions. For example, UPwSmallStrainElement ::CalculateAndAddLHS holds
1.	CalculateAndAddStiffnessMatrix
2.	CalculateAndAddCompressibilityMatrix
3.	CalculateAndAddCouplingMatrix
4.	CalculateAndAddPermiabilityMatrix
When UPwSmallStrainElement::DrainedUPwSmallStrainElement  only 1 and UPwSmallStrainElement::UndrainedUPwSmallStrainElement  only 1-3. 
	
In principle, these two functions (LHS/RHS) are responsible for all other cases, for example, Pw, steady state, transient.

Providing references on local functions (1-4) as input to these two functions is very difficult due to templating and different instances. For example, [c++ - C2276 '&': illegal operation on bound member function expression - Stack Overflow](https://stackoverflow.com/questions/55651688/c2276-illegal-operation-on-bound-member-function-expression).

The decision is to create static functions 1-4 that uses static functions. 
Therefore, drainage_policy (or transport_policy) will provide functions: 
     AllToLHS(Matrix&, …, const callBack) and 
     AlltoRHS(Vector&, …, const callBack).

callBack will hold references on required functions and it will be populated by an element.

**Comment by rfaasse** [comment]
Closing this issue after review. Follow-up issues are created and investigation is documented in the comments
