### ISSUE TITLE
No module named 'Kratos'

### ISSUE THREAD

**Issue by mokhairymahmoud** [KratosMultiphysics/Kratos#12276]
**Description**
I am trying to compile and run Kratos on my local machine, I have been following the instruction specified here https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md. The code compiles well and when I come to include KratosMultiphyscs in a python script I face this problem: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/Kratos/bin/Release/KratosMultiphysics/__init__.py", line 36, in <module>
    from Kratos import *
ModuleNotFoundError: No module named 'Kratos'

I have the feeling there is something missing but i have followed the instruction to the word. Any ideas ? 

**Environment**
- OS: Ubuntu 20
- Branch: master
- Python 3.10.13

**Comment by matekelemen** [comment]
Kratos' python modules consist of 2 parts:
- pure python modules (such as `KratosMultiphysics`, which your system seems to be able to find)
- binary modules that get loaded while importing pure python modules (such as `Kratos`)

Looks like your system finds the pure python module but fails to load the binary module. This usually happens when the version of python that you compiled for is not the same as the one you're trying to run your script with.

Make sure they're the same:
- check the version of python you're executing the script with (eg.: `python3 --version`)
- check the binaries you compiled:
   - go to `libs` directory of your Kratos installation (usually `<your_kratos_source_dir/build/Release/install/libs>`)
   - you should see some files like `Kratos.cpython-310-x86_64-linux-gnu.so` (`310` here indicates that the module was compiled for python 3.10)
- if they don't match that's the problem, in which case recompile for the python interpreter you're planning to use for your scripts

**Comment by mokhairy2019** [comment]
Thanks a lot. That solved my problem
