### ISSUE TITLE
[GeoMechanicsApplication] Document + communicate K0 verification

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#12499]
Data for verification of the K0 procedure in 2D is gathered and communicated to relevant stakeholders.

Data can be found in:
- [Horizontal layer test case](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/GeoMechanicsApplication/tests/test_k0_procedure_process/test_k0_procedure_with_horizontal_layers/README.md)
- [Tilted layer test case](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/GeoMechanicsApplication/tests/test_k0_procedure_process/test_k0_procedure_with_tilted_layers/README.md)
- [Kratos user group presentation](https://publicwiki.deltares.nl/display/PROJ/Kratos+User+Group+Meeting+2)

**Comment by indigocoral** [comment]
### **K0 Procedure Verification in Kratos GeoMechanics Application and Comparison with Plaxis**


[K0 Procedure.pdf](https://github.com/user-attachments/files/16281120/K0.Procedure.pdf)


A presentation was made with the results of a series of tests conducted to verify the K0 procedure in the Kratos GeoMechanics Application in comparison to Plaxis using the Hardening Soil model. The tests aim to evaluate the behavior of soil layers under various conditions of Overconsolidation Ratio (OCR) and unit weights. Additionally, an investigation into Pre-Overburden Pressure (POP) is performed in Plaxis, as this feature is not yet implemented in Kratos.

### **Test Description**

The tests are categorized into two main groups based on the orientation of the soil layers (horizontal and tilted) and the OCR values. Unit weights of the soil vary across three soil layers,

**Test 1: Horizontal Layers**

- Test 1a: OCR = 1,  K0 set to 0.5 in Kratos.

- Test 1b: OCR = 1.4, K0 set to 0.6 in Kratos.

- Test 1c: Different unit weights for soil layers, K0 set to 0.5 in Kratos.

**Test 2: Tilted Layers (Slope)**

- Test 2a: OCR = 1, K0 set to 0.5 in Kratos.

- Test 2b: OCR = 1.4, K0 set to 0.6 in Kratos.


### **POP Investigation in Plaxis**

POP's relationship with OCR is examined, particularly how it influences effective vertical stress. The formulation of POP and its relation to OCR has been shown below:

![Image](https://github.com/user-attachments/assets/2e03f42a-c92f-4003-91e3-91b86260134a)

With the assumption of OCR=1.4, the POP will be equal to 0.4 times the effective vertical stress for each layer of soil. Since the POP can vary in the depth of the soil, an investigation was done to understand it better. POP is analyzed at three different depths (bottom, middle, and top of each soil layer). Results are compared with scenarios where OCR = 1.4 is uniformly applied across layers.

[POP_OCR_comparison.xlsx](https://github.com/user-attachments/files/16281053/POP_OCR_comparison.xlsx)

---------------------------------------------------------
**Note:** It was observed that in Kratos, the K0 value specified by the user in the material parameters always overwrites the OCR value defined in the project parameters file. This behavior mirrors Plaxis.
