### ISSUE TITLE
Basic Questions Regarding Kratos Usage

### ISSUE THREAD

**Issue by duribes** [KratosMultiphysics/Kratos#12755]
Dear all,

I am a completely new user of Kratos, so I have some very basic questions:

1) Is it mandatory to use GiD? Are there any examples using plain text files?

2) I was able to compile Kratos in release mode on Ubuntu 22.04. It compiled well. However, I am not sure how to run it.

   After the compilation, I already did the following:

   export PYTHONPATH=$PYTHONPATH:$HOME/Kratos/bin/Release
   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/Kratos/bin/Release/libs

   But when I try in the terminal "from KratosMultiphysics import *" 

   I get the follwoing error:

   Command 'from' not found, but can be installed with:
   sudo apt install mailutils

   I tried downloading the “2_Kratos_input_files_and_IO” files but when I type “python3 ./MainKratos.py”, I get the following    error: “Traceback (most recent call last):
  File "/home/diego_uribe/Software/2_Kratos_input_files_and_IO/./MainKratos.py", line 3, in <module>
    import KratosMultiphysics
ModuleNotFoundError: No module named 'KratosMultiphysics'”

Is there any documentation explaining the theory behind the implementation without using GiD? I am particularly interested in MPM applications.

Best regards,
Diego Uribe

**Comment by AlejandroCornejo** [comment]
Hi,
This error is usually related to a bad PATH definition. These kratos folders are indeed those ones?

Can you try to run a file with:

`import KratosMultiphysics`

pinging @KratosMultiphysics/mpm

**Comment by takeshimg92** [comment]
>Is it mandatory to use GiD? Are there any examples using plain text files?

Absolutely not mandatory, as long as you can write MDPA files and project parameters as JSON files, you can use instances of AnalysisStage to run Kratos regardless of any GUI.

**Comment by andimkatili** [comment]
Hi Diego,

The error that you get “_Command 'from' not found_” is most likely because you use the command without launching python.

To test your installation, you can run a python script (some-name.py) with 
`from KratosMultiphysics import *`
inside the script. Like Alejandro mentioned before.

However, since you got “ModuleNotFoundError: No module named 'KratosMultiphysics'”, it means that you have a bad PATH definition. 

Are you sure the path in these commands are correct? Where did you put your Kratos folder?

> export PYTHONPATH=$PYTHONPATH:$HOME/Kratos/bin/Release
>     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/Kratos/bin/Release/libs

**Comment by rubenzorrilla** [comment]
> > Is it mandatory to use GiD? Are there any examples using plain text files?
> 
> Absolutely not mandatory, as long as you can write MDPA files and project parameters as JSON files, you can use instances of AnalysisStage to run Kratos regardless of any GUI.

Adding to @takeshimg92 's comment that you can also use Salome as preprocessor and write the mesh input file in MED format.

**Comment by sunethwarna** [comment]
Small guide on how to read in MED files from SALOME can be found in the following link
https://kratosmultiphysics.github.io/Kratos/pages/Kratos/For_Users/Getting_Started/Input_Output_and_Visualization/Salome_input.html

**Comment by duribes** [comment]
Thank you very much for all your answers. In fact, I had issues related to a bad PATH definition, but I managed to fix it. As Andi mentioned, I’ve already tested my installation by running a Python script with:

from KratosMultiphysics import * 

and it worked perfectly!" 

I will try to follow Suneth's advice to work with MED files!

**Comment by gzjing** [comment]
> 2\. I was able to compile Kratos in release mode on Ubuntu 22.04. It compiled well. However, I am not sure how to run it.

For the compilation, did you check if the configuration file used (```configuration.sh``` or ```configuration.bat file```) include the MPMApplication? If not, it may be possible that the import failed because the MPMApplication was not compiled.

See https://github.com/KratosMultiphysics/Kratos/tree/master/applications/MPMApplication under Getting Started -> Prerequisites for which lines to look for
