### ISSUE TITLE
[Structural] Impose sliding boundary condition within StructuralMechanics app

### ISSUE THREAD

**Issue by takeshimg92** [KratosMultiphysics/Kratos#12822]
**Description**
I want to have a minimal working example of a sliding boundary condition inside a StructuralMechanics problem. Essentially, given a unit vector $n$ normal to a surface, I want to add the constraint that the displacement is perpendicular to it: $$u\cdot n = 0$$.

I see two ways of thinking about this:
1. Using the [MPC interface](https://github.com/KratosMultiphysics/Kratos/wiki/%5BKratosAPI%5D-MultiPoint-Constraint-(MPC)-interface), but I see some issues with this. The constraint is $n_x u_x + n_y u_y + n_z u_z = 0$, which has 2 independent degrees of freedom. Also, I am having some difficulty finding good examples in the docs / codebase.
2. Using local coordinate axes: if I can somehow obtain a local coordinate with $n = e_z$, then I can just impose that `DISPLACEMENT_Z` is zero and I am done. However, I have player around with the local axes in ProjectParameters.json and they don't make a lot of sense to me - for a standard solid element (like `SmallDisplacementElement3D4N` and its associated triangular surface) using GetValue on the variables `LOCAL_AXIS_1` etc. only returns zero. Maybe I am doing something wrong.
* I looked through [this issue](https://github.com/KratosMultiphysics/Kratos/issues/136) and [this page on local axes orientation](https://github.com/KratosMultiphysics/Kratos/wiki/Local-axes-orientation) but they didn't help with my problem.

Thank you in advance for your help!

**Comment by AlejandroCornejo** [comment]
@RiccardoRossi @roigcarlo

**Comment by matekelemen** [comment]
> I want to add the constraint that the displacement is perpendicular to it $u \bullet n = 0$.

> The constraint is $n_x u_x + n_y u_y + n_z u_z = 0$ , which has 2 independent degrees of freedom.

Well, a 2D surface needs exactly 2 independent variables so I see no problem there. I'm a bit surprised to find no `Process` that would set `MasterSlaveConstraint`s, but you can always just write your own and specialize it to your case (I haven't tested this code but it should give you a good hint on how to make it work):

1) Create a new python script in your project directory (e.g.: `MakeSurfaceSlidingConstraint.py`) and implement a `Process` that adds a `MasterSlaveConstraint`s that implement your constraint equation.
    ```py
    # --- Kratos Imports ---
    import KratosMultiphysics

    # --- STD Imports ---
    import typing


    class MakeSurfaceSlidingConstraint(KratosMultiphysics.Process):
        def __init__(self,
                    model: KratosMultiphysics.Model,
                    parameters: KratosMultiphysics.Parameters):
            super().__init__()

            # Normally you should do some input validation but I'll skip it
            # here for the sake of brevity.
            self.model_part: KratosMultiphysics.ModelPart = model.GetModelPart(parameters["model_part_name"].GetString())
            self.node_id: int = parameters["node_id"].GetInt()
            self.normal: "KratosMultiphysics.Vector" = parameters["surface_normal"].GetVector()


            @classmethod
            def GetDefaultParameters(cls: "typing.Type[MakeSurfaceSlidingConstraint]") -> KratosMultiphysics.Parameters:
                return KratosMultiphysics.Parameters(R"""{
        "model_part_name" : "",
        "node_id" : 0,
        "surface_normal" : [1.0, 0.0, 0.0],
    }""")


        def ExecuteBeforeSolutionLoop(self) -> None:
            """ I'm putting the logic in ExecuteBeforeSolutionLoop because the Solver is already
                initialized at this point (check AnalysisStage::Initialize) so the Nodes should
                be constructed and could be found by ID. The constructed MasterSlaveConstraints will
                persist across nonlinear iterations and time steps.
            """
            # I'm assuming you don't have any other MasterSlaveConstraints, so I'll
            # set this constraint's ID to 1.
            constraint_id = 1

            # The linear equation n_x * u_x + n_y * u_y + n_z * u_z = 0 is equally valid
            # for any master/slave partitioning, but the Kratos interface demands we choose
            # a slave and masters explicitly.
            # => pick u_x as the slave and the rest (u_y, u_z) as masters.
            #    KEEP IN MIND THAT n_x SHOULD NOT VANISH but I'll ignore that case here.
            node: KratosMultiphysics.Node = self.model_part.GetNode(self.node_id)
            slave_dofs = [node.GetDof(KratosMultiphysics.DISPLACEMENT_X)]
            master_dofs = [node.GetDof(KratosMultiphysics.DISPLACEMENT_Y),
                        node.GetDof(KratosMultiphysics.DISPLACEMENT_Z)]
            relation_matrix = KratosMultiphysics.Matrix([[component for component in self.normal]])
            constraint_gap = KratosMultiphysics.Vector([0.0, 0.0, 0.0])

            self.model_part.CreateNewMasterSlaveConstraint("LinearMasterSlaveConstraint",
                                                        constraint_id,
                                                        master_dofs,
                                                        slave_dofs,
                                                        relation_matrix,
                                                        constraint_gap)


    def Factory(parameters: KratosMultiphysics.Parameters,
                model: KratosMultiphysics.Model) -> MakeSurfaceSlidingConstraint:
        return MakeSurfaceSlidingConstraint(model, parameters)
    ```
2) Insert the created process into the list of constraint processes in your project params JSON:
    ```json
    {
        "python_module" : "MakeSurfaceSlidingConstraint",
        "process_name" : "MakeSurfaceSlidingConstraint",
        "Parameters" : {
            "model_part_name" : "name-of-your-model-part",
            "node_id" : constrained_node_id,
            "surface_normal" : [n_x, n_y, n_z]
        }
    }
    ``` 

##

Keep the comments in my code in mind and let me know whether it works if you try it.

**Comment by matekelemen** [comment]
*Just a quick side note that the GitHub wiki is being retired in favor of the docs at our repo page. You'll find it on the right panel of our GitHub landing page. It's currently at https://kratosmultiphysics.github.io/Kratos/, and the corresponding docs you were looking at are [here](https://kratosmultiphysics.github.io/Kratos/pages/Kratos/For_Developers/Data_Structures/MultiPointConstraint_Interface.html).*

**Comment by takeshimg92** [comment]
Hi @matekelemen thanks for the detailed answer. Is it ok to ask a few follow-up questions?

1. I see this is done at node level rather than at Condition level. The latter would be interesting since normals are naturally defined. Any idea how to adapt to that?
2. I am trying to make sense of the matrix algebra of your implementation. In my understanding, I want to ensure that $$n_x = - (n_y/n_x) u_y - (n_z/n_x) u_z$$, so the relation matrix would not be `KM.Matrix([[component for component in self.normal]])` but rather 

```python
nx, ny, nz = self.normal
relation_matrix = KM.Matrix([[-ny/nx, -nz/nx],[1, 0], [0, 1]])
```
so that I can express $u_x, u_y, u_z$ in terms of $u_y, u_z$. Am I understanding something wrong about how the relation matrix works?

**Comment by matekelemen** [comment]
You're (almost) right. I was thinking in terms of a proposed change (#12787) rather than the current interface. Sorry about that.

## Correction

> express $u_x$, $u_y$, $u_z$ in terms of $u_y$, $u_z$.

You're on the right track but it seems like the docs are inaccurate and misled you a bit. The relation matrix you need to pass to `MasterSlaveConstraint` is not exactly the same as the relation matrix in the docs. In particular, it doesn't have rows for the master Dofs.

```math
u_{s} = \bar{T} u_{m}
```

where $u_s$ denotes the slave Dofs, $u_m$ the master Dofs, and $\bar{T}$ the relation matrix in the implementation. **In short, $\bar{T}$ defines the slaves in terms of the masters.**

In your example:
```math
\begin{bmatrix}
    u_x
\end{bmatrix}
=
\begin{bmatrix}
    -\frac{n_y}{n_x} & -\frac{n_z}{n_x}
\end{bmatrix}
\begin{bmatrix}
    u_y \\ u_z
\end{bmatrix}
```

## Example

Here's a complete example you can run: [slide_on_surface.zip](https://github.com/user-attachments/files/17724524/slide_on_surface.zip)

It consists of 1 tetrahedron that has a loaded node at the origin, while the rest of the nodes are fixed. The node at the origin is constrained to remain on a surface.

*Note that I made some changes to `MakeSurfaceSlidingConstraint.py`.*

## Normals from `Condition`s?

> I see this is done at node level rather than at Condition level. The latter would be interesting since normals are naturally defined. Any idea how to adapt to that?

That's ambiguous so I'll need a bit more info on what you're trying to do. The problem is that adjacent conditions will not necessarily lie on the same surface, meaning that their shared nodes will have conflicting constraints.

Of course if you *somehow* know that you won't be imposing constraints on adjacent conditions, you have several options:
1. the simplest (and ugliest) is to add a condition ID to the parameters of `MakeSurfaceSlidingConstraint` and fetch its normal instead of the one in the parameters. It does the job, but leaves plenty of room for bugs (e.g.: the constrained node might not be part of the provided condition).
2. Collect the conditions you want constrained into a `ModelPart`, and write a process that computes condition normals and copies the results to nodes. There's a [utility](https://github.com/KratosMultiphysics/Kratos/blob/588cf7f9abf8a54461e7a549f064ec35944fb61f/kratos/utilities/normal_calculation_utils.h#L59) that does exactly this and even has [python bindings](https://github.com/KratosMultiphysics/Kratos/blob/588cf7f9abf8a54461e7a549f064ec35944fb61f/kratos/python/add_geometrical_utilities_to_python.cpp#L215), so your job would just be putting this into a process. Note that this utility will interpolate the normals of adjacent conditions.

## Notes

*You may have noticed that our multifreedom constraint (a.k.a multipoint constraint, a.k.a `MasterSlaveConstraint`) infrastructure while working, is a bit wonky. We've all agreed clear it up, but are still discussing how exactly to do it. If you have a particular shortcoming or suggestion in mind, don't hesitate to open an issue about it, or explain it in #12787.*

*One issue in particular that you may run into in the future, is that $n_x$ in your example must not vanish. This is because our current system demands you (the user) define a master/slave partitioning manually, instead of letting an algorithm dynamically decide how to do it.*

**Comment by takeshimg92** [comment]
@matekelemen Thank you so much! The example runs and the explanation is clear. I have more than enough material to work with.
I will be closing this issue for now since I have no follow-up questions for the moment.
