### ISSUE TITLE
Giving an initial displacement to the beam results in very high initial acceleration

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#1302]
I was assuming that giving an initial value to displacement would react as it was from ever until the first step so I can use it for trigger a natural vibration. Nevertheless I observed that it calculates the acceleration based on dt which gives very high displacements. 
([example](https://github.com/KratosMultiphysics/Kratos/files/1631394/dynamic_beam.gid.zip) attached)

@KratosMultiphysics/structural-mechanics any comment?

**Comment by loumalouomega** [comment]
Right now the scheme just accounts the displacements, in a beam the influence of the rotation is significant. Maybe computing the dynamic contribution of the rotation DoF will solve this problem. This can be solved creating an independent scheme or as I suggested define a method in the variable like "HasTimeDerivative" and so on. With this will be possible to compute in a general way any derivative without reimplementing again all the shemes

**Comment by jcotela** [comment]
@loumalouomega from the example, it seems to me it is a simpler issue with the initial conditions, in this case. @pooyan-dadvand is applying an initial displacement, and instead of oscilating with an amplitude given by the initial condition, it increases the amplitude. It looks like it "invents" an initial velocity of `(initial_displacement - rest_position) / dt` and solves that problem instead.

**Comment by loumalouomega** [comment]
True (in any case the contribution of the rotation exists, and for a consistent solving should be taken into account)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/structural-mechanics any advances on this?

**Comment by pooyan-dadvand** [comment]
The problem is as @jcotela mentioning.

**Comment by philbucher** [comment]
ping @KlausBSautter

**Comment by RiccardoRossi** [comment]
ping @KratosMultiphysics/structural-mechanics

**Comment by KlausBSautter** [comment]
hi @pooyan-dadvand . I had a look at your set-up and the problem is that you have multiple nodes but only assign an initial displacement to the cantilever tip node. Here I provided 3 solutions:
[dynamic_beams.zip](https://github.com/KratosMultiphysics/Kratos/files/1699602/dynamic_beams.zip)

1.) use only 1 element. This will lead to a wrong frequency for the natural vibration but will behave as you estimated
2.) use multiple elements and apply a const. force (3 * displ * L³/EI) at the end node instead of an initial displ. This will trigger the natural vibration with a vibration period of ca. 0.003 1/s (sqrt(EI * 1.875⁴/(density * area * L⁴))
3.) use a ramp force which is increased until the wished displacement is reached and then release the structure. This will then result in exactly the behavior you predicted.


I also had the idea of a static analysis first to get each nodal displacement (so that the end node has the wished displ) and then apply all these nodal values as an initial displacement. But oddly enough this does not work.

I hope this helps you!

**Comment by loumalouomega** [comment]
I just want to say that now with #1461 still having huge accelerations (and angular accelerations). Tomorrow I will research more

**Comment by loumalouomega** [comment]
OK, I did some experiments, I worked in non linear range, same problem. I deactivated the acceleration and velocity prediction as @jcotela suggested, same problem. I worked with different schemes, and the only one giving reasonable accelerations is the backward euler in lnear range, but the non linear does not converge

**Comment by KlausBSautter** [comment]
Hi if you want to prescribe an initial displacment you need to prescribe the total shape, i.e. not only deformation to one FE-node but displacement values and rotation values to each node (you can get this from a static linear pre-calculation)

**Comment by loumalouomega** [comment]
That makes sense, but instead maybe is a better idea to solve a static linear problem instead and used as a prediction value

**Comment by KlausBSautter** [comment]
you can look at the 3rd example I uploaded. Where I do a linear dynamic analysis increasiing the load until the desired shape is reached and then set the force to 0. After this the problem is exactly what we want: a presribed displacement which vibrates in the natural eigen frequency

**Comment by pooyan-dadvand** [comment]
Thanks @KlausBSautter for checking the problem and your comment about static make sense to me. This would be a perfect case for stages. I also agree with force, and actually I have used it for my students. 

But still my concern is the initial acceleration which causes by the fact that you assume at `t=0` the `u=0` and apply my initial deformation to calculate the initial acceleration using Dt. So in case that I wanted to propagate the wave only by moving the head node, the result is not what I would expect.

**Comment by philbucher** [comment]
is this solved?

**Comment by pooyan-dadvand** [comment]
I'm not convinced and waiting for your answer! :smiley:

**Comment by mpentek** [comment]
Dear all,

For what it is worth, I was also creating examples some time ago for structural mechanics before there was a possibility to have eigenvalues and -forms. For that, I was using a displacement for a cantilever beam (whether it was modeled with solids, shells or something else) based on the assumed first eigenform. 
I had to prescribe an initial displacement for all the nodes. Note, that if you want to exactly reproduce the free vibration of the first mode (or any particular mode), you should apply exactly the nodal displacements/rotations (scaled) of the first eigenmode.
As far as I remember, the accelerations, velocities and displacements were reasonable, although I did not do an exact comparison. When I applied only an approximate initial shape, I also got some spurious oscillations of the internal nodes.

Maybe this does not totally apply to the case in mention.

**Comment by pooyan-dadvand** [comment]
I have checked it again and now it works as expected. The initial acceleration only depends on the section and not Dt. I'm not sure if the first one was my error in somewhere or something has been improved in the new version.

Thanks all for their comments.
