### ISSUE TITLE
Missing Meshing application when running Embedded Fluid - 5.2.3

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#1305]
Detected bug:
``` python
from KratosMultiphysics.MeshingApplication import *
ImportError: No module named 'KratosMultiphysics.MeshingApplication'
```
Fluid Embedded Application
Kratos 5.2.3 (GiD Internet Retrieve)

Temporal solution:
- Open MainKratos.py and comment that line

For further releases:
- Should MeshingApplication be compiled and deployed?
If not: 
- Should released EmbeddedFluid MainKratos.py script import MeshingApplication?

@KratosMultiphysics/fluid-dynamics 
@KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
Since no one is answering... I remember this to be a problem because of tetgen. For me there is no problem to include the application in the releases. It is technically possible, but I am not sure we should do it. 

@KratosMultiphysics/technical-committee I recall someone telling me this was not necessary for the release, can we confirm and comment the imports to meshing?

**Comment by roigcarlo** [comment]
We have speak and it seems that tetgen is no longer needed, so next release will have the meshing

**Comment by jginternational** [comment]
Bravo!
