### ISSUE TITLE
Can't check if Element has NULL properties because all calls to the properties have the check inside

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#1409]
I wanted to do some operations in the destructor of an element. These operations depend on some information I get from the properties. But the load of Kratos creates Elements with NULL properties. So I wanted to do something like:
`if (pGetProperties != nullptr) { a = GetProperties()[YOUNG_MODULUS]; }`
However, I did not find any method that gets the pointer without doing the check (in debug mode).
One possible solution would be a method called 'HasProperties()'.
Another possibility is to leave some methods without the check. I prefer the first one.

**Comment by jcotela** [comment]
You mention a load call... Is this related to serialized and then loaded elements? If so, this sounds like a bug to me (the element not saving and loading its properties). 

If it is not related to serialization, how are you creating the elements? I would expect that "normal" ways of creating elements do given them properties...

**Comment by maceligueta** [comment]
One element of each type is created when you load your application. Those elements are created with mpProperties pointing to nullptr. When they are destroyed, they use the destructor I made, which needs GetProperties().

**Comment by jcotela** [comment]
Oh I see, I didn't understand. If we can not agree on a better solution, you have the option of using a different constructor when initializing the elements of your application (in the application.cpp), so that they get a property.

Actually, the error is rather new (I wrote the offending check in the pGetProperties method... sorry). I would say we can leave the nullptr checks in the versions of GetProperties that return a reference, and let the user verify that the pointer is not null in the pointer variants. In this way, the methods always return something "useful" and well-formed. @pooyan-dadvand do you think this could be a solution?

**Comment by pooyan-dadvand** [comment]
After discussion in TC we arrive to conclusion that implementing `HasProperties` is the best option

**Comment by maceligueta** [comment]
@jcotela , this is the conflictive line:
https://github.com/KratosMultiphysics/Kratos/blob/27dcd5e2f6269d54497b5cf8559a5528dbe86dd3/applications/DEM_application/custom_elements/cluster3D.cpp#L37
