### ISSUE TITLE
Debug version of Kratos under Windows

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#1464]
I try to debug Kratos under Windows but I cannot couple Visual studio code with MVS.
I followed the tutorial “[How to cross debug Kratos under Windows](https://github.com/KratosMultiphysics/Kratos/wiki/How-to-cross-debug-Kratos-under-Windows)”
I can run Kratos in debug. When I start the debug with visual studio code, the process don’t stop at the breaking point of MVS.
Can you help me?

**Comment by roigcarlo** [comment]
Hi @PhilippeBussetta 

If the method in the wiki does not work for you, there is an alternative way to debug, but it does not allow cross debug, just the C++ part. Since you mention you put the breakpoints in MVS, I will asume this is the case.

In order to debug this way:
- Make sure the code is compiled in debug mode:
![image](https://user-images.githubusercontent.com/1935791/35916965-859b3fe8-0c0c-11e8-867a-46a0f8f62f69.png)

- Go to Kratos porject, on the solution explorer, click properties and go to Debug menu. you should see this:
![image](https://user-images.githubusercontent.com/1935791/35917027-d5f36934-0c0c-11e8-8730-943ac6aeb213.png)

here you need to change 
- __Command__: You should select python.exe you used to compile kratos. Ex: _C:\python36\python.exe_
- __Command arguments__: Name of the script of the case you want to run.
- __Working directory__: Path to the folder where the script above is located
- __Enviroment__: You have to a add 
    - __PATH__: so it also points to the "Libs" directory of Kratos where you have compiled the code. Ex: _C:\Kratos\Libs_
    - __PYTHONPATH__: it has to point to your kratos folder where the KratosMultiphysics directory is located. typically the same as above but without libs. Ex: _C:\Kratos\Libs_

After dat just right click in the Kratos -> Debug -> Start new debug instance:
![image](https://user-images.githubusercontent.com/1935791/35917255-bec136c8-0c0d-11e8-90ce-389c384cad57.png)

Let me know if this works for you

**Comment by PhilippeBussetta** [comment]
Great, you solve my problem.
Thank you

**Comment by ddiezrod** [comment]
I had the same problem and it was solved the same way. I think this should probably go to wiki

**Comment by roigcarlo** [comment]
Ok, I will move if this is helpful :+1:

**Comment by alecontri** [comment]
I am encountering the same exact same problem. I configured Kratos in FullDebug mode building from command prompt (-DINSTALL_RUNKRATOS=OFF). Then I followed the steps in order to debug the C++ code using only Visual Studio as described in the Wiki "Debugging Kratos using Visual Studio", which are the ones described above.
I am using the GiD example from the ParticleMechanicsApplication as test case. It runs without errors from prompt and from Visual Studio when I use "Start a new instance" from Kratos>Debug in the solution explorer. Unfortunately the breakouts are completely ignored (I placed some randomly in Initialize and SetGeneralVariables and in CalculateElementalSystems in the updated_lagrangian.cpp file). Moreover, if I try using "Start a new instance" selecting the ParticleMechanicsApplication I get an error saying "Invalid Win32 application".
I attach an image on how I've modified Kratos Property Pages> Debugging> Environment 
![Cattura](https://user-images.githubusercontent.com/82971238/126913151-a011b425-8671-4979-9eba-29533481d810.JPG)

Thank you in advance for your help!
