### ISSUE TITLE
BuilderAndSolver arguments for SystemSolver in Trilinos is not consistent

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1502]
For the implementation of the MortarMapper I need a Builder&Solver for solving the Mass-Matrix Problem.
The Mapper itself should be independent of the type of execution (serial/parallel), same as what is done currently.

I would like to call the function `SystemSolve` in order to do the solution of this.

The problem is now that the `TrilinosBlockB&S` takes an additional argument (a `ModelPart`), so I cannot do this.
This `ModelPart` is needed to do the following: `mpLinearSystemSolver->ProvideAdditionalData(A, Dx, b, BaseType::mDofSet, r_model_part);`

The normal BlockB&S also has a function that provides a `ModelPart`, there it is called `SystemSolveWithPhysics`

In order to make everything consistent we could add the function `SystemSolveWithPhysics` to the B&S Baseclass and rename the `SystemSolve` in the trilinos version to `SystemSolveWithPhysics`

what do you think @jcotela @pooyan-dadvand @RiccardoRossi  @roigcarlo ?

**Comment by jcotela** [comment]
Actually, there seems to be some confusion with the inheritance, since the "offending" function is marked virtual but does not override anything in the base class (this is from before the move to C++11, so where I see virtual I read override). @RiccardoRossi which solvers need to call the AdditionalData thing?

**Comment by loumalouomega** [comment]
If you use my mortar classes and the dual LM as I do in my mortar mapper you don't need to solve any system of equations

**Comment by philbucher** [comment]
I would like to do both, going full mortar and then also comparing to the dual version

**Comment by RiccardoRossi** [comment]
Hi guys,

the SystemSolverWithPhysics is needed for the ML or for the solvers that need to exploit the block structure of the problem. It does nothing more than a normal solver if this is not needed.

I would definitely switch to having the same interface for the Trilinos version and for the "Serial" version

**Comment by philbucher** [comment]
Also the normal B&S calls [SystemSolveWithPhysics](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L446) within `BuildAndSolve`, so I think this would definitely be a candidate to be added to the baseclass

**Comment by pooyan-dadvand** [comment]
It would be better to pass the ModelPart to constructor (if is possible) and avoid duplication of methods which only one should work. In general we should avoid the situations when caller should know (depending to the type of the object) which method to call.

**Comment by philbucher** [comment]
@pooyan-dadvand you mean the modelpart should be passed to the linear solver (i.e. for the ML) if it needs it and then we always only call `Solve` on the linear solver?

**Comment by pooyan-dadvand** [comment]
Yep! I would prefer it like this.

**Comment by RiccardoRossi** [comment]
No, it does not do. You need to pass the doflist and you don't know that at constructor time

**Comment by RiccardoRossi** [comment]
expanding on my comment, the point is that MultiGrid and deflation solvers require (optionally) the coordinates of the node to which a given dof is associated. This is needed to construct the "null space" of the problem.

this means that on one side you need to pass the list of dofs (which tells for each row of the linear problem to be solved which variable it corresponds to) and on the other side you need optionally to recover the coordinates that correspond to that dof.
Recovering the node a dof belongs to requires knowing the modelpart.

Note on the other hand that the list of dofs is also used for a variety of other reasons, for example for detecting which lines correspond to the pressure block in the AMGCL_NS_Solver or simply to detect the block size (Pastix, AMGCL, BlockDeflation)

**Comment by RiccardoRossi** [comment]
One more comment: passing the modelpart in the constructor would break the factory mechanism to construct the linear solver

**Comment by pooyan-dadvand** [comment]
I see that you need the list of Dof but for me this fits to be a BuilderAndSolver than a linear solver. (For this reason you have called it builder and solver to be able to do such combinations). Again, I'm not in favor of having two alternative methods.

**Comment by RiccardoRossi** [comment]
I think we are discussing two different things.

There is 1 Solve method for the linear solver, of the type Solve(A,x,b)

however the linear solver, since many years has a method ProvideAdditionalData which is implemented only by the solvers that actually need it. (the one in the base class does nothing)

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/linear_solvers/linear_solver.h#L237

Examples of solvers that need this are DeflationSolver, AMGCLSolver, AMGCL_NS_Solver, MLSolver, PastixSolver, MixedUPSolver.

the base class linear_solver also provides a method to ask if such additional data is needed

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/linear_solvers/linear_solver.h#L226

the builder and solver (openmp version) does the following

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L392

on the contrary (and here is the discussion) the trilinos version provides and uses a "SystemSolve" function which does not do the same (the block version is correct)

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_strategies/builder_and_solvers/trilinos_elimination_builder_and_solver.h#L367

the fix is simply to take out the call to method SystemSolve here

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_strategies/builder_and_solvers/trilinos_elimination_builder_and_solver.h#L444

and substitute it by what is implemented in all of the other builder_and_solvers.

I do agree that at this point we can take away directly the SystemSolve method from the API. Anyway the interface is the same as that of the linear solver so that one could get the linear solver and then use its api to obtain the same.

Note that doing this in the builder and solver **is not an option** otherwise we would have a different builder and solver for each linear solver option. This is exactly the reason for which the feature to provide additional data was provided

**Comment by RiccardoRossi** [comment]
@philbucher did we have progress on this? shall we close it?

**Comment by philbucher** [comment]
Unfortunately no conclusion has been reched yet, I will look into it again
