### ISSUE TITLE
error C2899: typename cannot be used outside a template declaration

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1528]
![image](https://user-images.githubusercontent.com/25903585/36316138-cba52b14-1339-11e8-8c05-c088abb323d1.png)

Compilation of master with Visual Studio currently fails due to the following error.

Removing all the ```typename``` from the lines in the error message solves the compilation problem.

@loumalouomega As i saw that you created those files, could you try if under linux it is the same, and if the functions still work as expected?
Thanks in advance!

**Comment by loumalouomega** [comment]
In Linux it works, my fault, as Appveyor consumes all the compilation time
I didn't know.

El 16 feb. 2018 4:57 p. m., "armingeiser" <notifications@github.com>
escribió:

[image: image]
<https://user-images.githubusercontent.com/25903585/36316138-cba52b14-1339-11e8-8c05-c088abb323d1.png>

Compilation of master with Visual Studio currently fails due to the
following error.

Removing all the typename from the lines in the error message solves the
compilation problem.

@loumalouomega <https://github.com/loumalouomega> Could you try if under
linux it is the same, and if the functions still work as expected?
Thanks in advance!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KratosMultiphysics/Kratos/issues/1528>, or mute the
thread

**Comment by loumalouomega** [comment]
Can you change it?, I will approve it ASAP

El 16 feb. 2018 6:12 p. m., =?ISO-8859-1?Q?Vicente_Mataix_Ferr=E1ndiz?= <
vicente.mataix@polytechnique.edu> escribió:

In Linux it works, my fault, as Appveyor consumes all the compilation time
I didn't know.

El 16 feb. 2018 4:57 p. m., "armingeiser" <notifications@github.com>
escribió:

[image: image]
<https://user-images.githubusercontent.com/25903585/36316138-cba52b14-1339-11e8-8c05-c088abb323d1.png>

Compilation of master with Visual Studio currently fails due to the
following error.

Removing all the typename from the lines in the error message solves the
compilation problem.

@loumalouomega <https://github.com/loumalouomega> Could you try if under
linux it is the same, and if the functions still work as expected?
Thanks in advance!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KratosMultiphysics/Kratos/issues/1528>, or mute the
thread
