### ISSUE TITLE
Convergence Criterion for Formfinding

### ISSUE THREAD

**Issue by annasophie91** [KratosMultiphysics/Kratos#1549]
Do you think it is a good idea to implement a formfinding  convergence criterion as @loumalouomega suggested? I observed some examples in carat where the formfinding does not converge, especially if lambda_max is (close to) 1 (see for example attached files). 

Is there a reason why there is a certain number of steps in carat which I am not aware of the moment?
And if we decide to implement a convergence criterion, would it be sufficient to use the existing displacement criterion or does someone have a better idea?

[membrane_no_cable_orthotropic.zip](https://github.com/KratosMultiphysics/Kratos/files/1744598/membrane_no_cable_orthotropic.zip)

**Comment by RiccardoRossi** [comment]
Hi @annasophie91 your issue lacks of introduction for who was not in the online meeting :-).

On my side I am in favour of implementing a convergence criteria for form finding. also i think you should employ some "acceleration" or at least underrelaxation technique to make the convergence more robust

**Comment by loumalouomega** [comment]
Replace Frau Blucher by convergence accelerator

https://www.youtube.com/watch?v=zdIID_TGwhM

**Comment by longchentum** [comment]
Hi @annasophie91, I would definitely try with the displacement criterion at first.
If lambda_max tend to 1, the constraint is simply too hard and depending on which initial design is given, the formfinding cannot converge. In such case, there might not exist converged solution. So I agree with @RiccardoRossi with some relaxation technique. For example, increase the lambda_max accordingly.
The reason why Carat has a certain number of steps is simply because, by setting a fixed number of steps, one already obtains the first very primitive abort criterium. This is a more or less experience based setting.

**Comment by philbucher** [comment]
I talked to @rolandwuechner and @longchentum , we would like to discuss this at the Skype Meeting tomorrow, does this work for you @annasophie91 @RiccardoRossi @loumalouomega ?

**Comment by loumalouomega** [comment]
For me OK

**Comment by annasophie91** [comment]
For me also OK, any time fits for me.

**Comment by philbucher** [comment]
@annasophie91 could you please post a brief conclusion of the skype meeting for future reference?

**Comment by RiccardoRossi** [comment]
ping @annasophie91 .

**Comment by RiccardoRossi** [comment]
closing as inactive
