### ISSUE TITLE
ExplicitStrategy defined both in the core and in the StructuralMechanicsApplication

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1597]
@KlausBSautter the title says it all. 

this is actually an error... can't u use the explicit strategy in the core? If not, you'll have to rename your strategy.

HOWEVER, by far the best option would be to reuse the one in the core ... so do not rename it lightly...

**Comment by philbucher** [comment]
what is the status of the one in the core, is it working?

I think the one in StructuralMechanics would need some refactoring before it could be moved to the core

**Comment by RiccardoRossi** [comment]
To be honest i don't know what is the status of the one in the core. 
It would be worth checking it out.

In any case we cannot have two "ExplicitStrategy" defined in the core and in an application, since they conflict

**Comment by KlausBSautter** [comment]
I understand that it would be nice to use the one from the core. However I just had a look and it is different to what I do. I would like to rename the mine even though it is not a good way to go. I would have to change the core strategy as I cant use it in its current state.

**Comment by KlausBSautter** [comment]
explicit_time_integration_strategy ?

**Comment by philbucher** [comment]
I suggest MechanicalExplicitStratrgy or ExplicitMechanicalStrategy since the link to StructuralMechanics is rather strong

**Comment by RiccardoRossi** [comment]
guys i just merged to the pybind11 branch and tested this (as usually, FullDebug)

i get this error

test_cr_beam_dynamic_explicit (test_patch_test_cr_beam.TestCrBeam2D2N) ... terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: attempting to do a GetValue for: MIDDLE_VELOCITY variable #659 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)

in kratos/containers/data_value_container.h:219:TDataType& DataValueContainer::GetValue(const Variable<TDataType>&) [with TDataType = array_1d<double, 3ul>]

Aborted (core dumped)

**Comment by KlausBSautter** [comment]
Do I need to register this somehwere else?

**Comment by RiccardoRossi** [comment]
no, this is telling that you are doing an access GetValue(MIDDLE_VELOCITY) from within a parallel region, without having previously set the MIDDLE_VELOCITY. This means that the memory for MIDDLE_VELOCITY is being allocated when you access, which is potentially not threadsafe

**Comment by KlausBSautter** [comment]
ok and this only happens for the 2d beam?

**Comment by philbucher** [comment]
no, the error is in the explicit_scheme, I will explain in more detail in a few minutes

**Comment by philbucher** [comment]
@KlausBSautter the error is in one of the following lines:
[here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_strategies/custom_schemes/explicit_central_differences_scheme.hpp#L267) or [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_strategies/custom_schemes/explicit_central_differences_scheme.hpp#L454)

The problem is that in one of the cases you access the MIDDLE_VELOCITY for the first time. This internally allocates the memory. The problem is that you cannot allocate the memory if you are running openmp (this is what the error message says).

A solution would be to loop the nodes and set the MIDDLE_VELOCITY manually to zero (no openmp!)
This way the memory gets allocated before entering the parallel region
This should be done before the first access to MIDDLE_VELOCITY, but I am not sure which of the functions (`InitializeExplicitScheme` or `SchemeCustomInitialization`) is being called first (names are not really descriptive, you might want to change that too)

I am not sure if this is the best solution. Maybe @RiccardoRossi has a better idea

**Comment by philbucher** [comment]
Btw @RiccardoRossi your branch does not compile on my machine:
~~~
In file included from /home/philipp/software/Kratos_aux/kratos/utilities/math_utils.h:26:0,
                 from /home/philipp/software/Kratos_aux/kratos/includes/mortar_classes.h:21,
                 from /home/philipp/software/Kratos_aux/kratos/utilities/exact_mortar_segmentation_utility.h:24,
                 from /home/philipp/software/Kratos_aux/kratos/utilities/exact_mortar_segmentation_utility.cpp:19:
/home/philipp/software/Kratos_aux/kratos/includes/ublas_interface.h:34:42: fatal error: boost/numeric/ublas/vector.hpp: No such file or directory
 #include <boost/numeric/ublas/vector.hpp>
~~~

**Comment by KlausBSautter** [comment]
@philbucher why is that only happening  for Middle_Velocity ? Maybe we can discuss this tmr at the chair

**Comment by RiccardoRossi** [comment]
@KlausBSautter the SetValue is ok, in the sense that it will not throw if you call it from a parallel loop.
so if you need to set it to zero in parallel call SetValue

@philbucher i think the problem is that YOU STILL NEED ublas. I am only removing boost.python in this branch
