### ISSUE TITLE
Calculation of reaction in FluidDynamicsApplication

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#1630]
Hello all 

Usually the reactions for a given problem are calculated in the CalculateReactions function of the Builder and Solver. This function is called in the `SolveSolutionStep`  of the `residualbased_newton_raphson_strategy` . 

Then we (me and @navaneethkn ) observed something in the code of `residualbase_predictorcorrector_velocity_bossak_scheme_turbulent.h`  
used for FluidDynamics. 
The reactions are calculated and update over all of the domain in the `FinalizeSolutionStep` of this scheme. 

Does this mean the reactions are doubled always ? 

Also the function  `FinalizeSolutionStep`  of this scheme does calculate the whole system again (which can be expensive). Can `Calculate_RHS_Contribution` used here (that is if it is necessary to update reactions here) ??

**Comment by RiccardoRossi** [comment]
The reactions are calculated in the FinalizeSolutionStep as the current implementation of reactions doesn't correctly show the reactions for exactly the reason you point out.

It should be superseded by your fix. @jcotela do you agree?

**Comment by jcotela** [comment]
I would prefer to calculate the reactions using the builder and solver when possible, but I seem to remember there was some problem with that... I think it was due to slip conditions, where you would not get the reactions because the DOF is not actually fixed? @RiccardoRossi do you recall this? If it can be done now, I'd just remove the duplicate calculation on FinalizeSolutionStep.

@adityaghantasala The problem with calculating only the RHS is that, the way the fluid element is implemented, it will just calculate the LHS internally and discard it, so the cost is the same (maybe even more since the matrix is allocated and de-allocated at each call).

**Comment by RiccardoRossi** [comment]
@jcotela  , yes i recall this. 
Exactly what i am telling is that as soon as we replace slip conditions by MPCs, which i hope we can do sooner than later, we can get rid of the reactions computation in the FinalizeSolutionStep (which is a chapuza solution).
In short...i agree with you

about the RHS calculation, it depends. For the Symbolic element it should not be the case...as a minimum it is not specifically needed. In any case this is a limitation of the FluidDynamicsApplication, i still believe that the solution of doing everything in the BuilderAndSolver is cleaner

**Comment by jcotela** [comment]
I'm not sure the MPC will change this, I think the problem is that the Builder And Solver only sets the reaction for fixed DOFS. Unless MPC requires fixing both "sides" of the constraint, we will continue not having reactions everywhere. Probably we need to think of writing reactions for all DOFs in the builder and solver (not only the fixed ones) but that would be a change beyond the FluidDynamics.

**Comment by RiccardoRossi** [comment]
@jcotela , yes computing the reactions everywhere is what @adityaghantasala was proposing. I do think this is a good idea...

**Comment by adityaghantasala** [comment]
@jcotela  no MPC will not require that both sides are constrained. Then there will not be any reactions set (but they are computed) on those nodes.

@RiccardoRossi  I am not sure when I suggested we compute reactions everywhere. But regardless of that, I think even in the normal builder and solver, the reactions are already computed everywhere but only set (for visualization) on the Fixed Dofs. We can see this here 

        TSparseSpace::SetToZero(b);

        //refresh RHS to have the correct reactions
        BuildRHSNoDirichlet(pScheme, r_model_part, b);

```
		const int ndofs = static_cast<int>(BaseType::mDofSet.size());

		//NOTE: dofs are assumed to be numbered consecutively in the BlockBuilderAndSolver
		#pragma omp parallel for firstprivate(ndofs)
		for (int k = 0; k<ndofs; k++)
		{
			typename DofsArrayType::iterator dof_iterator = BaseType::mDofSet.begin() + k;

			if (dof_iterator->IsFixed())
			{
				const int i = (dof_iterator)->EquationId();
				(dof_iterator)->GetSolutionStepReactionValue() = -b[i];
			}
		}
```
the RHS -> b is computed already over all the domain / dofs in the line  `BuildRHSNoDirichlet(pScheme, r_model_part, b);`

**Comment by jcotela** [comment]
OK it seems we all agree that having the builder and solver compute the reactions everywhere would be a good idea. Shall we do it only for the block one for now, or should all builder and solvers work like this?

**Comment by RiccardoRossi** [comment]
My call is that we should have all to behave like this.

**Comment by adityaghantasala** [comment]
All builder and solvers should have it like this I think. Then its more uniform.

**Comment by adityaghantasala** [comment]
Clarified with #1666  #1657 #1648
