### ISSUE TITLE
compute colors

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#1690]
Hello @loumalouomega ,

I am interested to create an utility to refine a mesh with non conforming subelements.
In the refinement process I will need to compute the sub model parts colors. To avoid code duplication, I could move the ComputeColors from mmg_process to a new class.
Which would be the best place to add the new utility? maybe kratos/utilities?

**Comment by loumalouomega** [comment]
Hi,

I suggested that some time ago, but due to time constraints and other
priorities I left the idea behind. I would be pleased to help in migrate
the colour computation to an independent utility, in such a way that could
be used for anyone.

Could be very interesting, not just for remeshing, but to generate lighter
output input files, due to the reduction of redundant information.

 For example in the case of creating a mdpa with submodelparts, instead of
specify all the elements belonging to a submodelpart, a list of colours can
be defined and just specify which colour belongs each component. This could
help in reduce significantly the size of the mdpa/hdf5 files, of course
would increase the complexity in the creation of files...

Best regards, tell me how can I help

**Comment by miguelmaso** [comment]
Hi,

I have added the utility (https://github.com/KratosMultiphysics/Kratos/compare/feature-computing-colors#diff-c348918a620a78290064cf573403a804) in the branch feature-computing-colors

The utility is exactly the same function as ComputeColors in mmg_process (with minor changes)

Now, before removing the function from mmg_process, I need to test the new utility.

**Comment by miguelmaso** [comment]
#1696 
#1692
