### ISSUE TITLE
Tables in submodel parts

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#173]
@KratosMultiphysics/technical-committ we need to decide what is the expected behaviour for tables being stored in submodel parts.

essentially i believe that there are two options
A - a table contained in a submodel part should also be contained in the parent model_part, that is, if we store a table TIME vs DISPLACEMENT it should be always the same in all the submodeleparts
B - a different (say) TIME vs DISPLACEMENT table can be stored in all the different submodelparts

i would personally go for option A, which is less flexible but easier to understand. B of course is more powerful...

**Comment by pooyan-dadvand** [comment]
I would go for option B if we got a clear use case for that. on the other hand I agree with @RiccardoRossi that the option A is easier to handle.

I don't have a clear use case now, but a less significant example would be  different inlets with different input velocity tables. I know that at this moment we are storing them in the model_part and passing them by id to the process. I think storing the corresponding table in each sup part would be a cleaner solution

**Comment by maceligueta** [comment]
I would vote for the versatility of B.

**Comment by josep-m-carbonell** [comment]
Now tables are stored in modelparts, but in fact they are used to impose and assign values to variables. Why the processes that use that tables does not own them?

**Comment by RiccardoRossi** [comment]
I agree with JM. For the use within a procesos the table should be stored in the process itself

**Comment by ipouplana** [comment]
But, what if we have a very large table... 
We first would store the table in a .json, and then we should add that table to the ModelPart through a process which, unless we have a very efficient method to add tables to the ModelPart from a .json, can be slow. On the other hand, if we have the table already defined in the .mdpa, we can use it right away in our ModelPart.
I mean, a part from the fact of having the tables "more clearly stored", what do we gain by defining them outside the .mpda?

**Comment by ipouplana** [comment]
By the way, regarding the definition of Properties outside of the .mdpa, I was wondering the same as for tables...

**Comment by josep-m-carbonell** [comment]
@ipouplana  I like the considerations exposed.

It rises the next qüestions:

1) Must the tables defined in the mdpa or supplied in different files?

If they are very large maybe it will be better to read them directly from an specific file instead of having a large mdpa. But then we will have several files to be considered in the input.

2) Does we have a method to read tables from a json, or from another file format ?. It will be less efficient to read something from a different file ?

3) Modify the code to have a more logical structure (in terms of ownership of each item) can be considered as a gain ?

@KratosMultiphysics/technical-committee

**Comment by RiccardoRossi** [comment]
@ipouplana 
     this is just to say that you could read using json the data of very large tables and just store it in a table object. That object could be perfectly stored within the process that makes use of it.

@josep-m-carbonell json is a confortable format to read from since the reading is done automatically. It can also be written in binary form using bson or msgpack. I would not go for another format and even less for a custom reading process without seeing a clear advantage in it.

**Comment by maceligueta** [comment]
Riccardo, can you provide more details on how to manage big tables in json? I did not fully understand what you just wrote.

**Comment by ipouplana** [comment]
I thought the same as Miguel Angel ^_^'

**Comment by RiccardoRossi** [comment]
@maceligueta @ipouplana i am simply saying that the reading of a table from json can be done very efficiently, i guess as efficiently as the code we can do "by hand" for reading it from a .mdpa file.
Even more so considering that employing json format we could have easy access to binary formatting of the files.

in shory my point is that json performance should not be a blocker issue in this discussion.

On the other hand thing of a problem in which you have 3 different inlets with 2 different time intervals.
if you want to prescribe TIME vs PRESSURE separately on each inlet, you could make one table per each submodelpart. However what would u do if you need a different table for each interval?

an easy solution is to read and store the table directly in the process definition, so that each process owns the data it needs.

**Comment by maceligueta** [comment]
Understood, @RiccardoRossi , but the json file can get really big, then (difficult to read visually).

**Comment by ipouplana** [comment]
@RiccardoRossi  I know it is possible to read tables from .json. My question is, what are the advantages of doing so?

I don't understand the case you mention of defining a table for each interval... Isn't it enough to define one table for all the computation. I mean, in the end a table allows defining piecewise linear functions and thus I guess there is no need to define different intervals since the table already includes that... 

In any case, you could always define a process with various fields where you can define the different tables' id of the .mdpa that the inlet uses, right?

**Comment by loumalouomega** [comment]
The structure of a json is very similar to a python dictionary, in principle is relatively easy to write a table as a simple dictionary, in any case I haven't use the json as a table input.

**Comment by loumalouomega** [comment]
The only remaining is to create a process for that pourpose

**Comment by RiccardoRossi** [comment]
@maceligueta @ipouplana i am not sure i understand your concern.
My understanding at first was that you were worried about the reading performance. I see this is not the case.
Your point is that the ProjectParameters.json may become too long and hard to read?
If this is so, i think it would be easy to have as option to either put the table "inline" within the file or to tell to go to read it from a (strictly optional) file, which might even be an hdf5 table if we like.

Also a lot of editors allow to do folding of json files, helping a lot with the readability. Just take a look to this one for curiosity:
[Online Json Editor](http://www.jsoneditoronline.org/)
note that i definitely do not want to enforce this choice, i just say it is an interesting option.

on the other hand i think it would definitely be useful to have the possibility of assigning a different table to two processes acting on the same portion of the domain within different intervals.
Note that this is just one use case...we could easily think of more of them.
Since the only object in charge of using this data would be the object to apply it, then i think it would be the logical owner for such data.

**Comment by pooyan-dadvand** [comment]
I agree with @ipouplana about their concern with adding more data to the parameters.

In my opinion we should try to keep the "data" in datafile and "parameters" in parameter file. I know that the borderline between these things is not well defined but in general if I can put something in data file I would put it there and try to reduce the size of parameters as @ipouplana  and @maceligueta proposing.

**Comment by josep-m-carbonell** [comment]
@pooyan-dadvand  Do you mean that, in you opinion,  Properties and tables of properties would be better to be kept in the data file (.mdpa), for example ? 
Right now,  if you need to use a table from a process (and that table is stored in the modelpart), the way to ask for it is via id. Is there any other way?

what about the answer to that questions too:

1) Must the tables defined in the mdpa or supplied in different files?  -->still not clear 

2) Does we have a method to read tables from a json, or from another file format ?. It will be less efficient to read something from a different file ?   --> @RiccardoRossi said that can be read and there is no efficiency problems.

3) Modify the code to have a more logical structure (in terms of ownership of each item) can be considered as a gain ?

**Comment by ipouplana** [comment]
I think that before accepting a series of changes that may imply quite a lot of work for the Kratos developers in terms of adapting the code and input format, we should address and discuss some questions like the ones @josep-m-carbonell mentioned...

**Comment by RiccardoRossi** [comment]
i would add a point 4 to @josep-m-carbonell 's points

4 - what to do if multiple tables involving the same data are to be considered?

**Comment by josep-m-carbonell** [comment]
Giving my opinion to the qüestions:

1) It would be nice to be able to read a table from a supplied txt, csv file directly

2) It would be nice too, to be able to supply tables directly to the processes that will use them, including them in the json file directly, a reference to the mdpa table label, or reading them from a file supplied.

3) I think so, a better structure of the code and the ownership of the objects must be considered always as a subtanciable improvement. (the collateral effects in the number of changes that must be done to keep everything working can be considered as the price to be paid, sometimes expensive, sometimes cheap). If something is better, is better. "We must try to avoid the consideration that something is worse because it is expensive...because it can block important improvements"

4) ModelParts have an array of tables, they are supplied with a unique label, Table 1, Table 2, Table 3, they don't matter if the same data is considered into them. 

@KratosMultiphysics/technical-committee @ipouplana

**Comment by maceligueta** [comment]
I like the versatility of putting a switch in the json -> Is this table in a mdpa? Or in a txt file? or inside the json itself? And after the switch the table is explicitly referenced or typed. 
@josep-m-carbonell : what would you do with the txt file? You can read it and save it in the process, or you can save it in the json at the beginning, or you can just read it every time you need it (I would avoid the last one).

@KratosMultiphysics : please expose the arguments against putting a switch for referencing tables. This switch would inform if the table is in a file, in a mdpa or in the json itself.

**Comment by josep-m-carbonell** [comment]
I agree with your comments @maceligueta.

**Comment by ipouplana** [comment]
I agree with @maceligueta's idea of using a flag to determine whether the table is defined inside the .json, inside the .mdpa or even in another kind of file, e.g. .csv.

And regarding @josep-m-carbonell's third point, I believe that changes that introduce improvements to the code should be implemented regardless of the working cost, but I also think that those changes must show actual improvements, i.e. everybody implementing them should clearly see its benefits.

**Comment by pooyan-dadvand** [comment]
@josep-m-carbonell I had missed your comment mentioning me with the questions. I saw it now.

1. I always like to have less files in order to have less disperse information and I would put what I can in mdpa and avoid an additional material file as we have. Saying that I agree with you that reading csv files would be a nice feature and it would be a reason for having a CsvIO class.

2. I don't see any performance issue regarding different formats or at least I think here in reading the performance is not our major issue. (It is important in large files in large clusters but not for tables)

3. You are right with ownership. However here you pass the sub model part and keep a link to that in the process. So it is also ok if table also come inside the sub model part. Technically the difference is very subtle. What I cannot evaluate is which would be more complex to work with in practice. (I mean to see why table is wrong or is not what we think)

4. I should change the modelpart tables to work like properties with two variables. But at this moment they are by id as @josep-m-carbonell mentioned. The important detail here is the fact that with the current implementation it would copy the table (instead of having a smart pointer to once allocated one)

**Comment by pooyan-dadvand** [comment]
I agree with @maceligueta about flag in json for choosing the table source

**Comment by RiccardoRossi** [comment]
Has anyone made progress on this?

**Comment by pooyan-dadvand** [comment]
Not from my side. Even I'm not sure if everybody agrees here.

**Comment by RiccardoRossi** [comment]
DECISION (from @KratosMultiphysics/technical-committee )

Tables assigned to properties, belong to the property they are assigned to, which is common in all a model part hierarchy.

If the table is assigned directly to a submodelpart, then it is private to that submodelpart (not known to the father nor to the sons).

For the input, the table can be written in the mdpa.
If something is written from a json, for example in reading the material properties for the structural application, then the reading process will be allowed to overwrite the value read from the mdpa.
