### ISSUE TITLE
Reusing the same time schemes for multiple problems

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#1835]
We were discussing earlier today about the difficulties in reusing a time scheme for different problems. In many time schemes, the update of nodal variables ends up looking roughly like this:
```
for (dof in dofs): dof += Dx(dof.EquationId());

for (node in nodes): UpdateDerivatives(node);
```
where we first update the problem variables, stored in the problem's DofSet (say, the displacements), and then, in the second loop, we use the time scheme update formulas to compute the new velocities and acceleration.

Now, the first loop is very general, since we can just rely on the elements to build the list of dofs, and we don't really care which variables are we working with. Conversely, the second loop ends up using hard-coded accesses to the node's database: we read the node's `DISPLACEMENT` to calculate its `VELOCITY`.

Now we may want to use the same time scheme with a different element type (think using shells instead of solid elements) and it turns out that our nodal variables change: now in addition to calculating the `VELOCITY` from `DISPLACEMENT` we also want to use the same update formula to compute `ANGULAR_VELOCITY` from `ROTATION`.

The three of us were not able to find a clean solution to write the second loop also in a generic way. This means we would need to write a new scheme (or at least derive it) to update the "additional" set of variables. @loumalouomega has managed to write a generic time scheme using json Parameters to define which nodal variables are unknowns and which are derivatives [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/schemes/residual_based_bdf_custom_scheme.h) but we feel that this is not a robust way to do this (it is easy to do it wrong if the variables are passed in the wrong order).

We thought of a couple possible ways to achieve this, but they have their drawbacks:

- Asking the elements/conditions for their derivatives, just as it is done for the Dofs: this would require enhancing the element interface and doing something similar to `BuilderAndSolver::SetUpDofSet`. We thought this would be the most generic way (just ask the elements) but that handling these lists would add a considerable cost. Also, we might not want to use Dof objects for this, since they are rather heavy, so I believe this would mean introducing a new class (a kind of 'lightweight DOF') storing these node-variable-derivative relations.

- Defining the derivatives as a property of the Dof or the Variable: @loumalouomega told us that this is common in other codes. Then we could just ask the existing DofSet to get a list of Dof derivatives (and second derivatives). This saves the cost of managing the extra dof lists, but makes the Dof object even heavier.

At this point, we thought we could turn to the community for ideas. All suggestions are welcome.

**Comment by loumalouomega** [comment]
I was thinking in the way to do it the most modular possible for future uses. The good think is that now the key is computed dynamically and basically just depends of the name (assuming that the time derivative is the same type as the base variable), so we could use the name of the variable in the constructor in order to store the key (because we know that the resulting is unique)

So my idea to extend this and make more modular is to define a member map (or any other structure doing some tricks, maps are heavy https://lemire.me/blog/2016/09/15/the-memory-usage-of-stl-containers-can-be-surprising/). This map could be defined with a enum key, which will be used to identify what is (TIME_DERIVATIVE, SPATIAL_DERIVATIVE, etc...) and  the value will be the key of the corresponding variable. 

This should be defined on compilation time to pass it on the constructor. Then it will only remain to define methods in order to access this variables

**Comment by philbucher** [comment]
@jcotela thanks for summing this up nicely. Considering #1833 and this, we will have some very general time integration schemes, working with and without mpi :+1: 

I tend to like the first method you proposed. I would add that this `AuxDofSet` could be a member of the `Scheme` and not of the B&S (since not all schemes need it, e.g. the Static one)
the scheme would ask the elements/conditions in the initialization for its "Additional" variables and does the same as what the B&S does with the dofset, constructing the `AuxDofSet`.
this list could be cleared when `Clear` of the scheme is called, again equivalent to what the B&S does.
Updating the adiitional Variables with the `AuxDofSet`would then be quite straight forward

@loumalouomega How would your solution look like for e.g. Fluids? For Structural the `VELOCITY` would be one of the additional Variables, whereas in Fluids it is the main dof.

**Comment by loumalouomega** [comment]
Well that's something I need to think, because for fluids you work in VELOCITY and even if you define additionally to TIME_DERIVATIVE the TIME_INTEGRAL variable you will have problems of cross definitions

**Comment by philbucher** [comment]
lets see what the @KratosMultiphysics/technical-committee has to say once they have time again after pybind is merged :)

**Comment by jcotela** [comment]
Regarding fluids, there is the additional problem that we rarely consider the time derivatives of pressure, so we have 4 dofs per node (3 velocities and 1 pressure) but only 3 additional variables (accelerations) or 6 if you also compute displacements. We could solve this by adding some kind of `Has(TIME_DERIVATIVE)` method to ask for derivatives, but that would fill our code with ifs...

**Comment by pooyan-dadvand** [comment]
Thank @jcotela for the description of problem. Technically speaking I see two different ways to do this:
- Add the time derivatives to the VariablesList and add methods to Dof to consult it without storing the variable reference. This option allows flexibilities like defining the time derivatives for a modelpart but is more complex to implement and maintain/debug.
- Add time derivatives to the variable. I have discussed this option with @loumalouomega and as he mentioned now we have better and simpler ways to implement this. Nevertheless this option would be less flexible and there are some corner cases like what happens if there are two PRESSURE variables with different time derivatives. Eventually I can detect such problems in registration and send an error or consider them as different variables giving different keys but we should define the desire behavior. 

I don't still have strong preference on either options and I would like to here your opinions on it.

**Comment by jcotela** [comment]
@pooyan-dadvand from your solutions, I'd prefer the second. The added flexibility of the first might actually make our lives difficult when we reuse the nodes on two different modelparts.

Regarding the same variable - different derivatives issue, I'd go for checking and throwing an error, for simplicity. Otherwise, we need to communicate to the users why their modelpart has two different PRESSURE variables, let users ask for the-PRESSURE-with-PRESSURE_DERIVATIVE-as-time-derivative variable and so on, which sounds like a nigthmare.

**Comment by RiccardoRossi** [comment]
triaged for now. We'll reopen in the future
