### ISSUE TITLE
Constitutive law base class (constitutive_law.h) improvements

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1838]
The debate is open to introduce improvements to the constitutive law base class. Also for deprecating old methods and solving name clashes. Please if you have any proposal that can contribute to it or you have detected errors or weak points on the constitutive law, feel free to expose it here.

**Comment by josep-m-carbonell** [comment]
1. Proposal of renaming constitutive law "Parameters"  by @philbucher , @josep-m-carbonell
2. Proposal  to deprecate some methods (must be specified which ones) @RiccardoRossi

**Comment by loumalouomega** [comment]
3. Fully implement cpp testting of all the CL base class methods
4. Define some methods by default in the base class. Like applying the PushForward and PullBack application when a StressComputation is not implemented

**Comment by jcotela** [comment]
5. If we are to use the constitutive laws for fluids too, it would be very convenient to be able to also pass the element data (the `element.SetValue/GetValue` container). An option would be to do as is done for the element's geometry, process info and property and use the `Parameters` object to pass it.

By the way, I fully support the addition of a velocity gradient strain mesure type as in #1837.

**Comment by pooyan-dadvand** [comment]
I would suggest `ConstitutiveLawParameters` for the 1 to avoid name clash.

I see the proposal of @jcotela, to have a constructor which accepts Kratos::Parameters as argument, very convenient (to create a reigstery based CL factory)

**Comment by jcotela** [comment]
@pooyan-dadvand sorry but I was not clear, I was referring to the "current" Parameters class (the one you are proposing to rename), which is passed when calculating the material response.

**Comment by RiccardoRossi** [comment]
Hi guys,

the possibility to pass "Kratos::Parameters" (not to be confused with ConstitutiveLaw::Parameters) in the constructor is something i am suggesting. 
The idea is that if we do this, we could pass the corresponding Parameters from the ReadMaterials.json, so to ease the construction of "strange" constitutive laws which require configuration. An example of this would be to configure for a given FlowRule, HardeningCriteria etc, etc )

**Comment by josep-m-carbonell** [comment]
In order to be able to create a general law based on rates (hypo- laws) in addition to the total deformation gradient other basic measures would be useful...like the derivative or the deformation gradient. Currently the storage of extra matrices are needed because the increment of F(deformation gradient) is not supplied to the ConstitutiveLaw and the previous F have to be stored.  If you don't want to add any extra variable to the parameters, a possible flexible change is to add a StrainMatrix (instead of StrainVector or they can live together), which can be no symmetric and several information can be supplied using the flags identification. To make it as general as possible the StressMatrix would be also needed.

**Comment by RiccardoRossi** [comment]
If all of this is not to pass DF = dx(n+1)/dx(n) than i guess it would be better to allow passing it.

However let's suppose that we have a function that requires both F(xn+1) and DF, and that we want that to work with a total lagrangian element. That would not work right? i mean, it would be up to the check to tell that they are incompatible...

**Comment by RiccardoRossi** [comment]
I have been thinking a little about this. Within the constituive law, we have the latest shape function derivatives as well as the geoemtry. This means that we can compute  the DF as we need from within the constitutive law without touching anything in the interface. Wouldn't that be an option?

**Comment by loumalouomega** [comment]
The CL does not know the geometry. The element knows and knows the shape function, but then we are in the starting point

**Comment by josep-m-carbonell** [comment]
CL knows the geometry, you can pass it as a term of the parameters, originally was like this because exist some magnitudes that only the constitutive law knows that are needed, and they must be computed from the geometry. For example, the "element size" in some damage laws.  It is clear that you can obtain everything from the geometry, but you don't want to do that. If you want to test a constitutive law, you will define a deformation or a strain and expect to obtain a stress. (you can define a displacement or velocity field that you know that gives that deformation, but it is a little bit tricky). In mixed formulations and multi-scale the things turn to more complex...
The issue here is that when you need another measure different form the F total ( dx_n+1/dx_0) there is no way to supply it. So a good option is to add another "DeformationMatrix", to pass this extra deformation measure. Then you can ask the law if any extra measure is needed, and pass it using the "DeformationMatrix". 
Adding this wildcard matrix is not going to enter in conflict with the current CLWs.

**Comment by RiccardoRossi** [comment]
@josep-m-carbonell i can see your point. 

I don't like however the concept of leaving a "dummy variable" in which one can pass anything.

I would propose passing DF so that   F(n+1) = DF * F(n)

with 
F(n+1) = Dx(n+1)/Dx(0)
DF = Dx(n+1)/Dx(n)

(of course we would NOT need to pass F(n). )

Would that do?

**Comment by josep-m-carbonell** [comment]
You must take into accout that in UMAT an array is used to supply everything you want to the law, this is a dummy. To have a new matrix container is not exactly a dummy, because it has to be a strain measure and the strain_measure flags will determine which measure are you passing. 
To add a  F =  dx_n+1/dx_n  is ok, in fact durings some years we managed to avoid this. However other measures are needed like  dotF = dv_n+1/dx_n, this is the one I was asking for right now...

**Comment by RiccardoRossi** [comment]
Hi @josep-m-carbonell the interface to UMAT is an internal detail of the CL. I would say it doesn't have anything to do with the CL API.

At this point however i am very lost. Let me see if i understand:

The interface now is passing F_(n+1):=D x_(n+1)/Dx_0. This is needed for All large-strains laws to be able to do pull-back/push-forward.
It was decided when the CL was designed that we would not provide DF, since one could store internally F_n and compute internally DF.
This is so, since doing it this way, one could use a hypoelastic CL together with a TL element (which only computed F, and not DF).  I am still defending this argument in order to insulate the element from the CL inner details.

As I understand, your proposal is to add dotF = dv_(n+1)/dx_n (maybe calling it another way)
My questions are:

1. what would happen with a Total Lagrangian (or updated lagrangian) element in statics?
2. what would be the case for a small_strain element?

**Comment by RiccardoRossi** [comment]
iterating on my previous comment,

i guess that we would need

1. strain_increment (voigt vector, useful mostly for small strains)
2. DF

which we could complete by a flag like INCREMENT_IN_RATE_FORM=True/False
telling if we are passing the dot version or the non-dot one. 

I am aware that this is what you were asking a lot of time ago...
sStill...i still see that this would make many CLs incompatible with static elements, so i don't really love the option

**Comment by josep-m-carbonell** [comment]
One possible option that we have discussed during the metting is to change the StrainVector and the StressVector to StrainMatrix and StressMatrix. It will allow more flexibility to pass and return different strain and stress measures. 
We must try to mantain the compatibility with the different element formulations TL, UL, so the total deformation gradient is mandatory. 
Another alternative is to make the constitutive law responsible of everything. From the geometry, the CLw can take the needed strain measure and return the required Stress. In this case, I think that the integration point must be passed to the constitutive law. (when things are not done in the correct place, options turn to more complex)
The pro and cons of this second option must be contrasted with the opinion of people working in non local constitutive modelling and mixed formulations too.

**Comment by RiccardoRossi** [comment]
Just to tell that changing
StressVector --> StressTensor ... for example PK1 is not symmtric, so this is needed
StrainVector --> StrainTensor ... for example grad_v is not symmetric, so voigt form is not possible

would be indeed a possible solution. the problem however is that the impact is pervasive, and the burden would be pretty high for "simple" constitutive laws, which are naturally defined in voigt notation.

I think it would be good that everyone in @KratosMultiphysics/structural-mechanics @KratosMultiphysics/fluid-dynamics comments on this


On a side note, my personal opinion is that we should adhere strictly to the guideline that elements are in charge of the kinematics. I think we should also write our CL in the assumption of cauchy model.
If one wants to go for non-local models, (say Cosserat) in my opinion much of the work should be done on the element side.


Finally i'd like to vocalize that this interface is getting too complicated for simple problems. 
I am starting to wonder if we shouldn't have designed an interface for "small strain" CLs and a different one (of course more complicated) for the case of "large strains".

**Comment by jcotela** [comment]
From the point of view of @KratosMultiphysics/fluid-dynamics, my feeling is that this is getting a bit too complicated for our needs. So far, the constitutive laws in the fluid dynamics application have been abusing the current interface to pass strain rates to methods that were designed for strains. We can adapt to whatever new way defined here but, as you say, the interface for the CL is already complicated enough and I think that trying to also fit in (Eulerian) fluids will only make it worse.

What I mean with this is that there are not that many laws that can be used both by solid elements and eulerian fluids, since the latter don't normally know or care about what the displacement/strain is. As a result, only a small subset of constitutive laws will be usable from the fluid dynamics application, which is currently 100% eulerian. I think that trying to find an interface fitting for both cases will just add new functions that will be unusable half of the time. If, as @RiccardoRossi suggests, the small strain and large strain CL should use different interfaces, maybe there should be a third one for strain rate based CL.

**Comment by PhilippeBussetta** [comment]
On my point of view the CLs and the elements have to be uncoupled as far as possible.
Maybe the non local behaviour can use CLs and update the result inside the element considering kinematic data.

About the Strain-Stress measure:
Maybe we can use a class -- with vector or tensor -- rather than enum structure.
class StressMeasure -> class StressMeasure_PK1 (with Tensor)
                               -> class StressMeasure_Cauchy (with vector)
with the function:
StressMeasure.setStressPK1()
StressMeasure.getStressPK1()
StressMeasure.getStressCauchy (), etc.

The structure is more complex that enum but more flexible.
The advantage:
- same structure
- we can add generic function (e.g. conversion between measure)
- we can add information regarding the CL
- the unused informations to simple CLs are avoided

**Comment by RiccardoRossi** [comment]
@PhilippeBussetta i fully agree about your comment of Nonlocal.

The problem with the StressMeasure, is how to know what is to be set, and where to read from.
For example what should a kinematic linear element set? what if we use it together with a large deformation CL?

**Comment by PhilippeBussetta** [comment]
@RiccardoRossi I think that it is the same problem that now, this slide does not fix this problem of compatibility. It is just to manage the difference of size of measure and maybe allows an more elegant way to transfer measure.
The compatibility could be fixed using template class, check function or let to the user.

**Comment by RiccardoRossi** [comment]
@PhilippeBussetta i see your point, and indeed it may be more clear what is being set. 
We could also have something like

      ConstitutiveLawParameters.StressMeasure( stress_tensor& stress , enum stress_measure ... )

what i don't love is however that we will need some ifs at the moment of using it, to decide what is to be given back. Not a killer, however so far we avoided such ifs by assuming that the Check verifies the compatibility (check is done once in all the analysis). Still i think that your idea has merits!!!

About the type of the stress_tensor (and strain tensor) i have a proposal articulated in "short term" and "longer term" :-)

== short term ==
Leave it as a dynamic vector. If one needs to pass a non-symmetric tensor, for example 3*3 it could be passed as s11 s12 s13 s21 s22 s23 s31 s32 s33 and copied internally to a matrix

== longer term ==
define always the tensor as "BoundedVector<double,3,3>" but then define a "reshape" expression that allows using only a portion of it (for example the first 3 or 6 components) as if it was a vector. this would be faster since no allocation would be needed (it is a stack array) and reshape would imply no copying so it would allow mantaining the efficiency

**Comment by RiccardoRossi** [comment]
@jcotela could u propose how the interface to pass the element data_value_container should look like? (i am personally in favor, but i think we may have an issue with cross including between the element and the constitutive law, so i guess we need to do that carefully.

**Comment by jcotela** [comment]
@RiccardoRossi regarding the interface, one way to avoid cross-includes would be to pass the data container directly using the existing `Element::GetData()`, which returns a reference to the data container. There is even a const version, which I think would be preferable (unless someone has a good reason to modify the data from the constitutive law). This could be passed at the same time as the other constitutive law parameters or, if desired, used to initialize a new pointer in the existing parameters.

**Comment by loumalouomega** [comment]
Maybe we should move this discussion to #3048 in order to reduce issues
