### ISSUE TITLE
Problem with gid_output_process

### ISSUE THREAD

**Issue by bodhinandach** [KratosMultiphysics/Kratos#2098]
I have a problem with the current gid_output_process.py in the core which print the "time" or "step" label as python double.

For the ParticleMechanicsApplication, I am planning to merge two output files in GiD but it is impossible since the printed labels are different in significant digits, e.g. `0.010000000000000002` in one output and 
`0.010000000000000009` in the other one.

Is there any way to have the label printed in float fashion so that the two output files can be combined smoothly?

Thanks

**Comment by loumalouomega** [comment]
The problem should be here:

https://github.com/KratosMultiphysics/Kratos/blob/86dc8a36beb24c6fbcfbdb785a55342c40a47fa6/kratos/python_scripts/gid_output_process.py#L568

**Comment by loumalouomega** [comment]
Well, in the following lines

**Comment by bodhinandach** [comment]
I have taken some time to look at the lines you mentioned but I think the label of the output is defined by the variable `time` as:
https://github.com/KratosMultiphysics/Kratos/blob/86dc8a36beb24c6fbcfbdb785a55342c40a47fa6/kratos/python_scripts/gid_output_process.py#L266-L269
The above functions will call the function in gid_io which will further call functions in `gidpost.c`. There, the format of the step is printed as `%.16g` as:
https://github.com/KratosMultiphysics/Kratos/blob/86dc8a36beb24c6fbcfbdb785a55342c40a47fa6/external_libraries/gidpost/source/gidpost.c#L1818-L1819
I changed it in my local branch to `%.12g` and it apparently works, I can merge my output smoothly.
What do you think about it @loumalouomega? If you confirm, I will make a PR.

**Comment by bodhinandach** [comment]
Or maybe @roigcarlo can help me to confirm this?

**Comment by loumalouomega** [comment]
The gidpost.c is something that belong to GiD, @jginternational can you inform your team about this bug?

I think we can change it anyway, @KratosMultiphysics/team-maintainers , as we discussed to update to the new gidpost.c we need to refactor anyway, so a small change will not harm

**Comment by bodhinandach** [comment]
I made a new PR of this change #2105. Could you please review this? @loumalouomega @jginternational @KratosMultiphysics/team-maintainers

**Comment by escolano** [comment]
As @loumalouomega has pointed you must not change any file of the 'gidpost' library.
Note: This is the webpage of the library:  www.gidhome.com/gid-plus/tools/476/gidpost
because your local change will be lost when upgrading to a new library version.

About your modification (write the time_step in ASCII format with %12g instead the current %16g) is not an acceptable change, the library is used by several programs and users, and they could have time steps with very very small increment, but that must be considered as different steps.
Truncating a few the printed value is only a solution of your particular case, not a good general solution.

I suggest as possible approaches:
a) use an integer id for 'step id' instead of a double value (don't directly use your 'calculation time step'), the value really will be casted for GiDPost to a double, but its representation is exact without any truncation.
The drawback is that your time step won't be represented in the result (although is encoded in some other place, like the result name). 

b) truncate in memory the double variable that store the 'time step' to be printed. e. g. force to 0 all binary digits after some 'arbitrary precision', and then print it, to have exactly the same representation of two numbers like 0.010000000000000002 and 0.010000000000000009
