### ISSUE TITLE
gitignore files generated  by visual studio

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#21]
Some files generated by Visual Studio during compilation should be added to gitignore:

![image](https://cloud.githubusercontent.com/assets/5918085/22973935/393e07c0-f380-11e6-8042-71a8083337e8.png)

@roigcarlo

**Comment by josep-m-carbonell** [comment]
Usually all directories and files generated by the build (for the different OS) are added to .gitignore

**Comment by roigcarlo** [comment]
I am fixing this in #22

I will add some packaging and scripts that where missing along with the files of the installation process.

That being said, I would like to point out a couple of things:

1 - Notice that the temp files created in the build are already mostly ignored (i.e. cmake_build/*). While is true that a couple of them were missing in the ignore list, the problem here are the ones that you, as a user, choose to install in the kratos source dir, which happens to be under version control.

For example, the KratosMultiphysics dir does not exist ( and never will ) in my computer.
I understand however that, as Kratos is designed it is useful to just have them all ignored to avoid problems. 

2 - In my opinion a best option would be if everyone that is installing in the source directory has this exclude list in HIS own ignore file ```.git/info/exclude```. This also covers a problem that @jcotela and others are having since they have alternate directories to build the project because they use different build directories for release / debug / etc...

**Comment by josep-m-carbonell** [comment]
Customize the .git/info/exclude file in the local computer is a good option.

**Comment by maceligueta** [comment]
I wrote how to do this in the wiki: http://kratos-wiki.cimne.upc.edu/index.php/How_to_make_Git_ignore_the_files_resulting_from_a_compilation_without_conflicts_in_.gitignore

**Comment by pooyan-dadvand** [comment]
Thanks!
