### ISSUE TITLE
"mesh_id" = 0

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#215]
Is Kratos going to work in meshes anymore?
Must **new** processes to include this field if it is in the limit of being obsolete?
....
@KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
I assume that now with the use of the submodelparts the meshes are not necessary anymore, but that these are conserved due to retro-compatibility reasons.

**Comment by josep-m-carbonell** [comment]
Please, do you talk from experience @loumalouomega ? If it is like this, can you enumerate the **new** processes that need retro-compatibility with the mesh_id?

**Comment by loumalouomega** [comment]
I just assumed, I haven't explained myself properly

**Comment by pooyan-dadvand** [comment]
@josep-m-carbonell It is a good question. In my opinion we should use submodel part instead of mesh when we can as @loumalouomega mentioned because they have more controled behaviour than mesh. However I'm not sure if we can remove the meshes completely. On the other hand I would like to reuse the meshes in a very different context of having fine grain coloring partitions (for openMp use) based on them if we can convert all the existing uses to ModelPart. But this idea is very fresh and even @RiccardoRossi is not aligned with it. 
Of course I am very open to your comments on this.

**Comment by josep-m-carbonell** [comment]
So maybe all processes assigning boundary conditions,and similar, must avoid to have the **mesh_id**. In fact the use of another mesh different form mesh 0 will be never used. Is there any application that needs this right now or plans to use this **mesh_id** in the future?

**Comment by RiccardoRossi** [comment]
my suggestions would be that as a first step the problemtype simply avoids writing the mesh_id=0 line.

this will allow silently removing the option at a later stage if we decide to do so.

**Comment by pooyan-dadvand** [comment]
I'm using it in some places but that uses can be easily changed to the sub model parts. But I thought that mesh generation in PFEM use it. @josep-m-carbonell am I right?

**Comment by josep-m-carbonell** [comment]
Hello Pooyan, PFEM is using submodelparts. It was changed one year ago. So, meshes are not needed anymore.

**Comment by pooyan-dadvand** [comment]
Perfect! 👍 

So the conclusion would be that we would avoid using the meshes and in future we will see if we remove them or reuse them for another purpose (like OpenMP partitions)

@KratosMultiphysics/technical-committee

**Comment by josep-m-carbonell** [comment]
For me it is OK. I agree with @pooyan-dadvand  and @RiccardoRossi.
