### ISSUE TITLE
FluidDynamics - definition of tau2?

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#2323]
@rubenzorrilla @jcotela @RiccardoRossi 
I think there is an error in the definition of tau2 in symbolic navier stokes element. (line 109)

`tau2 = mu + (stab_c2*vconv_gauss_norm*h)/stab_c1  `

If you check it, the units are not consistent. I think it should be as it is in the two_fluid_vms element, where the second term is multiplied by density. (line 1105)

`TauTwo = DynamicViscosity + 0.5 * Density * ElemSize * VelNorm;`

Maybe I'm missing something, but I think the latter is the correct one.
PD: I took a look in @jcotela thesis and same error is there (pag. 19), maybe that is where everything comes from..

**Comment by rubenzorrilla** [comment]
@ddiezrod thanks for reporting! I directly took it from that reference and if I'm not wrong, it was equal to other reference papers on the topic. In any case I will have a look to it ASAP.

**Comment by jcotela** [comment]
Just to confirm that the velocity*h term should be multiplied by the density to have the same units as mu. If it is not so on my thesis, it is a typo. Note that it is usually written without it in the references because their momentum equation is already divided by density (compared to ours).
________________________________

**Comment by rubenzorrilla** [comment]
Fixed in #2374. Thanks again @ddiezrod !
