### ISSUE TITLE
Application tests working on login node but not in cluster.

### ISSUE THREAD

**Issue by vineetmoraybfab** [KratosMultiphysics/Kratos#2370]
Hi, I am a newbie. I installed Kratos-5.3 using the steps provided in the wiki. The compilation is successful as I am able to run the tests successfully.
These tests:
from KratosMultiphysics import *
from KratosMultiphysics.mpi import *
from KratosMultiphysics.MetisApplication import *
from KratosMultiphysics.TrilinosApplication import *

And Kratos and Trilinos both are displayed.

This is true for the login node (the node on which i compiled the application)
But when i try to run the same tests on any of my compute nodes (cluster),
The Kratos logo is displayed but the application seems to be stuck at "from KratosMultiphysics.mpi import *" line.
Also when I run the "run_all_benchmarks.py" by providing "mpirun -np 224 runkratos run_all_benchmarks.py", all tests fail.

Please let me know if there is any solution to this.
Thanks

**Comment by jcotela** [comment]
Hi @BoNeLeS, in my experience such problems tend to be related to the way the cluster is configured, so I would recommend checking the cluster's documentation or contacting its admins.

Sometimes different libraries or modules are available on the login node and on compute nodes. You might need to load some specific modules to ensure that the same (versions of the) libraries you compiled against are available on the compute node. In some clusters, a solution is to compile directly on the compute nodes, if there is an appropriate queue/interactive session to do so. Again, there is no common standard for this, so the cluster's documentation and admins will be able to tell you what is the best procedure on your cluster.

**Comment by vineetmoraybfab** [comment]
Thanks for the quick reply, I talked with the system people. They said that the compute nodes only have minimal version of centos running on them with very few libraries. But they said that the required libraries are available on the system.
Also I won't be able to compile anything on the compute nodes.
So what I tried was...
1) I set up the environment required for Kratos-5.3 on the login node.
2) Ran mpi.py from <python_installation>/lib/python3.5/site-packages/KratosMultiphysics/
3) It printed out these things:
<host_name>.147749 PSM2_IDENTIFY PSM2 v2.1
<host_name>.147749 PSM2_IDENTIFY location /usr/lib64/libpsm2.so.2
<host_name>.147749 PSM2_IDENTIFY build date 2017-10-25 22:45:38+00:00
<host_name>.147749 PSM2_IDENTIFY src checksum 4a3b39b93920ff4b7cb95ec90a1ff6d6df07d111
<host_name>.147749 PSM2_IDENTIFY git checksum 61c8d25f4d7248c12cbdab63671a5bd237e81321
<host_name>.147749 PSM2_IDENTIFY built against driver interface v6.3
<host_name>.147749hfi_userinit: assign_context command failed: Interrupted system call
<host_name>.147749psmi_context_open: hfi_userinit: failed, trying again (1/3)
<host_name>.147749 PSM2_IDENTIFY run-time driver interface v6.3
This is from Intel Omnipath

But the same file fails to run from a compute node. Seems this is the only issue causing it.




Also, I tried to run the benchmarks on the login node.
Please help me if I am doing it the right way.

I am just going into the benchmarking directory and running:
mpirun -genvall -np 4 runkratos run_all_benchmarks.py 

And getting the following output:

[output.txt](https://github.com/KratosMultiphysics/Kratos/files/2148744/output.txt)

**Comment by vineetmoraybfab** [comment]
To be more specific there is an infinite time spent when I perform these lines in python:
python (python 3.5 interface)
>>> import mpipython
>>> mpipython.GetMPIInterface()

**Comment by jcotela** [comment]
I still would be inclined to think of some kind of library mismatch, since you get different results on the login and compute nodes. The acutual solution in that case would be system specific, so I won't be able to give you the right answers. However, the first thing I do when I have this kind of problem is to check library linkage with `ldd`. Navigate to the folder where you have installed the Kratos `.so` files and execute `ldd libKratosCore.so`. If I try that on my machine, I get
```
ldd libKratosCore.so 
	linux-vdso.so.1 (0x00007fffe8df2000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f2fc183c000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f2fc14b3000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f2fc111e000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f2fc0ef0000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f2fc0cd8000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f2fc0aba000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f2fc06fe000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f2fc2ddd000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f2fc04fa000)
```
Where you see which system libraries kratos tries to link to and where in the system it finds them.

I would recommend you to try that on both the login node and on the compute node (for example by launching a job with the `ldd` instruction) and compare the results. Ideally they should read the same. If it is trying to link to different files/versions, try to modify your LD_LIBRARY_PATH environment variable to include the routes to the "correct" versions of each file (the ones on the login node, which would be those you compiled against), so that they are found first.

Since you have problems with the mpipython module, I would recommnend doing the same with the mpipython `so` file. I would guess you will find some different versions for some of the files.

Note that sometimes a given file cannot be found, then `ldd` will report it as ` => ???`. If you encounter this, you also need to add the folder containing that library to the LD_LIBRARY_PATH environment variable.

I hope this helps with your troubleshooting.

**Comment by jcotela** [comment]
And I forgot to say: instead of/in addition to benchmarking, you may want to run the C test suite (which should be faster and more up to date, but I'm not sure it currently includes MPI tests). To do so, launch a script like this one:
```py
from KratosMultiphysics import *

Tester.SetVerbosity(Tester.Verbosity.TESTS_LIST)
#Tester.SetVerbosity(Tester.Verbosity.TESTS_OUTPUTS)
Tester.RunAllTestCases()
```

If you are interested in a specific application, I would suggest also importing it in the python script above, which will add its tests to the list of cases to be run.

**Comment by vineetmoraybfab** [comment]
Hi, thanks for the suggestions. The problem was related to SLURM scheduler. I was unable to run the benchmarks or any script when I submitted the job using SLURM. Alternatively, when the job was ran using direct ssh access to the nodes, everything was ok.
Thus, using intel MPI n slurm combination was causing the issue.

Thanks for related help.
Please close this issue.
