### ISSUE TITLE
Why element.h and condition.h EquationIdVector does not call GetDofList? 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2460]
This will reduce the code duplication significantly:

@KratosMultiphysics/technical-committee 

~~~ cpp
    virtual void EquationIdVector(EquationIdVectorType& rResult,
                                  ProcessInfo& rCurrentProcessInfo)
    {
        DofsVectorType dof_list;
        GetDofList(dof_list, rCurrentProcessInfo);
        
        const SizeType dof_size = dof_list.size();
        if (rResult.size() != dof_size)
            rResult.resize(dof_size);
        
        for (IndexType i = 0; i < dof_size; ++i) {
            rResult[i] = dof_list[i]->EquationId();
        }
    }
~~~

instead of 

~~~cpp
    virtual void EquationIdVector(EquationIdVectorType& rResult,
                                  ProcessInfo& rCurrentProcessInfo)
    {
        if (rResult.size() != 0)
            rResult.resize(0);
    }
~~~

and the redefinition in the elements and conditions will not be necessary anymore.

**Comment by pooyan-dadvand** [comment]
The only reason for which we haven't put this generic implementation in the base class was the overhead it has on performance. Nevertheless now I may consider it again.

**Comment by loumalouomega** [comment]
OK, thanks, I didn't know the influence was so significative

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee: This can be post-poned to after changing the  Node and Dof in the core. Eventually the builder and solver would be modified to only get the doflist.

So I will close it and reopen it in case of more comments

**Comment by pooyan-dadvand** [comment]
Just to add that it considered to be an interesting idea!

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee I thought about this in the scope of #5290 

I think since now the changes are done to `Node` & `Dof` we can take another attempt at this, since it can remove quite some duplicated code

I found some problems with this though:
- I basically had the same idea as @loumalouomega shows above, i.e. calling `GetDofList` inside of `EquationIdVector`. This would make everything super easy, very few code would have to be touched. 
**BUT**: we create a temporary `dof_list` inside of `EquationIdVector`, I am not sure how expensive this would be, since it is a temp we have a lot of memory allocation. And `EquationIdVector` is called all the time. 
Hence **IF** the compiler can figure this out that would be the least painful change
- Calling `GetDofList` instead of `EquationIdVector` requires quite some refactoring, also but not only because `Scheme` has many functions like this:
https://github.com/KratosMultiphysics/Kratos/blob/74669322b29763b9221f173a2f983e3982bd1606/kratos/solving_strategies/schemes/residual_based_implicit_time_scheme.h#L332-L349
=> The EquationIdVector is an argument to this function and `EquationIdVector` is directly called

**Comment by loumalouomega** [comment]
> 
> 
> @KratosMultiphysics/technical-committee I thought about this in the scope of #5290
> 
> I think since now the changes are done to `Node` & `Dof` we can take another attempt at this, since it can remove quite some duplicated code
> 
> I found some problems with this though:
> 
>     * I basically had the same idea as @loumalouomega shows above, i.e. calling `GetDofList` inside of `EquationIdVector`. This would make everything super easy, very few code would have to be touched.
>       **BUT**: we create a temporary `dof_list` inside of `EquationIdVector`, I am not sure how expensive this would be, since it is a temp we have a lot of memory allocation. And `EquationIdVector` is called all the time.
>       Hence **IF** the compiler can figure this out that would be the least painful change
> 
>     * Calling `GetDofList` instead of `EquationIdVector` requires quite some refactoring, also but not only because `Scheme` has many functions like this:
>       https://github.com/KratosMultiphysics/Kratos/blob/74669322b29763b9221f173a2f983e3982bd1606/kratos/solving_strategies/schemes/residual_based_implicit_time_scheme.h#L332-L349
>       
>       => The EquationIdVector is an argument to this function and `EquationIdVector` is directly called

OK

**Comment by pooyan-dadvand** [comment]
This temporal allocation was exactly our performance concern in the first design. Also, other options like having an accessor were considered to be too complex for the element layer and its intended developers.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee:
We will remove the `EquationIdVector` in the future, but we are not clear yet abt the implementational details
Hence I will not change `EquationIdVector` in #5290

**Comment by loumalouomega** [comment]
Do I close this?

**Comment by rubenzorrilla** [comment]
> Do I close this?

I think you can close it. We can reopen it if we change our minds about the future of the `EquationIdVector`.
