### ISSUE TITLE
Subtraction of Daming times Variable in the schemes of FluidDynamicsApplication

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#2509]
Dear colleagues,

I noticed that in the schemes of FluidDynamicsApplication, inside the function void AddDynamicsToRHS
(where one expects to execute the following operation:  bdyn = b - M*acc - D*vel), only the M*acc is subtracted, but D*vel is not. I also saw that you are doing the damping subtraction inside the element, instead. I believe that this may be somewhat confusing: why is one done inside the elem and the other inside the scheme? Also, the explanatory comment inside the scheme states: bdyn = b - M*acc - D*vel (maybe this was inherited from the older versions of Bossak schemes, where indeed both terms were subtracted). 

I suggest to put all the "management" of subtraction of Matrices * variable of the last iteration inside the scheme. 

Kind regards

**Comment by jcotela** [comment]
Hi Pavel,
I agree with you that the current situation is confusing, however this is a deliberate design decision (not by me, it was already like that when I started developing the FluidDynamicsApplication). The idea is that, in this way, you can support a non-Newtonian constitutive relation or other non-linear momentum sinks/sources (for example a non-linear porosity term). In such cases, you may want to use a tangent matrix as the velocity LHS (lets call it Dtang), so that you can no longer say that b_dyn = b - M * acc - Dtang * vel. The only part of Kratos that knows whether this is the case is the element, and that is why it was decided that the element, and not the scheme, should be responsible for defining the LHS and RHS contributions of the viscous term to the local system.

You don't want to do the same thing with the inertia term, because then you would need to strongly couple the time scheme integration with the element implementation. This leaves us with the current mixed approach, which is unsatisfactory due to the reasons you identified.

I agree that we should clean up the Bossak implementation, and it is in my to-do list (besides out-of-date comments it has quite a bit of old dead code and experimental features that haven't been used in a while) but we decided to focus on the Python solvers and elements first, which also have their maintenance problems. I am open to suggestions about what would be the best way to do so.

**Comment by playpaolo** [comment]
Hi Jordi! Thanks for the prompt reply. I think we should at least add a comment inside the scheme stating that this term should be added inside the element.

**Comment by loumalouomega** [comment]
I think I can not contribute more than @jcotela . Agree with @playpaolo to add the commentary

**Comment by philbucher** [comment]
Is this solved?

**Comment by philbucher** [comment]
Can we close this?

**Comment by jcotela** [comment]
Well, I still need to add the comment... Let me keep this open for a few more days as a reminder.
