### ISSUE TITLE
[StructurlMechanics] Truss CLaw saves stress

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2637]
this is a reminder issue

The linear elastic constitutive law of the truss currently saves the stress, which makes it difficult to use with the new adjoint-elements

This needs some refactoring

**Comment by KlausBSautter** [comment]
yep let's first make all the tests run again :cry:

**Comment by KlausBSautter** [comment]
this is really difficult in my opinion. The problem is that I cannot call element functions from the const. law. If the cl must return the current strain or stress I need to provide the respective counterpart. Thus I need to save one of them in as a class member. But we can discuss this when you're back

**Comment by philbucher** [comment]
It has to work somehow, see e.g. in the Shells and the Solids

But let’s take a closer look together ;)

**Comment by KlausBSautter** [comment]
@philbucher  I created a pr which should fix this problem :metal:
