### ISSUE TITLE
DEM questions

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#2667]
There are some parameters I can't understand and there is no comments.Can you give me the answer?
1.TOP and  BOTTOM (What are these standing for?)
2.BOUNDING_BOX (Is this mean that we set a box surrounding the DEM group?)
3.DEM_DRAG_CONSTANT_X or Y or Z
4.IS_GHOST(For this,I guess it much time,but I can't understand it)
5.RIGID_BODY_MOTION and FREE_BODY_MOTION(Are these standing for the constraint and unconstraint?)
6.SEVERITY_OF_WEAR and IMPACT_WEAR_SEVERITY and COMPUTE_WEAR
In addition,several days I asked that can the Kratos do create the tetrahedron or polyhedron particals?And can the Kratos simulate the partical breakage?

**Comment by fengzekang** [comment]
@farrufat-cimne @maceligueta

**Comment by maceligueta** [comment]
We are on vacations these days, so please be patient if it takes us some extra time to answer...
Actually, I am not in front of my computer, so I won't be able to answer all your questions, because I can't remember the exact meaning of all variables.
Concerning polyhedra, we are not capable of solving them at the moment, we do irregular shapes using the multi-sphere approach, which we call 'clusters'. There are some available clusters, but you can manufacture your own copying the structure of the .clu files.
Concerning the breakage of particles, we do it using smaller particles: you can make groups of little particles that behave like a big, solid, breakable particle. Those small particles we call them 'continuum particles',  and they follow the idea of 'bonded DEM'. 
You can follow the information and the tutorials from the general wiki page of the DEM application: http://kratos-wiki.cimne.upc.edu/index.php/DEM_Application

**Comment by fengzekang** [comment]
@maceligueta Thanks for your reply.And I am sorry to bother your vacation.I have checked the custom_elements folder.As you said,there are mainly sphere elements(varies from the size and other parameters).
Finally, wish you have a nice vocation.
Best regards.
fengzekang
