### ISSUE TITLE
[Core] Is serialization for WeakPointers going to be implemented?

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2725]
I do not know if there is any kind of impediment that makes its implementation very complex.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
It can be implemented relatively easy. Is it urgent?

**Comment by josep-m-carbonell** [comment]
Sure, now this is incomplete and we can not restart a case without changing the result.

**Comment by pooyan-dadvand** [comment]
OK, so I will put it in my priorities. Would you please add a test? (which of course would fail) Then it would be faster for me to implement it and I will do it sooner.

**Comment by philbucher** [comment]
FYI I think @RiccardoRossi wants to remove the weak_ptrs in the long run => #3255 
I guess it is not required then to implement the serialization for them (?)

**Comment by pooyan-dadvand** [comment]
For this reason I was asking if is urgent... I see that this would be a blocker... 
My problem is getting some time to do it....

**Comment by josep-m-carbonell** [comment]
Closed due to inactivity. Reopen if needed

**Comment by maceligueta** [comment]
@pooyan-dadvand , this issue is related with other Serializer problems, like the one detected by @josep-m-carbonell  and @roigcarlo , consisting in serializing a shared pointer and a raw pointer (both to the sam object). Apparently, if the first pointer found by the Serializer is the raw pointer, a copy of the object is stored, then the shared pointer could have a problem. Is the problem reported in any issue or PR?

**Comment by pooyan-dadvand** [comment]
I'm not sure if I have commented this. As mixing the share_ptr with raw pointer is something new in Kratos this problem have not been seen in the beginning and can cause serious problems
