### ISSUE TITLE
[FluidDynamics] Fluid Element Data Structure

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#2795]
Hi @rubenzorrilla and @jcotela,

I was in the process of including the Darcy Terms in the two fluid element I created. I am facing an old issue now. My idea is to create a method inside the two fluid element data that computes the Darcy term. This should be executed after UpdateGeometryValues as I need the shape function values. I'd like to avoid calling this method from the two fluid element as this (I think) goes against the whole idea of the data classes. So I guess we could ...

- Include this method (and other similar ones) in UpdateGeometryValues (maybe changing the name of this method)
- Add a new general method in all data classes that is always called after UpdateGeometryValues ( I leave the name to you)
- ??

**Comment by rubenzorrilla** [comment]
Hi @ddiezrod!

I ran into a similar problem while implementing a new embedded formulation (it is still pending to merge it). I like your second proposal. Correct me if I'm wrong, the idea is to implement an empty virtual method in the base data class which is overwritten in the derived ones. Isn't it?

**Comment by ddiezrod** [comment]
@rubenzorrilla Yes, that is what I meant, I also think it might be the best option. @jcotela ?

**Comment by jcotela** [comment]
I do not love the idea of adding more functions... We already have `FluidElement::CalculateMaterialResponse` that must be called after `Data::UpdateGeometryValues` and I have already lost some time debugging my own implementations because I called one but not the other somewhere. If we need to do add more steps on that chain, I'd define a wrapper function (probably in FluidElement) that calls everything in order.

@ddiezrod What specifically do you need to calculate the Darcy term? Just to understand the problem better.

**Comment by ddiezrod** [comment]
@jcotela
Darcy Term = A + |v| B 
where A and B are the Linear and Non Linear Darcy Coefficients respectively and |v| is the norm of the velocity at the gauss point.
Besides this method inside the data class, I have also other ones like CalculateDensityAtGaussPoint that are called from the element and I'd like also to call them from somewhere else.

**Comment by ddiezrod** [comment]
@jcotela Any thoughts? If it is not clear how to handle this yet, I can simply call this Darcy Term from the element and we will change this in the future...

**Comment by jcotela** [comment]
I see two potential ways to do this with minimal changes: one is to store A, B and the velocities on the data class and implement the A + |v| B operation in the derived element (the Darcy term would then need to be calculated on demand) and the other is to perform the same operation on an overload of FluidData::Initialize() (the Darcy term is pre-calculated and stored in some member of the element data). If these are not working for you, we can discuss how to improve the base interface.

What do you mean with CalculateDensityAtGaussPoint? Is the discontinuous interpolation? If so, I think that the original agreement with Riccardo was to call the regular GetAtCoordinate() methods with "positive only" or "negative only" shape functions instead of the regular N.

**Comment by ddiezrod** [comment]
@jcotela I think the second option is not possible as I need the values of the shape functions at the gauss points to compute the velocity. I am ok with the first option, although it adds more implementation details to the element.

Yes, it is the discontinuous interpolation. I was not aware of this GetAtCoordinate method. I will use that instead.

Thanks!

**Comment by jcotela** [comment]
@ddiezrod I believe you can do it as part of FluidData::UpdateGeometryValues(...) instead, but maybe we should change the name of the method if we see that more non-standard operations are needed.

**Comment by philbucher** [comment]
Is this solved?

**Comment by ddiezrod** [comment]
Hi @philbucher . Not yet, I am currently taking a look into this.

**Comment by ddiezrod** [comment]
@jcotela I have a branch which is computing correctly now the darcy terms. However I have found that the method that computes this term cannot be included inside UpdateGeometryValues as effective viscosity, which is calculated later in CalculateMaterialResponse, is necessary for the Darcy Term.

I do not see any option but include an extra step in the chain, maybe using some kind of wrapper function so everything is called in order (something like an "analysis" for the fluid elements). What do you think?

**Comment by jcotela** [comment]
Hi @ddiezrod, in the original design for the fluid element, the function CalculateLocalVelocityContribution https://github.com/KratosMultiphysics/Kratos/blob/cfef7dcd24ee8992c5a88f3148c47b9e7cf64f9d/applications/FluidDynamicsApplication/custom_elements/fluid_element.cpp#L209 played this role of directing the order of function calls, the only exceptions being mass terms (in the corresponding mass matrix contribution) and boundary integrals for embedded formulations (which we found too formulation-specific to generalize and left as the responsibility of each embedded implementation).

The simplest approach would be to fit the extra call you propose for the Darcy term in that general framework, placing it somewhere in CalculateLocalVelocityContribution. I believe this could solve your issues.

Having said that, one thing I do not like of the current design is precisely having UpdateGeometryValues and CalculateMaterialResponse as separate functions, since you always have to call one after the other (so keeping them separate is error prone, and I have often introduced bugs by forgetting to call one of them). I believe that merging them would also solve your issues, but that would be a change for all formulations derived from `FluidElement`. On the plus side, we would avoid introducing a third function that now we always need to call in order with the other two.

**Comment by ddiezrod** [comment]
@jcotela I am not sure if I completely understand your point. I was discussing with @rubenzorrilla that we could arrange a meeting to discuss it. Is that ok?

**Comment by rubenzorrilla** [comment]
Just as a reminder: we've decided to create a new method inside the base fluid element, something like `UpdateGausPointValues`. Inside this method we will call the `UpdateGeometryValues` as well as the `CalculateMaterialResponse`. Then each element can reimplement it according to its requirements, in this particular case to compute the Gauss pt. velocity and viscosity in the Darcy contribution.

**Comment by rubenzorrilla** [comment]
Must be fixed with  #3679 so I'm closing it. @ddiezrod feel free to reopen it if needed.
