### ISSUE TITLE
I want to know if my opinion is correct about kratos

### ISSUE THREAD

**Issue by ricardomerida** [KratosMultiphysics/Kratos#2825]
I want to write about kratos in my university 

Kratos is an analysis engine, it is called by its creators as the evolution of a scientific code, which is programmed in C ++ and is open source, it has Multiphysics packages and meshing as a function of time. This analysis engine was carried out by the International Center for Numerical Methods in Engineering CIMNE, which seeks to join in order to validate the analysis and develop more efficient methods of analysis for the MEF. This analysis engine meets the characteristics of a free and free software, with the disadvantages that it can not be used by users without programming knowledge, since it does not have a CAD drawing interface. This engine can be used by third-party organizations, which can be developed software with a simple interface whose analysis engine is KRATOS.

**Comment by loumalouomega** [comment]
Well we have a problemtype for GiD https://www.gidhome.com/. You can install the precompiled version of the last release there:

https://github.com/KratosMultiphysics/Kratos/wiki/Getting-Kratos-binaries-(via-GiD)

**Comment by loumalouomega** [comment]
Kratos is not just C++, it has an interface to Python, so you can use it directly from there.

**Comment by loumalouomega** [comment]
More here:

https://github.com/KratosMultiphysics/Kratos/wiki/Overview

**Comment by ricardomerida** [comment]
thanks for the link, this responded my questions.

**Comment by ricardomerida** [comment]
Where can I find videos about the compilation?

I am new at this

**Comment by loumalouomega** [comment]
Do you want a video to explain the compilation?, we don't have, but I can create one with a VM

**Comment by ricardomerida** [comment]
Thanks, 
I would appreciate it very much

**Comment by loumalouomega** [comment]
That's requires some extra work, can you try first following the wiki:

* Linux : https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build
* Windows: https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install
* MacOS: https://github.com/KratosMultiphysics/Kratos/wiki/MacOS-Install

**Comment by ricardomerida** [comment]
thanks

I'll check the links thank you very much

**Comment by ricardomerida** [comment]
I am from Guatemala and I want to write about Kratos, so I heard that there is a program called GiD that uses Kratos programming but uses a paid license, and I have heard that there are other options like the precompilation and the compilation, but this option does not have the ability to draw as CAD programs or import from CAD programs, It is correct?.

If I am a student,I am studying at the University of San Carlos in Guatemala. what is the price of the GiD license?  This license is generated by the University of Catalunya in Spain, is it correct?

**Comment by josep-m-carbonell** [comment]
Information about GiD can be obtained in https://www.gidhome.com/
GiD is not open-source and it is not free. You can use it without license but is limited to a number of geometrical entities and mesh entities. However you can obtain at least 3 monthly licences for free to try the professional version (it is easy, automatic password generation from the web page). You can ask for the price in the webpage contact address (you can also check it, registering and trying to purchase a licence in the webpage without completing the purchase). There are several options. GiD is sold by CIMNE, which is a research center linked to Universitat Politecnica de Catalunya but not it is not the same institution. See (http://www.cimne.com/).

Kratos is an open source project, therefore you have a programmed code mainly in C++ that can be compiled and executed. You can configure the compilation to select a particular set of applications in order to build a solution for fluids, solids, for thermal..., some of these applications are based in the implementation of different modelling methods, FEM, DEM, MPM,....Therefore, if you want only a fluid application, you can compile only the set of applications which implement the solution for the simulation of fluids.
Once the code is compiled it can be executed for a calculation. The configuration of the execution is done by a set of python scripts. It allows to configure a different solution options just modifying these scripts and they can be used to add new capabilities or to couple the solution of different applications. 
It is clear that in order to  run a problem some input data files are needed. Usually two o three files: one defining the calculation domain (nodes, elements, groups of nodes and elements..)  (file extension: .mdpa), another defining the calculation options called ProjectParameters (solver, constraints,boundary impositions, time discretization, output, etc..)(file extension/type: .json), in some cases also a file defining the material constitutive parameters and the properties of the domain (file extension: .json). 
All the input files have a common shared pattern and follow some rules. You can create them manually modifying some test example (not recommendable)  or use some of the GUI created for GiD to generate them. There is an open source general GidInterface for some of the simulation applications (https://github.com/KratosMultiphysics/GiDInterface). 

As commented before you can also use a pre-compiled Kratos version (a Release version) downloading it directly from GiD. This version uses the mentioned GiDInterface, you can generate a problem case and run it directly. The results are written, by default, in order to be read for the post process of GiD. However exist other options to generate files in hdf5 or vtk for Paraview. This also can be customized easily using python.
I recommend you to install GiD, download Kratos (its free), and run some of the test examples. You will need to ask for a free license for the large examples.

Thank you for your interest and good luck!

**Comment by ricardomerida** [comment]
Thanks for your help, this has been very useful.

Now I will install Github and download KRATOS, I will review the bibliography to be able to use the program.

Thank you

Have a nice day,

**Comment by philbucher** [comment]
I think this is solved,
Please reopen if otherwise
