### ISSUE TITLE
Properties object in SubModelPart must be a pointer to Properties of the ParentModelPart?

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#3030]
Now the Properties object belongs to each ModelPart and SubModelPart in an independent way. It means that the ParentModelPart properties object does not include the properties of their SubModelParts. 
Does it has any advantage or it will be better to have properties of SubModelParts as pointers of the Parent ModelPart properties (like ProcessInfo object)?

**Comment by RiccardoRossi** [comment]
This is a bug.

if you create a property in a submodelpart it should also create it in the parent modelpart (provided that you do it through the modelpart api)

could you create a test so that we can debug it?

**Comment by josep-m-carbonell** [comment]
```
import KratosMultiphysics

model_part = KratosMultiphysics.ModelPart("ModelPart")
sub_model_part = model_part.CreateSubModelPart("SubModelPart")

properties = sub_model_part.Properties[0]

print(model_part)
```
Output:

```
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-49f5efe649-RelWithDebInfo
 -ModelPart- model part
    Buffer Size : 1
    Number of tables : 0
    Number of sub model parts : 1
    Current solution step index : 0

    Mesh 0 : 
        Number of Nodes       : 0
        Number of Properties  : 0
        Number of Elements    : 0
        Number of Conditions  : 0
        Number of Constraints : 0

    -SubModelPart- model part
        Number of tables : 0
        Number of sub model parts : 0

        Mesh 0 : 
            Number of Nodes       : 0
            Number of Properties  : 1
            Number of Elements    : 0
            Number of Conditions  : 0
            Number of Constraints : 0
```

ModelPart has 0 properties and the SubModelPart has 1 properties.

**Comment by maceligueta** [comment]
Can you add properties just like that??
`properties = sub_model_part.Properties[0]`
IMO this should give an error if no Properties were added before...

**Comment by RiccardoRossi** [comment]
@josep-m-carbonell  the code just below would work and do what you intend. I agree beforehand that passing the mesh_id is not convenient, but there are a number of overloads that should be cleaned up. (I also agree that this should be improved to make it clear)

the problem is that if one manipulates directly the Properties array without passing through the modelpart API it is not possible to detect the manipulation and to reflect it within the modelpart tree

      import KratosMultiphysics
      
      model_part = KratosMultiphysics.ModelPart("ModelPart")
      sub_model_part = model_part.CreateSubModelPart("SubModelPart")
      
      prop_id = 0
      mesh_id = 0
      properties = sub_model_part.GetProperties(prop_id,mesh_id)
      print(model_part)

@maceligueta Properties is a PointerVectorSet, so if you access a inexisting term it creates it new. (same way as std::set does). I agree with you that this is a dangerous behaviour...but it is as it is (as of now)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee : This is a known issue due to the legal but legacy use of containers in the mesh which we think that should be avoided. So the strategy would be to block such accesses by returning a constant container as is discussed in #3227. Note that also #2181 is similar to this

**Comment by josep-m-carbonell** [comment]
Issue duplicated. Reopen if needed
