### ISSUE TITLE
How I learn Examples related to PFEM and MPM

### ISSUE THREAD

**Issue by BilalTsinghua** [KratosMultiphysics/Kratos#3036]
HI
 I want to learn examples related to PFEM and MPM. Help me in this , how to learn the examples and after learning how to write the script.?
Thanks

**Comment by josep-m-carbonell** [comment]
Hello @BilalTsinghua, I don't know about MPM application. But about pfem I can give you some guiding information:

After compiling Kratos with pfem application, you can go to the test folder of the PfemApplication, there are several examples there that can be tested. They are defined in the SmallTests.py, NightTests.py and ValidationTests.py. To run them individually you can do:

python3 run_tests.py  SmallTests.newtonian_dam_break_2D

This will run the newtonian_dam_break_2D tests defined in the SmallTests.py file. 
Then in the fluid_tests or solid_tests folder you can take a look on the configuration parameters of each one of them. For example: "dam_break_2D.mdpa" and "dam_break_2D_parameters.json". The first one (.mdpa) contains the definition of the mesh and parts of the domain and the second one the ".json", the configuration file. The configuration is changed to be a test instead of a normal case. The differences are the output:   "check_process_list"  is active instead of   "output_configuration"   (you must change it to get results for GiD, if there is  "_"  before the name it will not be considered (i.e. "_output_configuration" -> not considered, "output_configuration"-> considered, and an output will be written down). There are also some other small differences in the definition of the input file name.

The mdpa file is the same as a normal running case, the parameters file is a little bit different (as I said previously), usually the name for the configuration file is ProjectParameters.json. The materials file can have two different formats, a materials.py or a Materials.json. You can find a version of these files in the test folder.

I recommend you to download GiD and try the GiDInterface, there is one for SolidMechanics that generate a very similar input files which can be a guide for you. There is also a Pfem interface that is not fully functional yet.

**Comment by BilalTsinghua** [comment]
there are no examples shown in Pfem application Folder @josep-m-carbonell

**Comment by josep-m-carbonell** [comment]
Hi @BilalTsinghua , 
  There is a test folder that contains some "examples"
https://github.com/KratosMultiphysics/Kratos/tree/master/applications/PfemApplication/tests
If you don't have it, it is because you are not up to date with the repository.

**Comment by BilalTsinghua** [comment]
ok  now i got it @josep-m-carbonell

**Comment by BilalTsinghua** [comment]
I see those examples, now i want to write it on kratos , what should i do ? @josep-m-carbonell

**Comment by josep-m-carbonell** [comment]
As I said to you we have a Gid interfase for Pfem (www.gidhome.com) (https://github.com/KratosMultiphysics/GiDInterface) that is not finished yet. Essentially you need three files, the problem_name.mdpa, ProjectParameters.json and Materials.json(or matetials.py).

By using python3 you call a script like this one: 
https://github.com/KratosMultiphysics/GiDInterface/blob/master/kratos.gid/apps/Pfem/python/RunMainPfem.py

This script must be copied in your problem folder.

**Comment by bodhinandach** [comment]
@BilalTsinghua Hi, I am currently the active developer of MPM in Kratos. I would apologize that, currently, the application doesn't have any test cases uploaded yet. However, I am working for this to be online as soon as possible, hopefully, by the end of this month.

**Comment by BilalTsinghua** [comment]
@bodhinandach  ok thanks for feedback

**Comment by bodhinandach** [comment]
@BilalTsinghua I got the tests now in the master branch.

**Comment by philbucher** [comment]
Closing since inactive
