### ISSUE TITLE
[Core] Check if model part is empty only if the variable is not added

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#3037]
@KratosMultiphysics/technical-committee 
Now, the model part throws an error if it is not empty when we try to add a variable. I suggest that this check is performed only if the variable was not added before. Something like this:

```
 void AddNodalSolutionStepVariable(Variable<TDataType> const& ThisVariable)
    {
        if (!mpVariablesList->Has(ThisVariable)) {
            KRATOS_ERROR_IF((this->GetRootModelPart()).Nodes().size() != 0) << "attempting to add the variable: " << ThisVariable.Name() << " to the model part with name: " << this->Name() << " which is not empty" << std::endl;
            mpVariablesList->Add(ThisVariable);
        }
    }
```

I think it is a fair solution and this will make things easier for us in terms of structure.

**Comment by loumalouomega** [comment]
Better KRATOS_DEBUG_ERROR_IF that way you don't reduce performance on Release

**Comment by ddiezrod** [comment]
@loumalouomega It is not a matter of performance (the difference would be insignificant) the problem is related to our actual code structure when we run different stages. This would be an easy fix for us and I think it would cause no harm.

**Comment by philbucher** [comment]
@ddiezrod do you have the latest version of Master?

The same problem you are having now came up earlier and I think I solved it => [there is even a test for this](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/sources/test_model_part.cpp#L40-L52)
Check out the current code in master:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/model_part.h#L507-L519

@loumalouomega this must be a regular error, since it can lead to severe memory problems!

**Comment by loumalouomega** [comment]
I like living on the edge

**Comment by philbucher** [comment]
> I like living on the edge

fine for me, but please don't mess with my memory ;)

**Comment by ddiezrod** [comment]
Ohh I see. I was working with Release 6.0. Thanks @philbucher  and sorry for the noise.
