### ISSUE TITLE
If the only files changed are python scripts why is necessary to wait for appveyor and travis compilation in a PR ?

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#3046]

**Comment by loumalouomega** [comment]
@roigcarlo

**Comment by jcotela** [comment]
Because travis runs the tests, and python files may very well affect tests passing/not passing.

There were some technical reasons why it was hard to detect if a PR affected only some files/file types (which is why travis always compiles, even if you just change python), but that does not change the main point.

**Comment by josep-m-carbonell** [comment]
Good, there is no problem to wait for the compilation, just it is a result that you know in advance. It would be optimal if the system could detect if only python files are modified and run the tests in that case. I guess it must be hard to detect when this happens, as you argued.

**Comment by roigcarlo** [comment]
As @jcotela said is technically hard. There is no problem per-se into detect that only python files where modified but adding that along with other features that we currently have enabled. In particular the problem is catching, cotire, incremental builds and auto-cancels as well as some filters.

Also I understand the problem and it will be a priority when I set up our machine but right now is hard to change without breaking everything.
