### ISSUE TITLE
How to make automatic the internal variable interpolation?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#309]
Yesterday I added the pull request #307, to interpolate the internal variables from two model parts. I have been speaking with @RiccardoRossi  and the one of the things that we need to improve is to do the interpolation automatically. For that purpose the CL requires to know the internal variables from it depends, but due to the inter-modular structure of the CL it is complicated (depends of a flow-rule, hardening-rule...). 

So I have been thinking and maybe this is a good idea, we add a  to each "part" of the CL the method `GetInternalVariablesVector`, this method call simultaneously to the "parts", that have that same function `GetInternalVariablesVector()` implemented, something like:

In the CL:
~~~c
void GetInternalVariablesVector(std::vector<Variable<double>>& IntVarVector)
{
      IntVarVector.clear();
      mpFlowRule->GetInternalVariablesVector(IntVarVector);
      mpYieldCriterion->GetInternalVariablesVector(IntVarVector);
      mpHardeningLaw->GetInternalVariablesVector(IntVarVector);
}
~~~  

In some of the "parts":

~~~c
void GetInternalVariablesVector(std::vector<Variable<double>>& IntVarVector)
{
      IntVarVector.push_back(PLASTIC_STRAIN);
      IntVarVector.push_back(DELTA_PLASTIC_STRAIN);
}
~~~

**Comment by josep-m-carbonell** [comment]
It is a little bit more complex than this, there are some historical (member) variables stored in the laws themselves usually the total magnitudes of  F0 , detF0, and C/b (or Eps0), and others that are considered internal variables of the plasticity model [a1,a2,a3], that would be the internal variables vector.  There is no problem to ask for the internal variables set in order to interpolate them. The current structure of the CL is not so general, this is why a new implementation is going on in the new ConstitutiveModelsApplication. I am working on it now, so I have not made any official announcement to review it yet. But you can take a look and propose improvements as the one you ask for here. A fixed set of internal variables can be established for the interpolation of their values.

**Comment by RiccardoRossi** [comment]
Hi @loumalouomega, @josep-m-carbonell, all,
     i think that the point rised by @loumalouomega is valid and goes well beyond the implementation detail of how the ConstitutiveLaw is being implemented.

From the outside, the FlowRule etc, are _an implementation detail_, and the user should not be aware of it at the moment of interpolating variables. Same happens for F etc.

the approach described by @loumalouomega is actually very similar to that employed in the very old "structural_mechanics_application". The idea is that each constitutive law shall know how to serialize/deserialize its internal data to a vector of doubles so that it can be interpolated.

The nicety of such approach in that it does not require the user to know anything of the internals of the CL to be interpolated while still retaining a reasonable efficiency. This is very important particularly in the context in which multiple CLs may exist in different parts of the domain.

The question is: **is there today any mechanism of this type in place?** if not, what are the foreseeable difficulties with the design i propose?

**Comment by pooyan-dadvand** [comment]
In my opinion we should have a method which "serializes" the interpolatable values (like doubles and array_1d) to a vector of double so a simple loop can interpolate them. This mechanism would be also interesting for synchronization in MPI.

**Comment by loumalouomega** [comment]
I will close this old issue, if we need to discuss more I will open again
