### ISSUE TITLE
impossible to compile with both ublas and amatrix

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#3243]
@pooyan-dadvand here it is an example where it is impossible to find a solution that works both with ublas and AMATRIX

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/custom_elements/embedded_fluid_element.cpp#L375

**Comment by jcotela** [comment]
@RiccardoRossi a comment, just because I am the person who wrote that particular "fix": the idea is that once AMatrix is the default, the `KRATOS_USE_AMATRIX` goes away and we just delete all `#else` branches. I do not see it as a bad thing.

Also, once AMatrix is the default, we'll be able to do things like initializing AMatrix vectors using C++11 array notation, which I plan to use extensively, so I've already in mind to do another AMatrix pass for the fluid application anyways. In this sense, I don't think that the workload overhead of defining these conditional solutions is too great to do big changes in AMatrix for it.

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi Thanks for the example. Unfortunately for that I should declare the `operator()` for different expressions which I tried once without success... (compiler ambiguity error) and I wasn't very convinced about adding it so I put it aside.... I will try it again if it is considered as real bottleneck.

**Comment by philbucher** [comment]
is this still active?

**Comment by philbucher** [comment]
can we close this?

**Comment by jcotela** [comment]
There is at least one blocker I know of in the fluid dynamics application, in a part of the code I would like to replace by @sunethwarna's statistics application once it is ready
________________________________

**Comment by rubenzorrilla** [comment]
I think we can close this one.
