### ISSUE TITLE
Failing sensitivity calculation with shells

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#3247]
The sensitivity calculation for the thin quad shell (ShellThinElementCorotational3D4N) fails. To be more precise, if a linear analysis is specified, it produces different sensitivities even when the shape is not changed and only the gradient calculation is called several times. If a non-linear analysis is specified, this is not the case anymore. However, as soon as the shape changes, also the sensitivities grow unboundedly. 

Also, the sensitivity calculation of the ShellThickElement3D4N fails (unbounded values) if in the functions CalculateRHS and CalculateLHS, not both flags are set to true.  @philbucher So obviously, the shell does not properly distinguish these two calls. 

As a consequence of these issues, right now, an optimization with thin quad shells is not possible. These failures really have to be fixed in order to allow for proper shell optimization/sensitivity analysis.

**Comment by philbucher** [comment]
@dbaumgaertner can you please provide a minimal example showing the mentioned behavior?
-> in the line of the tests, e.g. test_patch_test_shells.py

Otherwise this is very difficult to debug

Also it is not clear to me if the shells are failing or the sensitivity calculation 
-> therefore the minimal example

**Comment by dbaumgaertner** [comment]
@philbucher Here you go: [minimal_example_gradient_calculation_failure.zip](https://github.com/KratosMultiphysics/Kratos/files/2542498/minimal_example_gradient_calculation_failure.zip)

One thing I already noticed is that the changing sensitivities in a linear analysis over some iterations with no shape change is due to the fact that obviously a linear analysis for the shells is implemented as a single step of a non-linear analysis --> Running a few times the solution without chaning the shape leads to a converging displacement field, respectively response value and senstivity field.

**Comment by philbucher** [comment]
> @philbucher Here you go: [minimal_example_gradient_calculation_failure.zip](https://github.com/KratosMultiphysics/Kratos/files/2542498/minimal_example_gradient_calculation_failure.zip)

This does not only use the shells but also the structural-response, which I don‘t know in detail. Therefore only Martin and Armin can help you with this

> One thing I already noticed is that the changing sensitivities in a linear analysis over some iterations with no shape change is due to the fact that obviously a linear analysis for the shells is implemented as a single step of a non-linear analysis --> Running a few times the solution without chaning the shape leads to a converging displacement field, respectively response value and senstivity field.

If you use the nonlinear shell, then this is exactly what is expected... why not using the linear one...?

**Comment by AndreasWinterstein** [comment]
@dbaumgaertner 
Just a comment from my side: If your are using the CR shells they always have nonlinear kinematics. Only the "normal" shells without the CR addition have linear kinematics. As @philbucher says the nl shell does exactly what it should. I do not know what happens if you are solving the CR shell, which has nonlinear kinematics, with the linear strategy. This we would have to test. 

Since the splitting for the matrices is done anyway in the elements into K_e, K_g and K_u  one solution could be to only assemble K_e in the linear case. But I am not sure if this works. This also would have to be tested.

**Comment by AndreasWinterstein** [comment]
Is this solved?

**Comment by dbaumgaertner** [comment]
@AndreasWinterstein thanks for that comment. And the problem is not solved in a sense that I also want to discuss it with @armingeiser once he is back.

**Comment by AndreasWinterstein** [comment]
ping @dbaumgaertner @armingeiser

**Comment by AndreasWinterstein** [comment]
ping @dbaumgaertner @armingeiser

**Comment by philbucher** [comment]
is this still active?

**Comment by philbucher** [comment]
closing since inactive, please reopen otherwise
