### ISSUE TITLE
Remove LaplacianMeshSolver

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#328]
Since it has shown that the LaplacianMeshSolver is performing not very well I would suggest to remove it from the ALEApplication. I would suggest to replace it by the VertexBallSpringSmoothing method in the nearer future. 

Please let me hear your comments about this.

**Comment by rubenzorrilla** [comment]
Hi @AndreasWinterstein!

Since the ALE application has a reasonable number of files and is well organised, I would keep the LaplacianMeshSolver and just add the VertexBallSpringSmoothing one  (even though I did not ever used it, but IMO it might be useful for any comparison or test in the future). In any case you are the expert on the topic, so if you consider that it is not worth it to keep it, feel free to remove it.

**Comment by RiccardoRossi** [comment]
Hi Andreas,

is it "severely broken" or simply "it does not work very good"?

cheers
Riccardo

**Comment by AndreasWinterstein** [comment]
Hi together,

currently it is broken. I do not know how severe. I can try to fix it and we can keep it. Furthermore in my opinion it does not work very well.

**Comment by rubenzorrilla** [comment]
@AndreasWinterstein shall we close this?

**Comment by pooyan-dadvand** [comment]
Actually I have not aware of this smoother and I have added a new `MeshLocalSmoothingProcess` 

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/mesh_local_smoothing_process.h

which does the laplacian smoothing and some derived ones with diferent criteria like `TetrahedraMeshWorstElementSmoothingProcess` and `TetrahedraMeshQualityWeightedSmoothingProcess`

They work but unfortunately I cannot find the test that I did for them...
