### ISSUE TITLE
Serialize objects for sending them with MPI

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#346]
I am currently modifying the mapper and enhancing especially the MapperCommunicator.
In addition to exchange Variable values I want to be able to extract values from the partner-objects.
For this I have to exchange data with MPI, independent of the datatype, which requires serialization of the object. 

I took a look at the MPICommunicator and the "AsyncSendAndReceiveObjects" function and intend to do sth similar. @adityaghantasala and I thought that the serialization offered by boost seems to be suitable since it also works for every STL container.

What is your opinion on this?

**Comment by RiccardoRossi** [comment]
hi guys,
     i think your question is best addressed by @pooyan-dadvand or @roigcarlo 

i know for sure they considered boost::serialization and decided otherwise, however i am not aware of the full details

**Comment by jcotela** [comment]
I had to think about this a while ago for a tool I was coding at the time, and in my opinion serialization is overkill: most of the time you just need to send a few doubles per object, not entire classes. I don't think we need that level of generality, since what we send is usually some kind of vector/matrix and filling a buffer with doubles is enough to do the job (maybe ints and bools from time to time, but rarely more than that).

My recommendation is to have a few auxiliary functions (maybe classes) that know how to send and receive an mpi message to transfer the most common types of data: doubles, vectors (of fixed and variable size), matrices,... and how to build the corresponding object on the other side. I think that this should be much more efficient (in terms of amount of data sent) than serialization, and would allow the option to use the serialization based solution as a default for strange or unexpected data types.

In any case, as @RiccardoRossi was saying, it was decided in the past to skip boost serialization and build our own kratos serialization classes (I don't know the technical reasoning either). I would recommend building on that rather than introducing more dependencies to boost packages.

**Comment by pooyan-dadvand** [comment]
For the serialization I tried to use the boost one but there was many (and many) complication and ambiguity in the use. So finally I decided to implement my own one which is the one in Kratos. 

As @jcotela said we have found the use of serialization for MPI as an overkill while we don't need to send all of the pointers of an object to reconstruct it again on the other side. 

One solution would be to set MPI flag in serialization so we can check in load and save if is MPI communication and reduce data. However this solution would cause lot of corner cases and each solver would try to send different data.

For this reason I started to with the GlobalPointer idea (which I discussed with you in TUM) which tries to not pass the object and perform the operation where the object is and return only the result of an operation. So in long term this should be our way to go. Then using the existing serializer for passing the results would be efficient. 

Last week we have finished a deadline and so now @roigcarlo can start implementing this idea.

**Comment by philbucher** [comment]
Basically I just want to send some vectors or matrices, nothing fancy or complicated. But still one needs some sort of "serialization".
I think what @jcotela suggests with the aux classes (for Vector, Matrix and maybe some more types) sounds good. Where would be a suitable location in the code for this? I guess the core bcs it seems like sth general.
@pooyan-dadvand what I want to send is already raw and processed data. But as I mentioned already one needs some way to send it with MPI

**Comment by pooyan-dadvand** [comment]
For that you may use directly the `Serializer` of Kratos and it should work quite fast for that.
