### ISSUE TITLE
How to belong to the list of the Main Applications of Kratos

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#3553]
In the front page of Kratos repository (readme) there is a list of main applications. Are there any rules or requirements to belong to this list? When is an application considered to belong to the status of main application or secundary application? What are the advantages of belonging to the "main applications" group? It is going to receive more support from core developers to ensure is up to date when "the standards" change? @KratosMultiphysics/all

**Comment by pooyan-dadvand** [comment]
Good question! As far as I know there are no clear definition... And just checking it after seeing this issue I realized that it is very inconsistent.... 

I would like to hear community opinion before discussing it in @KratosMultiphysics/technical-committee

**Comment by jcotela** [comment]
Just to clear any confusion, being "in the list" does not confer any kind of privilege. There is no extra support to keep the applications up to date, since there is no manpower to do so. If anything, there should be extra pressure on their maintainers to keep up to date, since applications not up to standard should not be presented as "main".

**Comment by josep-m-carbonell** [comment]
@jcotela, do you mean that being "in the list" is a bad business? And what do you mean when you say "applications not up to standard"? Are there applications not following "kratos rules" in the repositori? Which parameters do you use to classify them?

**Comment by GuillermoCasas** [comment]
I agree with @josep-m-carbonell that such list should reflect something unambiguos. Otherwise the list should not be there until such criterion is clearly established. If the intention is to maintain the list, I believe that at least a guide should be produced explaining the criteria behind the selection. Here are some ideas to what such criteria might include:
1. **Maturity**: The application has been there for a long enough time.
2. **Robustness**: The application includes a complete-enough list of benchmark tests
3. **Documentation**: The application is well-documented.
4. **Scope**: The application has a large-enough scope, meaning that it solves a problem that is not too specific, so that it is of general interest.
5. **Coding standards**: The application follows closely the standard.
Supposing that the final decision concerning the inclusion of an application to the list corresponds to the Technical Committee, it would be good to establish the steps to be followed to apply to the list (if it is not possible, make that explicit) and in what circumstances an application may be removed from the list.

**Comment by jcotela** [comment]
@josep-m-carbonell I think it is pretty evident that not all applications in the repository are equal, using whichever measure you want to use (see for example the suggestions of @GuillermoCasas). As @pooyan-dadvand  already said, no specific criteria exist at this point. I was just answering your other questions, regarding what it means to "to be in the list".

**Comment by josep-m-carbonell** [comment]
Solved. Reopen if needed
