### ISSUE TITLE
SolidMechanicsApplication

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#364]
I cannot execute the test examples of the 'SolidMechanicsApplication'
The error is: 
```
import restart_utility           as restart_utils
ModuleNotFoundError: No module named 'restart_utility'
```
In '1_Thin_plate_Axial_load.gid' I launch 'runkratos run_test.py' with 'Kratos 5.0.0-cab42cf'

Thanks in advance

**Comment by loumalouomega** [comment]
I think the test examples in the SolidMechanics are completely over deprecated, in fact the elements are now in the StructuralMechanicsApplication, use them instead.

**Comment by josep-m-carbonell** [comment]
The error is coming because these examples are not up to date and are still using the old main script of python for executing the SolidMechanicsApplication. They all use solid elements.
The solid elements are located in the SolidMechanicsApplication, and if any new solid element is developed, the place to locate it is the SolidMechanics. Structural elements (beams, trusses, plates, membranes and shells) were moved, some time ago, and after a decision of the "chiefs", from the SolidMechanics to the StructuralMechanics. Therefore the StructuralMechancis App has the role to be an specialized App, deriving from the SolidMechanics App, for the specific treatment of structural elements. This is what I understood when it was conceived.

**Comment by loumalouomega** [comment]
Yes, the test examples were in fact moved to the Structural but for some reason one copy remained in the SolidMechanicsApplication, I solved this in the #365, removing the deprecated examples and adding tests following the current standard

**Comment by josep-m-carbonell** [comment]
I am for adding unitests to the SolidMechanics. I think  the tests must be added where things are implemented.

**Comment by loumalouomega** [comment]
In #365 everything is related with the SolidMechanics, I just added two python processes to the core that are necessary to check analytically the solution of the problem

**Comment by PhilippeBussetta** [comment]
What is the differences between “SolidMechanicsApplication” and “structural_application”?

**Comment by loumalouomega** [comment]
The "structural_application" is the legacy "StructuralMechanicsApplication", is not currently supported, besides some developers still use it and develop things in application.

**Comment by loumalouomega** [comment]
@PhilippeBussetta , do you think that we can close this issue?

**Comment by PhilippeBussetta** [comment]
Yes, I think.
