### ISSUE TITLE
DEM:could we use the cluster to simulate the real shape of particles

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3691]
![default](https://user-images.githubusercontent.com/38140045/50169856-6a17d500-0329-11e9-95a7-54c430b29550.png)
Dear @maceligueta  and @farrufat-cimne 
I know that in DEM we can use only the sphere to simulate the particle. If we want to use dozens of sphere element together to make a new element and to simulate other different shapes, just like the picture shown. If we want to do that, we can add particle_cohesion in the properties part of .mdpa file. But, if we define many different part, should we use the cluster? Because in the example, there is the input files including ....._cluster.mdpa.
Best regards.

**Comment by maceligueta** [comment]
Yes, you can work with clusters as well. This feature is working since long ago.
The easiest way to start working with it is to use the inlet to generate them. Note that from the GUI (G-DEMpack for example) you can choose different types of elements. There's a limited list of clusters you can choose, but you can customize your own as well by writing a .clu file.
