### ISSUE TITLE
TrilinosApp Tests Failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3694]
For me `TestTrilinosRedistance` and `TestTrilinosRedistanceInMemory` are failing (I tried different numbers of cores). The first one sometimes throws an error saying that there are no dofs ...
They are segfaulting in Release

Also the Aztec-CG-Solver does not converge if I use more cores (might be bcs problem becomes too small per core, I don't know)

@roigcarlo I don't think the partitioning-in-memory has a problem, I am successfully using this in the MPI-tests of the MappingApp

@jcotela some of the things in the trilinos-app don't have anything to do with trilinos
Do you plan to move them to the mpi-core? usually those are the mpi-versions of things in the core

**Comment by jcotela** [comment]
> @jcotela some of the things in the trilinos-app don't have anything to do with trilinos

@philbucher please document those you find in #2945, so that we have them in mind for eventual migration.

**Comment by philbucher** [comment]
> > @jcotela some of the things in the trilinos-app don't have anything to do with trilinos
> 
> @philbucher please document those you find in #2945, so that we have them in mind for eventual migration.

From what I could see the list there contains all things already :+1:

**Comment by philbucher** [comment]
I think now also another test is failing:
~~~
======================================================================
ERROR: testTrilinosRedistance (__main__.TestTrilinosRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_trilinos_redistance.py", line 86, in testTrilinosRedistance
    epetra_comm, self.model_part, trilinos_linear_solver, max_iterations).Execute()
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. KratosTrilinosApplication.TrilinosVariationalDistanceCalculationProcess3D(arg0: KratosTrilinosApplication.Epetra_MpiComm, arg1: Kratos.ModelPart, arg2: KratosTrilinosApplication.TrilinosLinearSolver, arg3: int, arg4: Kratos.Flags)

Invoked with: <KratosTrilinosApplication.Epetra_MpiComm object at 0x7f6c236f4f48>, <Kratos.ModelPart object at 0x7f6c236f4ea0>, <KratosTrilinosApplication.AmesosSolver object at 0x7f6c08c8a030>, 2
~~~

@swenczowski could this be related to the changes you recently did to the constructor?

**Comment by swenczowski** [comment]
I apologize for the delayed answer. Indeed, I overlooked the occurrence in the py-test and missed to insert the "flag argument" `KratosMultiphysics.VariationalDistanceCalculationProcess3D.NOT_CALCULATE_EXACT_DISTANCES_TO_PLANE`. I am addressing this issue in #3790.

After the correction of my error, the test still crashes with 

`ERROR: testTrilinosRedistance (__main__.TestTrilinosRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_trilinos_redistance.py", line 87, in testTrilinosRedistance
    KratosMultiphysics.VariationalDistanceCalculationProcess3D.NOT_CALCULATE_EXACT_DISTANCES_TO_PLANE).Execute()
RuntimeError: Error: No degrees of freedom!`

which I think is the error originally described by @philbucher.

**Comment by swenczowski** [comment]
> Also the Aztec-CG-Solver does not converge if I use more cores (might be bcs problem becomes too small per core, I don't know)

The same experience was made for the MPI version of the `amgcl` solver in an application case (of a considerable size). In contrast, the serial version performs as expected.

**Comment by swenczowski** [comment]
Concerning the failing test, I made an observation - my apologies in case I am entirely mistaken.

In the function `ReGenerateDistanceModelPart` of class `TrilinosVariationalDistanceCalculationProcess`, the following [lines](https://github.com/KratosMultiphysics/Kratos/blob/ac1285323c6b80d901f16f740177b1ac6f438623/applications/trilinos_application/custom_processes/trilinos_variational_distance_calculation_process.h#L196) 

`ModelPart& r_distance_model_part = base_model_part.GetModel().GetModelPart("RedistanceCalculationPart");`
`r_distance_model_part.Nodes().clear();`
`r_distance_model_part.Conditions().clear();`
`r_distance_model_part.Elements().clear();`

are found. It appared as if here all nodes, condition, and elements were deleted. This theory was supported by inserting `KRATOS_WATCH( base_model_part.Nodes().size() )` etc. directly before and after the calls of `.clear()`. Also, it explains the "no dofs" error message. However, for other applications, the process seemed to work.

The reason for the error seemed to be in the python file of the test:

In #3306, `self.model_part = current_model.CreateModelPart("Main")` was exchanged to `self.model_part = current_model.CreateModelPart("RedistanceCalculationPart")`. When handed over to the function, the main model part and the added model part are the same by name. Clearing one means clearing both (because also no new one is generated). The simple solution is a renaming the created "main model part" in the python file as suggested in PR #3805.

**Comment by philbucher** [comment]
now the tests are working again!

Thanks @swenczowski !
