### ISSUE TITLE
Check-Macros => can they be functions?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3733]
I was wondering if the testing-macros (e.g. `KRATOS_CHECK_NEAR`) have to be macros or can they be functions?
Reason I am asking is bcs I think the unrolling of Macros is slow and increases the compilation time

furthermore in #3053 you told me to use a function instead of a macro

FYI @KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
Hi @philbucher ,

Yep we are aware that it increases the compile time a lot. For now the reason is that using macros allows use to fake reflections (https://www.meetingcpp.com/blog/items/reflections-on-the-reflection-proposals.html) so we can print the name of the variables etc...

We have some ongoing developments to address the issue, particularly for matrices&vector, but it is scheduled for after amatrix.

**Comment by RiccardoRossi** [comment]
also as @pooyan-dadvand observed, by using a macro the stack is simplified when throwing an exception

**Comment by philbucher** [comment]
Thx for the answers

@roigcarlo  the answer I gave here https://github.com/KratosMultiphysics/Kratos/pull/3729#discussion_r244305843 is still correct then right?

**Comment by roigcarlo** [comment]
Yes @philbucher , that will reduce the compile time, but keep in mind that in case of a possible error, the message will indicate `lumping_factors[i]` without telling you the actual value of `i`.

If you are ok with that np.

**Comment by philbucher** [comment]
ok thx for the help
