### ISSUE TITLE
MPI crashes on exit

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3751]
I get the following errors in almost every mpi-run (standard fluid simulation, nothing special), after the simulation finished succesfully
~~~
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[(null):4883] Local abort after MPI_FINALIZE completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
~~~

@jcotela did you notice sth similar?
could be related to #77 I think
also FYI @roigcarlo

**Comment by AndreasWinterstein** [comment]
Just a comment from my side. I did a lot of simulations with the current master branch the last days and I did not get this error. The reason might be that I am using IntelMPI. Which one are you using?

**Comment by philbucher** [comment]
OpenMPI
This was working before, I have the same installation of MPI for almost 2 years now

**Comment by jcotela** [comment]
@philbucher I did not see anything like it so far. We should probably check on your machine later. Are you mixing the new C mpi interface with the python one? That could be the source of the problem, since both may try to call finalize independently.

**Comment by jcotela** [comment]
Just to keep everyone updated, we just checked this with @philbucher and we believe it is related to interference between the old MPI Python interface and the new MPI Core. I think we can solve it by making the MPI Python interface to call the MPI core internally. I will address it in a new PR.

**Comment by jcotela** [comment]
The python garbage collector strikes again... I believe this is #77 all over again, but with the new pybind11 capsule technique to call MPI_Finalize.

Apparently Python decides to unload kratos and the trilinos application before destroying the solver strategy, which is what is giving you the error in this case (MPI_Finalize is called on unloading the KratosMultiphysics.mpi module. Just as a dirty hotfix which you can try, `del` your solver strategy from Python in the `Finalize()` method for your solver. For the monolithic fluid solver, this looks like:

```Python
def Finalize(self):
    del self.solver
    if self._IsPrintingRank():
        #TODO: CHANGE THIS ONCE THE MPI LOGGER IS IMPLEMENTED
        KratosMultiphysics.Logger.Print("Monolithic MPI solver Finalization finished.")
```

**Comment by jcotela** [comment]
Just for the record, @philbucher and I have checked this a bit more and there are a couple of changes that can be made to fix this without having to resort to hard deletes. One is that the Newton-Raphson strategy uses TSparseSpace::Clear to deallocate the system vectors, which internally just replaces the vector with a new uninitialized vector with the same underlying Epetra_Map (this errors out because copying the Map implies some MPI operations, which are not safe during destruction -- finalize was called before). Releasing the pointers to the vectors would be a more robust operation in this case.

This change, combined with calling Clear() methods for the linear solver (and probably other auxiliary classes) during the Finalize() of the python solver can make the errors go away.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee: To check this bugfix for Clear method and see if it improves the error
