### ISSUE TITLE
Unassigned people 

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#378]
Dear @KratosMultiphysics/technical-committee 
I keep being reported every now and then that some people loses his rights to upload code because they are removed from the team they are present, rendering them, indeed, unable to upload code.

In part this is my fault as normally if someone contacts me with this problem I assign them to a group I think it fits the code they are working on, usually because I know them and more or less I keep tack of they work. Clearly this does not work. 

I create this in the hope we can agree in a "protocol" so this situation gets minimized.

For the time being I just create a "Unassigned" team in which I can put people to give them rights without polluting the other teams witch people that don't belong there, but this is a bad solution at best.

Any ideas on how we can make this more organized?

**Comment by jcotela** [comment]
We were discussing this with @roigcarlo just now and we agree that the way permissions work now is a bit hard to manage. The main problem is that, since permissions (to push to branches, to review pull requests) are set on the group level, people must belong to a group in order to collaborate with us.

The current "protocol", at least in theory, is that new members should contact the person responsible for their desired group, who then requests @roigcarlo (or one of the admins) to add this person to the group. However, it is often not clear at all who is responsible for a given group. I don't even know if this position exists "officially" in the github structure.

We were considering, as an alternative, to introduce two levels of groups to separate permissions and subject area.
- We define a few "membership" groups: CIMNE, TUM, external collaborator,... People get permission to push, review, etc. based on belonging to one of these entities. The advantage of this is that admission is clear: if someone works at cimne, they get added to the group.
- Then we have "subject-based" groups like Fluid Dynamics, DEM, IGA, whatever. These groups have no special permissions (they are set to "read" permissions), but they serve to alert all members of a relevant discussion with the '@' mentions. Since they carry no privileges, joining (and leaving) can be more or less voulntary, based on research interets.

**Comment by maceligueta** [comment]
It's a nice solution.

**Comment by pooyan-dadvand** [comment]
👍 

Just to add that the official figure in GitHub is Team Mainter and I'm try assign it for each team.

**Comment by roigcarlo** [comment]
Seems this is under control now, closing.
