### ISSUE TITLE
[PFEM] Bingham and variable viscosity model

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3912]
Dear developers, @antonialarese , @josep-m-carbonell and @AFranci 
Hello, I want to ask the questions about the differene between Bingham and variable viscosity model. (this is from the paper "A Coupled Eulerian-PFEM model for the Simulation of overtopping in Rockfill Dams" which is completed by @antonialarese ).
As for the first example, there is a sentence explained that:
![bingham_variable yield model](https://user-images.githubusercontent.com/38140045/51484156-c3b26a00-1dd5-11e9-8efa-e1595226edcd.png)
Is this mean that the τ0=1000kPa in the Bingham model as same as the Φ=30° in the variable viscosity model. I know that the internal friction angle stands for the physically significant in engineering practice (such as a internal friction angle of the slope). But I don't know the real meaning of the yield_shear.
The other hand, can I change the types of the model (I know that we can simulate the Bingham fluid in the PFEM_Fluidapplication and other newton_fluid tests in the PFEM_FluidApplication). But after I read this paper, I don't know how to control the type of the model or what should I do in the PFEM_FluidApplication if I want to use the variable viscosity model for my simulation?
Best regards for you~ 
Feng

**Comment by antonialarese** [comment]
Dear Feng, 

Thank you for your interest in the non-Newtonian models.
Concerning your query, you can not compare directly the Bingham model and the Variable yield model since they are representing different materials. The objective of the example was to explain which are the properties of the variable yield models that cannot be captured in a classical Bingham model.

Bingham models have a constant yield that separate the rigid and the fluid-like behaviour of the material. This is a good description for paint and many other similar materials but not for granular materials.
These latter,in fact, need at least a point-wise definition of the yield stress, in function of both the effective pressure and of the kind of material (i.e., the internal friction angle). I chose the Mohr Coulomb failure criteria but other option are possible.

Unfortunately I am afraid that the current version of the PFEM model does not include the variable yield model but only the classical Bingham. @AFranci can you confirm it?



Regards,

**Comment by fengzekang** [comment]
Dear @antonialarese 
Thanks for your reply. I am learning about the PFEM and also do some tests using the PFEM/Kratos, especially the overtopping of the rockfill dam and the seepage conditions. I will continue to do related work. 
Best regards.
Feng

**Comment by rubenzorrilla** [comment]
I'm closing since the issue appears to be solved. @fengzekang feel free to reopen it if you require it.
