### ISSUE TITLE
solving scope of thermomechanicsapplication

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#3969]
what kinds of problems can thermomechamicsapplication solve?  can it deal with heat conduction, heat convection, heat radiation, or one of them? if i can simulate heat dissipation in structure or around structure.

**Comment by philbucher** [comment]
@jcotela

**Comment by jcotela** [comment]
@ZhimingGuo the thermomechanics application is relatively old, and we keep it mostly for backwards compatibility. It deals mostly with heat convection. I would suggest looking into the convection_diffusion_application, which mostly deals with heat convection but can also be used for conduction-only. It should be able to simulate heat dissipation in a structure due to the presence of a surrounding fluid, but I do not know if radiation is currently supported.
Mentioning @juliobarna @ipouplana and @rubenzorrilla since they have relevant experience in the convection_diffusion_application.

**Comment by philbucher** [comment]
is this still active?
