### ISSUE TITLE
Official way to apply a prestress or an initial strain

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#402]
Hi guys, particularly @KratosMultiphysics/structural-mechanics 

the title tells it all. Does it exist a convention on this?  if it doesn't can we decide smthg on the subject?

cheers
Riccardo

**Comment by vryy** [comment]
Hi @RiccardoRossi, regarding the prestress it's typically used in soil mechanics to account for pre-loading of the ground, especially when it consolidated for a long time under gravity.

AFAIK, there is two ways to account for prestress:
+ If we used a non-critical state soil model, i.e. Mohr Coulomb, the prestress is used to balance out the gravity. That means the (sigma+sigma0) will go into the constitutive law and the output with be offsetted by  -sigma0
+ For critical state model, i.e. modified cam clay, prestress is used together with OCR (over consolication ratio) to compute the initial preconsolidation pressure (pc) of the soil. This pc defines the yield surface and will be expanded/contracted if soil is hardened/softened.

I'm not very clear on your question. Do you mean to define a way to apply prestress for all type of application? In my point of view, that's not possible since it will depend on the constitutive law as described above.

**Comment by RiccardoRossi** [comment]
Hi @vryy, what i mean is that we should collectively agree on a "standard" way to apply a PRESTRESS/PRESTRAIN so that everyone does it in the same way.

That is, if someone implements a new constitutive law that should accept a prestress, than a convention should be followed

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/structural-mechanics this is to be discussed and closed
