### ISSUE TITLE
python_linear_solver_factory backward compatibility 

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#4244]
Recently I have found a problem using the python_linear_solver_factory. There is a modification of the parameters which is breaking my code. It seems to be related to #3635

https://github.com/KratosMultiphysics/Kratos/blob/644af658a7cd4910fa19953b21b3db415b650459/kratos/python_scripts/python_linear_solver_factory.py#L156

The python_linear_solver_factory is requesting a module in the configuration. However, on top of reading the configuration, this factory also modifies it. The point is that I need to reuse the configuration after sending it to the factory, because I am building several hierarchical solvers. I think others can run into the same problem, so I decided to open this issue to discuss some possible alternative solutions to this.

Maybe there is lack of consistency in the expected parameters by the `PythonLinearSolverFactory` and the `LinearSolverFactory`, which leads to the need for this modification. 

Some solutions could be:
- To apply some tricks on my derived python solver and my derived analysis (ugly patch)
- To call `LinearSolverFactory` with a local copy of the parameters instead
- To separately request for the solver type and the module, like the `ProcessFactory`, like this:
~~~
"module_name" : "KratosMultiphysics.ApplicationName",
"solver_type" : "the_solver_name"
~~~
Any suggestions?

**Comment by GuillermoCasas** [comment]
Interesting. I am moving this to the To-DOs list of the @KratosMultiphysics/implementation-committee

**Comment by loumalouomega** [comment]
You should use the factories instead, the factory is keep for backward compatibility reasons

**Comment by loumalouomega** [comment]
> You should use the factories instead, the factory is keep for backward compatibility reasons

Ok I see you commented that, sorry I read it partially

**Comment by philbucher** [comment]
Hi @miguelmaso 
Sorry for the inconvenience and thanks for reporting
your problem should be fixed in #4249, can you please try it? 
I no longer modify the incoming configuration, so now you should be able to use the same settings multiple times

Here are the answers to your suggestions:
> * To apply some tricks on my derived python solver and my derived analysis (ugly patch)

I agree, this is a global problem and local fixes won't help in the long run

> * To call `LinearSolverFactory` with a local copy of the parameters instead

Even though this would work, we try to avoid this, because the idea of the validation that happens inside the individual classes is that every class "adds" it's settings and afterwards one has a complete set of settings accessible from the outside

> * To separately request for the solver type and the module, like the `ProcessFactory`:

I would really like to avoid this for the following reasons:
- the discussion abt the naming-interface for the linear solvers was really tedious and we just updated all the kratos and the gid-interface. Already now it was hard to keep backwards-compatibility, and it will be even more difficult if we change it again
- For MPI-solvers it does not make sense to provide "TrilinosApplication", because all of them are in there
- Personally I don't see the need for an elaborate mechanism as we have for the processes, because the linear solvers are 1. only in very few apps and 2. never user-defined

**Comment by philbucher** [comment]
side question (in relation to @GuillermoCasas ):

> Interesting. I am moving this to the To-DOs list of the @KratosMultiphysics/implementation-committee

just to avoid misunderstandings between the responsibilities among the sub-committees, I thought this would be more a question for the @KratosMultiphysics/design-committee rather than the @KratosMultiphysics/implementation-committee , since the implementation is not really a problem here ...

@pooyan-dadvand what was your intention here?

**Comment by pooyan-dadvand** [comment]
I (personally) see the design as defining the objects, their API and their relations. And I see implementation as how to develop the design goals avoiding global code duplication, ensuring performance, etc. As you may imagine these two concepts overlaps and both team may interact on it. A typical example is when design can affect performance o implementation detail restricts the design. 

In fact, this case is a very good example of such overlaps because it reports a backward compatibility issue in input (interface committee) enforced by a factory design which was restricted by implementation details.

Meanwhile the idea behind committees was to actively look for issues and PRs and participate in them if they consider appropriate. The rationale behind is the fact that for issues like this, it is not clear what would be the optimum solution (redesign or reimplement) So having point of view of each team helps to achieve the best solution.
