### ISSUE TITLE
Warning- Variables Mismatch in Connectivity Preserve Modeler

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#4267]
After we merged to latest kratos, we are getting some warning in our altair applications,

Connectivity preserve modeler is complaining that variables do not match between origin and destination model part. I would understand this if we were not using then:

https://github.com/KratosMultiphysics/Kratos/blob/da4d5f5880b4b359b2c0de6f2fe2bff3c78bc843/kratos/sources/connectivity_preserve_modeler.cpp#L112

It seems to me that then the warning makes no sense and could be safely removed. What do you think @philbucher @RiccardoRossi @jcotela @jrubiogonzalez ?

**Comment by RiccardoRossi** [comment]
@ddiezrod please do not remove the warning. the problem here is that you did not add the same variables to the two modelparts. this is problematic at the moment of creating new nodes, since the new node would not contain the same variablelist.

the warning tells you to take care about this

**Comment by ddiezrod** [comment]
@RiccardoRossi I undertand this, but you are making sure that variables lists are the same in the line I wrote, so variables are always the same when the nodes are created.

**Comment by philbucher** [comment]
I also think the warning is necessary 
1. what if you have a variable in the destination-mp that you want to output later? It is removed in the line you reference and hence will crash when writing output
2. as Riccardo points out, you should always take care of the variables in the modelpart to be correct in the first place. I think Ruben implemented a merge functionality for this in the thermal-fluid solver to take care of this properly

**Comment by pablobecker** [comment]
If I underestand correctly, this warning is to tell the user "you wanted X variables, I don't care and will use these other ones". 
 IMO it would be better if it expected a model part with no variables at all

**Comment by pablobecker** [comment]
if model part has variables, return the warning

**Comment by philbucher** [comment]
This is what I mean: 
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/convection_diffusion_application/python_scripts/coupled_fluid_thermal_solver.py#L64

Maybe @rubenzorrilla can also comment

**Comment by ddiezrod** [comment]
To clarify my point, I do not mind maintaining the warning. It just seems to me that these two things together are somehow contradictory. @philbucher Take into account that in your first point, the output variable would not be present in the nodes if it was not in the origin model part.

**Comment by philbucher** [comment]
@pablobecker for my use-case I copy only a submodelpart, so it will always have variables already, but natively they are the same as in the (parent-)ModelPart, hence this operation is safe
Therefore I would only throw the warning if the variable-lists are different
And that is already happening

**Comment by ddiezrod** [comment]
> This is what I mean:
> https://github.com/KratosMultiphysics/Kratos/blob/master/applications/convection_diffusion_application/python_scripts/coupled_fluid_thermal_solver.py#L64
> 
> Maybe @rubenzorrilla can also comment

Thanks! That would solve my problem I think. Maybe we could then remove line 112 and throw an error instead of a warning.

**Comment by philbucher** [comment]
@ddiezrod you mean to throw an error in any case if the variable-lists are not equal?
I like it since it forces the user to take proper care of the sensitive subject of adding variables to the MP, and we can give a proper error message referencing the utility I pointed out

What do the others think?

**Comment by ddiezrod** [comment]
@philbucher yep, that is what i meant.

**Comment by RiccardoRossi** [comment]
I wouldn't be against throwing an error, however as i recall i was asked not to do that (i do not remember details unfortunately)

**Comment by ddiezrod** [comment]
@RiccardoRossi I am pretty sure that was me, sorry for that  :)  Anyway I think it would be the proper behaviour right now

**Comment by philbucher** [comment]
If we agree on sth (I think we have right?) then I can implement it, I am anyway working on it right now

**Comment by rubenzorrilla** [comment]
> This is what I mean:
> https://github.com/KratosMultiphysics/Kratos/blob/master/applications/convection_diffusion_application/python_scripts/coupled_fluid_thermal_solver.py#L64
> 
> Maybe @rubenzorrilla can also comment

Dear all,

Sorry for the late reply, I didn't realize that I was involved on this. What @philbucher is pointing out is that we want to share the same nodes in different model parts, which will have different element type, for the sake of coupling the thermal behavior between the CFD and the thermal solvers. Therefore what we firstly do is to enhance the variables list with the variables coming from each one of the solvers. In this way the nodes will have all the variables required by both solvers when importing the model part and "copying" it with the connectivity preserve modeler.

Based on this, there might be situations in where the destination and origin variables list do not coincide. For our thermal coupling particular application this turns into a problem, since the variables from one solver are needed in the other one and vice versa. However, there might be some applications of the connectivity preserve modeler in where there is no problem with having different variable lists. 

Having this in mind I would keep the current implementation which throws a warning and rely on the user to handle the variables issue. To throw an error might limit the application range of the connectivity preserve modeler.

**Comment by philbucher** [comment]
well if we keep the warning then I think we should also do what @ddiezrod points out in the first post, i.e. assigning the variables list to each other otherwise as he says the warning doesn't make sense

**Comment by rubenzorrilla** [comment]
Totally agree... the warning makes no sense if we always do `        rDestinationModelPart.GetNodalSolutionStepVariablesList() = rOriginModelPart.GetNodalSolutionStepVariablesList();` . Therefore we can either remove the warning or let the user to control the variable set outside the connectivity preserve modeler.

**Comment by philbucher** [comment]
I guess it would be better / more flexible to remove this line, bcs as @rubenzorrilla is saying, some day someone will need different variable-lists and then we have to change stuff again

**Comment by rubenzorrilla** [comment]
To remove the line makes also sense to me.

@RiccardoRossi you were the main promoter of this utility, so what do you think?

**Comment by jcotela** [comment]
Some thoughts on this, since I encountered this issue today...
In my opinion, the warning in connectivity_preserve_modeler is correct, because this class COPIES the node containers from one ModelPart to the other. This means that both modelparts will share the same nodes, so both modelparts should have the same variable list to avoid nasty surprises.

The safe solution would be to assign to the destination model part the variable list of the source one (it is the variable list that its nodes will use internally anyways), but I think that there is no interface to assign a variables list to an already existing model part (for good reason).

**Comment by sunethwarna** [comment]
Hi, I have few questions regarding this, if connectivity_preserve_modeller uses the same nodes, with different elements, then all the variables which are in the original MP would be existing in the new MP as well, will there be a different scenario where this is used?

It conserves the nodes=>conserves the memory used by the variables, then the new model part has the same variables., If not, everywhere we use connectivity_preserve_modeller, we will have to do what I did in #4897, wouldn't we?
