### ISSUE TITLE
Convergence Critaria & MPCs

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4486]
Based on the recent struggles I have some questions:
- why are the master-dofs excluded from the computation of the residual? => [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/convergencecriterias/residual_criteria.h#L241-L242) 
    I think they should not be excluded but I am not sure
- Don't we also need the same mechanism (detecting inactive dofs, i.e. slave and fixed) in the displacement criteria?
- why is the setting `mActualizeRHSIsNeeded` needed now? I know that it rebuilds the RHS before checking the convergence but why was this not necessary before?

**Comment by RiccardoRossi** [comment]
Hi @philbucher let me answer inline to your questions

    why are the master-dofs excluded from the computation of the residual? => here
    I think they should not be excluded but I am not sure

the "Residual Criteria" is based on asking that $Res(x(i+1))/Res(x0) < tol$ (in L2 norm).
The criterion is based on the concept that the nodal residual tends to zero on all **internal nodes**, meaning nodes for which a dirichlet condition is not applied. This is so since on dirichlet nodes the Res doesn't tend to zero (indeed it is -Reaction). This first is the reason for which fixed dofs need to be excluded from the residual calculation. 
When you add an MPC you are adding an additional constraint. The effect of the constraint is to add an **arbitrarilty large** system of forces onto the constrained nodes so that the desired constraint is met. such forces also do not converge to zero (similarly to the case of dirichlet dofs) and hence need to be taken out from the norm calculation, otherwise the norm will tend to a finite value rather than to zero and the criterion will never converge

    Don't we also need the same mechanism (detecting inactive dofs, i.e. slave and fixed) in the displacement criteria?

It is not needed since the Displacement Criteria measures $( x(i+1)-x(i) )/ x0$ the difference between the value at two successive iterations will correctly converge to zero both in the case of dirichlet dofs (case in which the difference is exactly zero) and in the case of MPCs

    why is the setting mActualizeRHSIsNeeded needed now? I know that it rebuilds the RHS before checking the convergence but why was this not necessary before?

The problem is that in order to compute the norm of $Res(x0)$ we need to compute the residual before doing any update. What happend before my correction was that we were starting after predict with a value $x0$, we were solving once the system for $dx$ and we were computing as initial residual the residual $Res(x1)$ this meant that instead of having 

$Res(x(i+1)/Res(x0)) < tol$ 

we were always considering

$Res(x(i+1)/Res(x1)) < tol$ 

now if the problem was quasi-linear, then $Res(x1) \approx 0$ so we were always getting a 0/0 and the convergence criteria was never met. This problem was detected originally by @mraschi, and we spoke about this extesively also with Prof. Xavier Oliver who has a lot of experience with this.

Does this answer you?

**Comment by philbucher** [comment]
perfect, thx a lot for the detailed explanation

I have one more question: If you say that we don't have to exclude the dirichlet-dofs in the Displacment-Criterion, then I guess [those `if`'s](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/convergencecriterias/displacement_criteria.h#L358) could be removed and we could directly use the `Norm` of the `Space` right?

EDIT on the other hand, if we don't exclude the fixed dofs & the MPCs then I think we won't achieve absolute convergence (e.g. in case of non-zero dirichlet BCs), only relative

**Comment by RiccardoRossi** [comment]
@philbucher i guess we could try to use avoid the use of ifs in the displacement criteria.

regarding reaching the absolute convergence, the criterion is that

norm(x(i+1) - x(i) ) / ndofs < abs_tol

in principle when nothing changes any longer two successive iterations are identical, so the abs_tol can be met

**Comment by philbucher** [comment]
ok I think I understood it now, I will make a PR after the workshop with some minor modifications (also to unify the mpi/non-mpi-versions)
