### ISSUE TITLE
About editing 3 files (4 places) when adding one variable

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#453]
Talking with @jcotela and @roigcarlo yesterday, we noticed that we might save a lot of time to the Kratos developers in the process of adding a new variable.
The basic idea would be to substitute the long lists of macros KRATOS_DEFINE_VARIABLE, KRATOS_CREATE_VARIABLE, etc... by a single loop in each file. The loop would take the information from a list of pairs that would contain the names of the variables and their type.
We did not foresee any blocker to this, however it would great to talk about it and see if it is really possible. I think the advantages are clear.
@KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
I agree with the idea but just a couple of things I noticed after we spoke:

The define/create macros will not be that straight forward to replace as we spoke, since we cannot make a loop that iterate the list as we discussed without more deep changes:

We didn't see that one now does:

```C++
extern Variable<double> VAR1;
extern Variable<double> VAR2;
extern Variable<int> VAR3;
```

But it is clear if we rewrite this:

```C++
for(...) {
    extern Variable<type> name;
}
```
That a loop construct here does simply not work.
Even if we manage to get something like this, we destroy the concept of "variables". 

It could be solved with a list maybe and making the variables strings?. Personally I would be against this because it will potentially introduce problems with the variable names that will only be detected when executing the code ( not in compile time as it is today ), and of course we would have to change the get/set....

Not to speak about the variables that need to be exported in win... 

Anyway, just throwing some thoughts I've been having after thinking about that after our initial discussion...

**Comment by pooyan-dadvand** [comment]
I agree with observation of @roigcarlo about the feasibility of the idea. 

A possible solution would be a python script which adds the variable (also checking of already exist in other applications etc.)

**Comment by RiccardoRossi** [comment]
Hi, I do not love the idea of a preprocessing step, since it is very easy to break it.

Now, if we define a tuple and we have the macro to add to that tuple, wouldn't it be enough?

**Comment by jcotela** [comment]
The problem is the C++ definition of the variable. As @roigcarlo was saying, it is not clear how it can be done from a tuple at compile time.

**Comment by RiccardoRossi** [comment]
i am thinking of the following:

in the file variables.h
the function DEFINE could define the variable and add an object of type Variable<whatever> to a list

then in the various cpps we could iterate over that list and do whatever needed.

of course the point is how to store the "Variable<whatever>"...

ciao
Riccardo

**Comment by jcotela** [comment]
That might work.
I just thought of another question: right now some files in katos have huge RAM requirements when compiling. I understand that variables.cpp is one of them, due to the macro unrolling going on there. What would happen if we put all the variables on a list and we try to compile them in a single unit? Would that be a problem for performance (at compile time)?

**Comment by pooyan-dadvand** [comment]
Any macro approach would be very complicated as we have very different arguments in creating the variables or components or the one with zeros. 

Again I see the python script for adding variable a better solution

**Comment by RiccardoRossi** [comment]
just to comment that with pybind in we could try to make outmatic the variable registration in python

**Comment by pooyan-dadvand** [comment]
Just to add that a more complete registry would help here.

**Comment by maceligueta** [comment]
Closing as it is inactive and not prioritary.
