### ISSUE TITLE
Problem with unit testing using more than one thread

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#461]
I am trying to make new tests using the python suit. I am using the compare_two_point_output_files_process, but in some cases the values in the comparison file slightly change from one execution to another and of course the test will fail. Furthermore the difference occurs always at different values of the files.

This problem does not occur if I am setting the number threads to one. I am using the ResidualBasedBlockBuilderAndSolver from the core, so there is no parallelization done in my application. Am I doing something wrong with the test or is the problem in my application? Did this problem ever arise before?

**Comment by RiccardoRossi** [comment]
Hi Andreas, some minimal oscillation may happen, but it should be limited to the last digits.

AssertAlmostEqual is designed to cope with this

Just to confirm, are u employing a direct solver in the test?

**Comment by ipouplana** [comment]
Hi Andreas, I must say that I also noticed the same problem in a test I prepared some weeks ago. 

The case was a plane-stress linear elastic beam subjected to a line load, solved with the SolidMechanicsApplication with all pragmas commented out (except for those in the core). I used the SuperLu direct solver.

I measured the Displacement-Y at a particular node and I observed the following: the solution was robust when running in a single thread, but with 2 or more threads the value of displacement changed every time I repeated the test. I am talking about changes in the 15th decimal position.

Although it might seem a very subtile change, when solving a quasi-static non-linear problem, that little error starts propagating from one step to another and, at the end of the simulation, the difference between the solution obtained in two consecutive cases run with more than 1 thread is perfectly noticeable...

That was the reason why, with @roigcarlo 's help, I uploaded a brief tutorial in the wiki on how to use ThreadSanitizer (https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-ThreadSanitizer-to-detect-OMP-data-race-bugs). In any case, I was not able to find the source of the problem in the PoromechanicsApplication nor in the SolidMechanicsApp, and I was told that @RiccardoRossi and/or @roigcarlo would look for it in the core when they could...

**Comment by RiccardoRossi** [comment]
Hi @ipouplana @AndreasWinterstein,
when you run in parallel the order in which you do the sums is not deterministic. This may lead to change in the last digits due to inherent rounding errors. 

if you have a linear problem such error should hopefully not accumulate, meaning that if you solve many times the same problem, the error remains of the same order. however, if your problem is nonlinear, at every solution stage you only enforce solution up to a tolerance. you can not expect more precision than that (the tolerance) if you start from a slightly different starting point. In this context an error greater than tol can accumulate during iterations.

I heard other people (working with other code) reporting the same kind of behaviour on different type of applications. Actually i was told that two "identical" simulations soon diverge in the context of turbulence.

in any case, if the error that appears within a single iteration is more than on the 14-15th digit then i expect a real error somewhere.

other than that i have no other feedback to provide ...

**Comment by ipouplana** [comment]
Thanks @RiccardoRossi, your explanation seems logical to me.

**Comment by RiccardoRossi** [comment]
@AndreasWinterstein, if you write new tests try to make them completely from python, as in 

https://github.com/KratosMultiphysics/Kratos/blob/feature-porting-elements/applications/StructuralMechanicsApplication/tests/test_patch_test_small_strain.py

it is a bit more laborious to make, however then it is self contained and easier to debug

cheers
Riccardo

**Comment by loumalouomega** [comment]
Hi, have we solved this issue?

**Comment by rubenzorrilla** [comment]
Is this solved?

**Comment by RiccardoRossi** [comment]
closing as inactive
