### ISSUE TITLE
Constitutive laws of solid mechanics

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#465]
I am a little bit confused about the structure of the constitutive laws into SolidMechanicsApplication.
1) Why the linear elastic laws derive from the hyper-elastic ones? I think that it could be better to inverse the hierarchy or put both class on the same level.
2) It is possible to choose the stress measure from outside of the material law. For example, the StressMeasure_PK2 is chose inside the membrane element. I think that it is better to uncouple the material computation and the element formulation in the aim to use different material laws with the same element formulation. Maybe it is better to choose the stress measure at the instantiation of the material law.
3) It feels that the linear elastic constitutive law is defined by python file as well as C++ class – "SolidMechanicsApplication\constitutive_laws\linear_elastic_constitutive_law.py" and "SolidMechanicsApplication\custom_constitutive\linear_elastic_3D_law". What is the preferable way to define material law?

**Comment by josep-m-carbonell** [comment]
Hello Philippe
    First of all, I must say that there is a work ongoing to build a better structure for the constitutive models. You can take a look of the application located in https://github.com/josep-m-carbonell/Kratos/tree/develop/applications/ConstitutiveModelsApplication

Answering to your questions:

1. This is like this because the linear elastic laws were created after the hyper-elastic ones. Specialising some methods. To not duplicate code, one was derived from the other.
2. Your element formulation depends on the stress measure you are using. However, if you write a flexible structure for your element that can accept different stress measures, then an option could be to pass a variable in properties and with that set the stress measure for your element before calling the material response.
3. It was an attempt to write constitutive laws using python. It will be possible (maybe not recommendable) to do it. Right now this capability is taken away from the SolidMechanicsApplication to not offer confusion. The preferable way is to write it in C++. 

If you have any other doubt or proposal, do not hesitate to ask here

Kind regards
