### ISSUE TITLE
[CFD] turbulence model / steady and unsteady flow

### ISSUE THREAD

**Issue by chen112p** [KratosMultiphysics/Kratos#4769]
Hello developers,

I am a novice user of Kratos with GiD user interface. What I am trying to do is going through some samples and tutorials as well as some CFD cases which I am very familiar with (to make sure I am doing right things). 

The problem I have encountered now is that I am not sure what turbulence model is being used. **How do you select the turbulence models in GiD?** Many journal papers I read talked about the work they did using LES on Kratos. So I am assuming LES is available, or maybe the default? Please correct me if I am wrong. 

Then it brought me to another question: in the 2D cases, **is the turbulence model selected LES?** 2D LES seems making no sense to me, but maybe I am wrong.

Also, nearly all examples I have seen are unsteady. **By chance Kratos support a steady RANS simulation?** k-e, k-w or k-w sst?

Thanks a lot,

JT Chen

**Comment by philbucher** [comment]
@KratosMultiphysics/fluid-dynamics

**Comment by jcotela** [comment]
Hi,
The CFD implementation of Kratos is based in the Variational Multiscale (VMS) method, a framework to derive stabilized finite element formulations. This method can be understood as a finite element version of Implicit LES if the mesh is fine enough (essentially, in the inertial subrange) and I assume that this is what is meant by the papers you have read. Regarding the relation between VMS and (implicit) LES, I would point you for example to https://www.sciencedirect.com/science/article/pii/S0045782508003265

Regarding 2D cases, you are essentially right. Since turbulence is a 3D phenomenon, transient 2D simulations cannot correctly capture the physics of the problem, either with LES or otherwise. Only averaged approaches such as RANS make sense in 2D.

Finally, regarding steady RANS in Kratos, it is currently under development. The development of the k-epsilon model is underway (@sunethwarna is currently implementing it) and k-omega/SST (and probably Spalart-Allmaras) will be coming next. Once they are validated, we plan to include them in the releases and the interface, but they not ready yet.

**Comment by chen112p** [comment]
Thank you very much for the explanation!

JT Chen

**Comment by jcotela** [comment]
Closing as inactive, since the original question was answered. Feel free to reopen if you have further questions.
