### ISSUE TITLE
[StructuralMechanics] specifying available elements for PreProcessor

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4773]
@RiccardoRossi and I were discussing to **replace** the xml that specifies the elements, conditions and constitutive laws in the GiD-Interface-repo (https://github.com/KratosMultiphysics/GiDInterface/tree/master/kratos.gid/apps/Structural/xml) by a json-file that is in the Kratos-repo and can be maintained by the developers themselves. This way the Interface will automatically be up-to-date, without @jginternational having to manually update

So far for the idea, at the beginning I think we could copy this file whenever necessary. Eventually we could replace it by sth automatic, I guess this should be possible

What do you think @jginternational ?

**Comment by jginternational** [comment]
Let me think about it and answer on Monday, but at first sight, my face looks like this 
![image](https://user-images.githubusercontent.com/5918085/57132045-9a26b880-6d9e-11e9-88ec-e3ad3e87aa92.png)

**Comment by philbucher** [comment]
@jginternational I think you misunderstood, this is supposed to make your life easier, not more difficult...

If you don't agree then please feel free to close this issue

**Comment by rubenzorrilla** [comment]
I think that to add an element to the GUI is quite easy (maybe I have this feeling because I am more or less used to it). Indeed, one of the aims of the current design was to make this kind of operations (add elements, add CLaws, ...) more or less straightforward.

Besides, this would add a (small) part of the GUI to the Kratos repo, something that I don't like too much.

**Comment by philbucher** [comment]
I think another idea was that this could be a uniform place where preprocessers can just load what is currently available
=> this way the preprocessor would automatically be updated

I personally find it quite difficult to add an element, even though I did it a couple of times already.

**Comment by philbucher** [comment]
ping @jginternational

**Comment by philbucher** [comment]
ping

**Comment by philbucher** [comment]
Ping @jginternational

**Comment by jginternational** [comment]
Time to answer,
The 'thing' here it's more a philosophical issue than anything

The GiD problemtype is 'one' Kratos interface, not necessarily the only one. On it's files you can find a lot of properties and definitions that are placed there to be processed by the GiD problemtype and customization system. 

Of course this could be implemented in a way so generic that those files were common for all the Kratos Guis, but I still think it's not a good model.

The current way to add a new item to the GUI is easy. It's via xml instead of json because the tdom library to handle xml in tcl is widely more reliable than the json one, but it should be easy for any Kratos developer to add a new element or condition to it's app.

I recognize that it's my bad the lack of documentation, in the sense that there nothing like a "How to" tutorial. Until June only 1/4 of my workday was destined to Kratos. Nowadays is 1/2, so maybe it's time to write more

**Comment by philbucher** [comment]
Thanks for answering @jginternational 

> The 'thing' here it's more a philosophical issue than anything

I disagree, this is about avoiding duplicated work (and making the life for all involved ppl easier), in the sense that things don't have to be added to every preprocessor manually in the format specific to the preprocessor that Kratos-devs are not familiar with (which is exactly the issue that @loumalouomega has in #5045)

> Of course this could be implemented in a way so generic that those files were common for all the Kratos Guis, but I still think it's not a good model.

I disagree, for the same reason as I wrote above

Either way, closing this for now, thanks for your contributions
FYI @RiccardoRossi

**Comment by RiccardoRossi** [comment]
i also agree with Philipp here.

the informations in the xml.are.usefuk.for anyone writing a gui. it woukd
be good if they were inside kratos  (with an automatoc conversion to the
xml the Javi uses).

the cool thing is that someone else coukd use the same info elsewhere...
