### ISSUE TITLE
[FluidDynamics] Historical variables in DistanceModificationProcess

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#4834]
Hi @KratosMultiphysics/fluid-dynamics!

I'm writing this issue after https://github.com/KratosMultiphysics/Kratos/pull/4811#discussion_r281951267.

In my application (PotentialFlow), I'm using the distance modification process to solve embedded geometries. However, if the "deactivate_fully_negative_elements" option is activated, it is required to define the VELOCITY and PRESSURE as historical variables in the solver, even if you dont need them. Would it be possible to make this optional?

https://github.com/KratosMultiphysics/Kratos/blob/c030f918a296b0b87c6a0c33bf823060791c2f4e/applications/FluidDynamicsApplication/custom_processes/distance_modification_process.cpp#L352-L363

Also, is there a specific reason that the Historial NodalH process is used intead of the NonHistorical one? 

https://github.com/KratosMultiphysics/Kratos/blob/c030f918a296b0b87c6a0c33bf823060791c2f4e/applications/FluidDynamicsApplication/custom_processes/distance_modification_process.cpp#L140-L146

Regards!

**Comment by rubenzorrilla** [comment]
Concerning the variables request, we can create a list of double and array variables. 

On the other hand, after checking the compute nodal H process, I did realize that there is a template variable to set the "historicity". When we implemented the distance modification process this wasn't available. However, after going through the code, I dare say that the non-historical value is not MPI compatible since the synchronization in there can only be done when using the historical variant, since there is no a non-historical version of the synchronize to min in the MPI communicator.

**Comment by philbucher** [comment]
> I dare say that the non-historical value is not MPI compatible since the synchronization in there can only be done when using the historical variant, since there is no a non-historical version of the synchronize to min in the MPI communicator.

I don't fully understand the requirements, but there is a version for the synchronization of non-hist nodal variables

**Comment by rubenzorrilla** [comment]
There is, but there is no SinchronizeToMin (or I didn't find it).

**Comment by jcotela** [comment]
If the non-historical SynchronizeToMin is needed, it should be straightforward to add in (or after) #4745.

**Comment by rubenzorrilla** [comment]
I'd take the chance to add it.
