### ISSUE TITLE
[Core] ReplaceElementsAndConditions replace aaaaall entities

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#4862]
Hi! We found that replace elements and conditions process changes the elements (and conditions) type in all the elements in the model part, i.e. it finds the very root main model part and change everything there. I would expect that it changed only the elements of the given model part. If you have a model part that contains two sub-model parts ( e.g. mold and part ;) ) you want to have different elements and conditions in each of them.

What do you think @loumalouomega @philbucher ? Is there any strong reason for this? Maybe the two options could be maintained using a local flag or something similar.

@KratosMultiphysics/altair

**Comment by philbucher** [comment]
I started doing this at some point for @inigolcanalejo but then stoped bcs he found a different solution for his problem 
There were some technical difficulties, let me remember and then get back to you later

**Comment by inigolcanalejo** [comment]
Hi @ddemidov, I am also interested in this feature and was trying to implement something like this. Let me explain.

The way it is right now (as you describe): the replace elements and conditions process finds the rootmodelpart of the submodelpart given as an argument and replaces the name of all the elements and conditions in the rootmodelpart and all the submodelparts belonging to the rootmodelpart, leaving the ids, geometry and properties of the element as they were.

The way I would like to have it (and I think you too): one gives a submodelpart and only thename of the elements contained in this submodelpart are replaced in this submodelpart, in the rootmodelpart and the submodelparts that contain these elements. Is this what you want? 

Replacing the name of the elements in the given submodelpart is easy, but the problem comes at the time of replacing the name of only the elements of the given submodelpart in the rootmodelpart and other submodelparts. What I implemented (but might be very expensive for a large number of elements) is a loop over elements like the one in replace_elements_and_conditions_process.cpp where it checks for each element of the rootmodelpart and submodelparts whether it is contained in the given submodelpart. This check involves for each element a loop over all the elements of the given submodelpart.

Another option proposed by @philbucher that was working well was to: instead of just replacing the element name and leave the ids, geometry and properties as they were, changing both the element name and the ids. This allows to create new elements in the rootmodelpart and mark the old ones to be replaced TO_ERASE. The disadvantage of this approach is that if the elements were contained in other submodelparts they will be erased and not substituted.

Or you really want the elements to be replaced ONLY in the given submodelpart? I don't know your application, but changing the elements only in the given submodelpart might lead to some problems because you will be having the same element in different modelparts with a different name.

**Comment by inigolcanalejo** [comment]
pinging @loumalouomega and @RiccardoRossi

**Comment by philbucher** [comment]
In a nutshell: The problem is when an element is part of SubModelpart A AND B. Now you replace only submodelpart A, but you also have to replace all the elements that are in A AND B also in B, otherwise your Modelpart is broken.

Ofc this can be done but requires more attention from the user

**Comment by loumalouomega** [comment]
Well, I can add a local flag, to replace only in one submodelpart with a new Id, as @philbucher says if I replace in the submodelpart but not in the root and preserves the same Id the model part structure is broken

**Comment by ddiezrod** [comment]
You got it right @inigolcanalejo , we want those elements to be changed everywhere. I personally prefer option 1 even if it will be much slower. We had something similar implemeneted in our side and I think the cost was acceptable.

**Comment by inigolcanalejo** [comment]
I would also go for option 1 although I need to see how expensive it is for our application in 3D when the number of elements in the rootmodelpart is larger than around 5 million.

**Comment by RiccardoRossi** [comment]
it is not only a question of cost...

an element with id say 1 belongs to the root.

now you change it in a submodelpart. 1 also belongs to its father. what then?

**Comment by philbucher** [comment]
1 also has to be replaced in the father then ...

I would say that first one replaces the entities in a SubModelPart, then goes up the hierarchy and replaces the corresponding entities. This is done until root. Afterwards the change also has to be done top-to-bottom to update ALL submodelparts

**Comment by pooyan-dadvand** [comment]
I think the natural one (and for me the only option) is the option 1. IMO it is not natural what we have now.
The implementation is not difficult. 
1. Getting the ids[] from the given model part
2. Go to the root and only change ones in ids[]
3. Go down in the hierarchy and cahnging ones with in ids[]

**Comment by inigolcanalejo** [comment]
I agree with @pooyan-dadvand that this is the best approach.

**Comment by RiccardoRossi** [comment]
ok i am not against

**Comment by rubenzorrilla** [comment]
Makes sense for me as well. It ensures that what happens to the son model part is always consistent with the root one.
