### ISSUE TITLE
About the Normal definition of surfaces loads

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#4933]
Dear Kratos community,

During these days I've been implementing in my App an online (during calculation) generation of pressure loads (with tetrahedrons) along time and I have some concerns that may be interesting for the rest of users.
The main problem that I had is to properly define the order of the nodes in order to create the pressure load as:
```
    const auto& r_pressure_condition = rSubModelPart.CreateNewCondition(
                                        "SurfaceLoadCondition3D3N",
                                        rMaximumConditionId,
                                        condition_nodes_id,
                                        pProperties, 0);
```
And I've seen that the order of the nodes inside the Geometry is not the local order (i,j,k,l) so it's not possible (or I don´t know how to) to define a correct order of the nodes (`condition_nodes_id`) in order to define consistently the normal of that load.

In the end I've solved this issue by iterating... This is a consistent way of defining the local_id but, as can be seen, some of them do not follow the **right hand rule**:

```
    const IndexType id_1 = (NonWetLocalIdNode == 0) ? 0 : (NonWetLocalIdNode == 1) ? 1 : (NonWetLocalIdNode == 2) ? 2 : 3;
    const IndexType id_2 = (NonWetLocalIdNode == 0) ? 3 : (NonWetLocalIdNode == 1) ? 0 : (NonWetLocalIdNode == 2) ? 3 : 0;
    const IndexType id_3 = (NonWetLocalIdNode == 0) ? 2 : (NonWetLocalIdNode == 1) ? 2 : (NonWetLocalIdNode == 2) ? 1 : 1;
    const IndexType id_4 = (NonWetLocalIdNode == 0) ? 1 : (NonWetLocalIdNode == 1) ? 3 : (NonWetLocalIdNode == 2) ? 0 : 2;
```

![Sin título](https://user-images.githubusercontent.com/26402605/58169444-08211a00-7c91-11e9-8dc6-c43f42f9b75d.png)

I know that @rubenzorrilla has something to say about this.

Thank you

**Comment by rubenzorrilla** [comment]
Going one step further, the debate is on the consistent definition of the normal orientation in Kratos. In fluids this is more or less easy (for simplex elements), since we can reorient the normals to always point outside the fluid volume. For structures the problem arises when dealing with shells or membrane structures (or combinations of these with solid elements), since the correct orientation of the normal should be provided by the user. @RiccardoRossi  and me had a conversation about this a few days ago.

At this point, I have no clue on how to solve this, but it would eventually solve the problem @AlejandroCornejo  is pointing out.

**Comment by RiccardoRossi** [comment]
I am not 100% sure we are discussing the same stuff, nevertheless the "GenerateFaces" method should give you back a list of faces oriented to that the normal points otherwise. That function should be defined consistently for all the geometries.

what is NOT available (nor trivial to do) is a function geometry.SwapNormal() which would be needed to ensure the correct orientation
