### ISSUE TITLE
[FluidDynamics] Problems with the embedded distance modification

### ISSUE THREAD

**Issue by dagmawibekel** [KratosMultiphysics/Kratos#5041]
Hello @KratosMultiphysics/fluid-dynamics,  
i am trying to compute fluid flows using the embedded approach. For coarse background meshes this works pretty fine. However, refining the background mesh leads to crashing simulation, because the condition number is too high: 
  Error:  Condition number of the matrix is too high!, cond_number = 4.72029e+31. 

The "apply_distance_modification_process" is supposed to move intersection between the embedded structure and the background mesh if they are too close to a node of the background mesh. However, any value for the "distance_threshold" can be chosen and it still will give me the same error concerning the condition number. 
Has anyone else working with the embedded solver experienced a similar behavior and knows how to overcome this problem?

Best regards, 
Dagmawi

**Comment by marcnunezc** [comment]
Hi @dagmawibekel !

Im not working in the FluidDynApp but I'm using the embedded tools as well.

I had a similiar issue that had to do with the default tolerance that is currenly defined in the CalculateDistanceToSkinProcess. Have you checked how the 0-level looks in the cases that are failing?

Here is an example of what I was experiencing:

![image](https://user-images.githubusercontent.com/32136457/58949751-71268880-878d-11e9-9488-ea816a1b566f.png)

The white line is the 0-level, which is doing something weird. Since one of the nodes has a very high value, the area of this element is very small. Here the node with value 0.000131331 should be negative.

Can you check if this is happening in your problem as well? The issue here is that the tolerance in the ray-casting process is not low enough.

You can redefine the tolerance adding it in the constructor of the process:

```
tolerance =  1e-9
KratosMultiphysics.CalculateDistanceToSkinProcess2D(self.main_model_part, self.skin_model_part, tolerance).Execute()
```

[The default one is 1e-8](https://github.com/KratosMultiphysics/Kratos/blob/e9d74510d276368e3e29191511e0e411dcec4295/kratos/processes/calculate_distance_to_skin_process.h#L201)

**Comment by RiccardoRossi** [comment]
cc-ing @rubenzorrilla

**Comment by rubenzorrilla** [comment]
Hi @dagmawibekel ,

What @marcnunezc is pointing out was a problem of tolerances in the level set function computation. This was a consequence of the default distance values modification that we introduced a few weeks ago. 
Having this in mind, can you update to the last master version? (in case you are out of date). If you are using quite refined meshes, you might have a similar situation to the one @marcnunezc used to have. If this is the problem, it is solved by changing the raycasting tolerance in the distance computation algorithm, since it is considered as a non ill-conditioned cut by the distance modification algorithm.

**Comment by dagmawibekel** [comment]
Thanks for the help. Updating to the latest master version solved my problem!
Best regards

**Comment by rubenzorrilla** [comment]
> Thanks for the help. Updating to the latest master version solved my problem!
> Best regards

:sunglasses:
