### ISSUE TITLE
There's no way of accessing the INITIAL length, area or volume of the geometries

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#5264]
Dear colleagues,

Regarding the calculation of the characteristic length for the Structural Mechanics App I've seen that there's no way of computing the original length, area or volume of a certain geometry. I think that this is a limitation so I propose to add some methods like
```
InitialLength()
InitialArea()
InitialVolume()
```
in which all the coordinates will be the initial ones (`.X0()`).

If you agree I can implement it myself.

Thank you!

**Comment by loumalouomega** [comment]
The simplest way I think is to add to the point the InitialCoordinates method, returning a warning and the current coordinates. Then override this method on the node. Then adding those methods to the geometries

**Comment by loumalouomega** [comment]
See #5266

**Comment by philbucher** [comment]
I agree that those methods can be useful, however so far afaik there was no need for them 
Hence I am not sure if we should duplicate the interface of the Geometry just for this
Another option would be to save those variables in the initial state

**Comment by RiccardoRossi** [comment]
one simple way is to create when needed a geometry of points initialized
with the original coordinates.

that woukd allow you to compute what you need. hiwever it surely has an
overhead

**Comment by loumalouomega** [comment]
> one simple way is to create when needed a geometry of points initialized with the original coordinates. that woukd allow you to compute what you need. hiwever it surely has an overhead

That's even more expensive, you need to create a full geometry (and @AlejandroCornejo wants to use it on the CL, so in each GP, several times during Nl iteration in the NL laws)

**Comment by jcotela** [comment]
For me the main concern is that the geometry as is now has no concept of initial configuration (the node is the one that does), so I see this as a major change of scope of the geometry class. Who would store the initial position? Relying on the nodes having it is not possible, since the geometry can be made of points. Should we also store this data in the geometry?

I think that the suggestion of @RiccardoRossi is a good practical compromise in this case. A `Point` geometry should have significantly less overhead than a `Node` one. If creation/destruction is a concern, I would recommend storing this extra geometry in the element that needs it.

**Comment by loumalouomega** [comment]
I will leave the decision to @AlejandroCornejo. But I think we need further discussion @KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee
