### ISSUE TITLE
[Metis] How to create tests for partitioning

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#5404]
I was thinking of creating some basic tests for the MetisApp, but I don't know how :/

I am not sure what to test for. If I write a test that explicitly checks if a certain node/element goes to a certain partition, this might fail with different versions of Metis, since I could imagine that if they change/improve the algorithm the partitioning pattern could also change ...?

Any ideas @jcotela @roigcarlo @pooyan-dadvand @RiccardoRossi ?

**Comment by pooyan-dadvand** [comment]
I would try with some meshes that we know it should go in the same way. For example a long bar with no node in the symmetry line. So we can predict that all the metis version would divide it correctly. 

Another option is to check if all partitions have more or less the same number of nodes or elements instead of checking which nodes are in which partition. Finally the load balance is important not the position of the tests.
