### ISSUE TITLE
[Fluid] Show warning about too high CFL when solver does not converge

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#5534]
Talking with @RiccardoRossi we thought that using too high CFL numbers is a common error by unexperienced users of CFD. 
I propose to compute the CFL and throw a warning when the solver is not able to converge, showing the user the possibility to decrease the time step and proposing a correct estimation.
@rubenzorrilla @jcotela

**Comment by rubenzorrilla** [comment]
Well, I think that for this purpose we have the automatic DT estimation utility, which automatically sets the time step in accordance to the maximum local CFL. 

In any case, maybe is a good idea to throw a warning with the maximum CFL if the NR doesn't converge.

**Comment by mpentek** [comment]
In my experience with Kratos, you can run CFD simulations which will converge without a problem with local CFL of at least 10-15 (maybe even a lot higher in some cases). The exact way how CFD in 3D is measured I think is slightly different from code to code and different formulations will be less and more sensitive to high CFL. I think that at least the fractional step using the amgcl solver is very robust. I had convergence problems mostly due to problems with the mesh or conflicting boundary conditions on certain edges. A CFL calculation utility should be available, but i am not sure that connecting a warning message with a non-converging solution is the best thing. I would imply a causation which should always hold, but in my experience is not always the case.

The other question is, would this imply calculating CFL at each timestep? Or only when the solution does not converge?

In my opinion, those who do not know how to set up the timestep properly, should use the estimate dt utility and set a maximum cfl in the project parameters. For others, getting CFL evaluation should be an option. See some refactoring in #5499. I mean, when the simulation does not converge, the user anyway has to check for modeling errors and sometimes do debugging. I do not think it would be the best idea to link a non-convergence message with a CFL number message which may or may not be causing it.

**Comment by mpentek** [comment]
I am also initiating a discussion #5516 which would include this thread partially.

**Comment by rubenzorrilla** [comment]
> 
> In my opinion, those who do not know how to set up the timestep properly, should use the estimate dt utility and set a maximum cfl in the project parameters. For others, getting CFL evaluation should be an option. See some refactoring in #5499. I mean, when the simulation does not converge, the user anyway has to check for modeling errors and sometimes do debugging. I do not think it would be the best idea to link a non-convergence message with a CFL number message which may or may not be causing it.

After reading his post, I'd say I agree with @mpentek on this. The non-convergence in an implicit scheme could be not directly related to the CFL (indeed, it shouldn't be in theory...). Despite it is not bad idea to show it, it might generate even more confusion in non-expert users.

Having said this, I'd leave the implicit solvers as they are right now as the linear solver already throws a warning if it does not converge. 

However, we are working on some explicit fluid elements & strategies right now. For these, I think it completely makes sense to inform the user about the maximum CFL in case the solver do not converge.

Having said this, I'd close the discussion until the explicit solver is ready.  @maceligueta feel free to reopen the issue if you consider it necessary.
