### ISSUE TITLE
[Trilinos] AMGCL cmake options outdated?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#5562]
Hi @ddemidov 
I have a short question about the mpi amgcl solver in the TrilinosApp:
I am currently trying to clean up the app a bit and stumbled across the following code related to AMGCL:
https://github.com/KratosMultiphysics/Kratos/blob/a445ae992263553665e0fc0d4cc3d3e3b1468777/applications/TrilinosApplication/CMakeLists.txt#L19-L35

to me it seems like `TRILINOS_USE_AMGCL` and `AMGCL_INCLUDED` are no longer used, because now amgcl is always included right?
Also what abt Pastix in combination with amgcl, does this still work?

Could you please have a look? (not urgent)
Thanks a lot!

**Comment by ddemidov** [comment]
This part of cmake was contributed by @RiccardoRossi, so I am not sure how or if `TRILINOS_USE_AMGCL` is used.

AMGCL supports pastix as a direct solver at the coarsest level, so that part should still be relevant. But there is no option in Kratos to actually select pastix as direct solver here:

https://github.com/KratosMultiphysics/Kratos/blob/6fe4dc717ac9bb20ff56d6cb30eff915bd445e1a/kratos/linear_solvers/amgcl_solver.h#L149-L169

**Comment by RiccardoRossi** [comment]
If you select pastix from cmake than it is hard coded

**Comment by ddemidov** [comment]
> If you select pastix from cmake than it is hard coded

I think it *was* hard-coded in our subdomain deflation implementation, but that is no longer used. I don't see anything related to pastix in the current [TrilinosApplication/amgcl_mpi_solver_impl.cpp](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/TrilinosApplication/amgcl_mpi_solver_impl.cpp).

**Comment by RiccardoRossi** [comment]
good then, we can remove both options and make amgcl compilation on always

**Comment by ddemidov** [comment]
Should I add it to #5556?

**Comment by RiccardoRossi** [comment]
i would keep the two separated (i already checked #5556 so i can approve it now)

**Comment by ddemidov** [comment]
#5573
