### ISSUE TITLE
Git patch number does not take any value when dowloaded as a package

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#56]
This is related with #12 

Since git allow people to download the source code as a tarball, the patch number obtained by CMake from the git command is not guaranteed if the command does not exists in the target machine ( which is already controlled ), or if such command is executed in a non-git directory.

For example the output of the nightly builds since they work with git is 
```
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.0.0-
```

**Comment by loumalouomega** [comment]
Something like gitwatch may help?

**Comment by roigcarlo** [comment]
@loumalouomega Looks nice, I'll take a look. Anyway I may have described just the opposite of what is happening. @RiccardoRossi realted to #12 it looks like we DO have git installed there, which should not have. But we probably still want to address this particular problem.

I updated the issue description so is more clear

**Comment by ddemidov** [comment]
One way to deal with this would be to distribute a text file containing the version number. When git is available, version should be generated from git. Otherwise, the version is read from the file.

For example, in amgcl I have `git_version.py` script that does exactly this:
https://github.com/ddemidov/amgcl/blob/master/git_version.py

The script is used in [`setup.py`](https://github.com/ddemidov/amgcl/blob/master/setup.py#L93) so it is called twice: first, to create the package (that's when the `RELEASE-VERSION` file is created and is [included into the package](https://github.com/ddemidov/amgcl/blob/master/MANIFEST.in#L2)) and second, when the package is being installed (that's when the `RELEASE-VERSION` file is used). I guess similar logic could be applied to non-python distribution. Note that `RELEASE-VERSION` itself is not tracked with git.

**Comment by roigcarlo** [comment]
Thx for pointing that out @ddemidov. Actually we are using something quite similar based on what you suggested in the test repo.

But for what I have seen in the scripts we are doing some things differently. Since we don't have any commit tagged yet, we are assigning the MAJOR.MINOR.PATCH manually and using git just to obtain the hash (`git rev-parse` vs `git describe`) . The rest of the information is in the CMake.
Another difference is that we have the need to generate a file `kratos_version.h` with that number. 

 But we have no "default" option if everything fails. I see several situations here:

| Has Git?        | Source is under version control?           | result  |
| ------------- |:-------------:| -----:|
| Yes     | Yes | 5.0.0-Hash |
| **Yes**      | **No**     |  **5.0.0-** |
| No | Yes      |  5.0.0-0 |
| No | No      |   5.0.0-0 |
 
So the problem comes when we do have git, but the code is not in a folder under version control.

My suggestion would be: 

* Make a small patch so that particular case defaults to 5.0.0-0 as well.

* Once we tag the first version in git, use `git describe` to obtain the version and generate default `kratos_version.h` for that particular tag which would be the base ( since it has to exists anyway). If any of these is possible ( which should never happen ) we default to 5.0.0-0 ( or whatever major is active at that moment) 

What do you thing? I would like to know you opinion as well @RiccardoRossi and @pooyan-dadvand.

**Comment by ddemidov** [comment]
I think we can group all of these situations into two cases: either you can use `git rev-parse` to get git hash, or you can not (either git is not present, or the folder is not under version control). In the first case you can directly ask `git` for the hash, and in the second case you can read `RELEASE-VERSION` file that was packaged together with the sources as part of the packaging process. Then you can always ask your users for the hash, and immediately know what commit they are on. Any default is much less useful.

Generation of `kratos_version.h` can be done along the same lines. May be it can even be used instead of `RELEASE-VERSION` file.

**Comment by loumalouomega** [comment]
@roigcarlo I see you added to the CmakeLists.txt:

~~~
configure_file(
  "${PROJECT_SOURCE_DIR}/kratos_version.h.in"
  "${PROJECT_SOURCE_DIR}/kratos/includes/kratos_version.h"
)
~~~

Is the issue solved?

**Comment by roigcarlo** [comment]
No. I had no time to finish this yet sorry.
We probably should mark this as low priority or something. In its current state this is only a cosmetic problem.

**Comment by roigcarlo** [comment]
I am closing this since the package case is no longer a problem as it was solved some time ago (only if one downloads the code as a zip directly from github this keeps being an issue). We can tacke that case in another separated issue.
