### ISSUE TITLE
Error if linear solver does not converge

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#5620]
Currently the linear solvers print a warning if they do not converge (see #2284)

```
AMGCL Linear Solver: Non converged linear solution. [0.00727915 > 1e-07]
```

This is already helpful however it easily gets unnoticed if this is one of many lines in the output.

I propose to raise an error if the solver did not converge.
My personal opinion is that this behaviour should be the default, and only be deactivated by experienced users.
I don't see a good reason why a non converged solution should be accepted by default. If one knows that a larger tolerance is acceptable to continue the simulation, that can easily be set in the solver settings. 

PS: I think i opened a similar discussion some time ago, but could not find it anymore.

@KratosMultiphysics/technical-committee

**Comment by AndreasWinterstein** [comment]
I think the warning is enough. The user should be able to judge about his results. It also happens, for example in our FSI simulations, that the linear solver does not converge only for a few out of thousands of time steps, but the solution is fully acceptable. Additionally, if you are computing on cluster systems a job you submitted might fail only because of this error. You would have to restart your job, send it again to the queue. Then you might have to wait until it starts again (this can take up to one week, depending on the cluster usage).

**Comment by philbucher** [comment]
I also think that it should only be a warning
**Remember that a non-converged solution is not a wrong solution!**

In my cases sometimes a timestep or an iteration does not converge, out of thousands, so I can live very well with this
As you suggested I could adjust the tolerance (i.e. decrease it to always converge) but that would mean that for all the other times when it could converge to a smaller tolerance I am not enforcing it and hence decreasing the overall convergence of the simulation

Also in other cases this cannot be done, imagine an adaptive (e.g. with remeshing or decreasing the timestep) analysis. There you would check for convergence, if you don't achieve it then you do sth (e.g. remesh in certain areas) to improve the convergence. 

What we could think abt is a setting to have this optional. Same probably for the solvers (in py and C++) but I strongly suggest to leave the default with a warning not an error. Again, a non-converged solution does not necessarily mean that it is wrong!

**Comment by rubenzorrilla** [comment]
I also fully agree with  @AndreasWinterstein  and @philbucher . Aside of what have been commented in here, formulations that suffer from matrix ill-conditioning are prone not converge during the first non-linear iterations.

I understand that for non experienced users, this could lead to a wrong interpretation of the obtained results if the solution is far from the expected one.

Having said this, I think it would be more valuable if we improve our screen info while running than making this optional. There are some open discussions about this (#5080).

**Comment by rubenzorrilla** [comment]
I'd also like to add that throwing an error should be the last option. You can use some strategies, which are also used in well-known commercial codes, to try to reach convergence in case it is not found (e.g. go back to the previous time step, divide the Dt by a factor and solve the problem again),

**Comment by armingeiser** [comment]
I was expecting these answers. 

You're exactly what i would consider as expert users:
If you know that you can accept non converged solutions in a long simulation on a cluster with long queue times - it is easy for you to allow them if such a setting would exist. You know what you are doing.

Adaptive strategies are another perfect example of a more sophisticated "user" of a linear solver that accepts a non converged solution and knows how to handle it. 

I understand your reasoning even if i do not agree that this should be the default for everyone.

As @rubenzorrilla mentioned, an improved logging could also help. E.g. a final warning at the end of a Kratos run that states if or how many warnings have been encountered would be a good thing. 

```
WARNING: Kratos run terminated with 5 warnings!
```
or 
```
INFO: Kratos run terminated without warnings!
```

This should be possible to do in the destructor of the Logger i guess. 
A more prominent highlighting of Warnings to distinguish them from Infos would also be a big help. e.g. prepending `WARNING` to the actual message, or changing the color of the message.

Or a separate log file that only contains warnings and only appears if warnings have occurred.

If any of these options is already possible and i missed it, it would be great if you could point me to this. 

My point is that it can not be expected that everyone has to scan their complete log (that may contain thousands of lines) for arbitrary warning messages that are not highlighted in some way.

**Comment by rubenzorrilla** [comment]
I like the idea of having a kind of "short final report" of the simulation.  Print the warnings (and eventually the errors) in a separated file could be also a good idea. However, we need to take into consideration that right now we have lots of deprecation warnings that could hide the meaningful convergence information. Therefore, I wouldn't introduce the warnings output file until we have get rid of all the deprecated stuff.

I remember that @loumalouomega had a prominent highlighting (the "fancy output") in his application. However, he had some technical difficulties to generalize it for the rest of apps. @AlejandroCornejo is also working in this direction.

**Comment by RiccardoRossi** [comment]
also, we could optionally throw an error on failure.

this means that the default bejaviour remains as today, and one may ask to
be more strict

**Comment by mpentek** [comment]
@armingeiser there is a similar discussion with respect to error message, warning and generally informing the user more, for e.g. in case of FluidDynamicsApp #5534. From a different perspective, making everything fool proof and totally safe might also give the perception to a new user that a) it is ok to be less informed of what is going on because my software will save me and b) I will always get a result which (is good enough that) I can carry on with. I think this would be an inadequate message. Also, some cases, where one could connect a warning message to some non-convergence (like high CFL and convergence of the solver) could be the actual cause and effect or it could be not, so every now and then you would be implying that the solver is failing due to some effect (for e.g. CFL) whereas the actual problem might be lying elsewhere. Without a more in-depth analysis, which does require advanced knowledge as it should, this can and should not be generically handled.

In this sense I agree with @philbucher that, a non-converged solution does not necessarily mean that it is wrong. And in many cases, such as @AndreasWinterstein writes, automatically stopping a long and expensive simulation in such cases should definitely not be the way to go.

There have been quite some technical suggestions above, perhaps one could introduce some utilities and measures to monitor the "quality" of simulations during runtime, but that is very case and application dependent, of what exactly quality means and how to measure it. This leads back to the need of an "experienced user"...

**Comment by philbucher** [comment]
> My point is that it can not be expected that everyone has to scan their complete log (that may contain thousands of lines) for arbitrary warning messages that are not highlighted in some way.

@armingeiser this is EXACTLY what one has to do when using sth as complex as a finite element solver (esp if the results look weird)! If there are hundrets of WARNINGS then there is clearly sth wrong with the simulation!
Whoever wrote the code knew what they were doing and why in certain cases warning messages should be issued. If a user deliberately ignores them then this is not the codes fault but the one of the user.

I agree that there are some deprecation warnings which make the log harder to read, but it is not that many and we are constantly trying to remove them. 
Here I would propose a new logging level, then it would be very easy to filter or disable them

Regarding redirecting the output to a file, I think this is the intention/goal of Pooyan, but I am not sure if it is available yet. Also afaik it will be possible to filter by severity

Regarding the colors I have to say that I really like this idea (in fact the CoSimApp uses this already) but it is not that straight forward, because we need the option to easily disable/enable it due to the fact that not all terminals and also files cannot display them and would have the weird color-code characters everywhere

**Comment by armingeiser** [comment]
> @armingeiser this is EXACTLY what one has to do when using sth as complex as a finite element solver

Solving the linear equation system is as much standard as it can get. What if the non converged results do not look strange? What if a non converged solution in one of the early steps results in a different solution path of your complex scenario that may still look reasonable? What makes it complex is the context.
Why should something as simple as a linear static analysis require to constantly read through the log? 

I see your points but your complex transient FSI scenarios are not the only place an iterative solver is used. For me an iterative solver replaces a direct solver and it should give the same (within a tolerance) results. if it can not - it failed.

We can close the discussion about the the iterative solver throwing an error on failure, as i see all of you are against it. An optional error as Riccardo suggested can be added, i will do that at some point. Would it make sense for your applications if that error would be related to another "tolerance" level? E.g.
* tol < 1e-7 success 
* 1e-7 < tol < 1e-4 warning 
* tol > 1e-4 error? 

> DeprecationWarning: Here I would propose a new logging level, then it would be very easy to filter or disable them

This makes sense. 

If the coloring is troublesome and not easily portable it might not be the best solution to highlight the different levels. (even if i would prefer it).
Alternatively what do you say about prepending "WARNING: " to every warning message?

```cpp
#define KRATOS_WARNING(label) Logger(label) << KRATOS_CODE_LOCATION << Logger::Severity::WARNING << "WARNING: "
```

like this at least a simple search through the log will show all warnings.

**Comment by pooyan-dadvand** [comment]
> Regarding redirecting the output to a file, I think this is the intention/goal of Pooyan, but I am not sure if it is available yet. Also afaik it will be possible to filter by severity

This is the intention and can be done now by adding a new output (the normal `LoggerOutput`) and setting its severity to warning to filters the message and writes it to a warning file. 

> Alternatively what do you say about prepending "WARNING: " to every warning message?

This should be done at the output level and not in the message itself. It would be a good idea to add this to the `LoggerOutput`

**Comment by armingeiser** [comment]
I am closing this, since the decision was clear to not throw an error on non converged solutions of linear solvers. Also there is a PR  #5700 for highlighting warnings by prepending `[WARNING]` in the `LoggerOutput` as @pooyan-dadvand suggested.

Thanks to all of you for the input/discussion.
