### ISSUE TITLE
Kratos MPM example

### ISSUE THREAD

**Issue by vjagodnik** [KratosMultiphysics/Kratos#5691]
Is there any example or tutorial on how to use material point module of Kratos? I am constantly getting errors.
I am using Kratos via GiD.
Best regards

**Comment by philbucher** [comment]
@KratosMultiphysics/mpm

**Comment by VeronikaSinger** [comment]
Hi 
here you can find some more information https://github.com/KratosMultiphysics/Kratos/tree/master/applications/ParticleMechanicsApplication

**Comment by vjagodnik** [comment]
Thank you for the link. Somehow I missed it.
Do you know by any chance if this is available in version 6, since it is the only one that can be used on macos? On windows i could select the MPM option, but on mac, i cannot (screenshot from my mac computer).
<img width="608" alt="Screenshot 2019-10-07 at 09 18 16" src="https://user-images.githubusercontent.com/36809874/66292014-80584700-e8e3-11e9-8a59-824db7bb9db9.png">

I will check the link you shared and hope I will find all necessary information.
Thank you once again 
With kind regard

**Comment by VeronikaSinger** [comment]
I am currently working with the master branch of Kratos and I use Gid13 or Gid14 for windows and linux. 
But I think that at least your Gid Interface is too old, as you cannot select MPM.

**Comment by vjagodnik** [comment]
I think that the Kratos version for mac is old. 
I am using GiD 13.1.10d. I could not start version 13.1.11d on mac for some reason. I have tried to find a solution on GiD forum [https://www.gidhome.com/forum/viewtopic.php?p=10736#p10736](url)

**Comment by bodhinandach** [comment]
I never tried to run in Mac @vjagodnik. But I think this should work in windows or linux. Maybe @jginternational can answer?

**Comment by jginternational** [comment]
Hi all.

There's a couple of things here:
- GiD latest macOS version was released last week, you can find it [here](https://www.gidhome.com/download/developer-versions/mac-os-x/)

- The latest Kratos released version for mac was 6.0.0, wich is the one you are using. That version has no MPM application. In order to use MPM you should use [Kratos 7.0.2](https://github.com/KratosMultiphysics/GiDInterface/releases/tag/Release-7.0.2) or the [master branch of the interface repository](https://github.com/KratosMultiphysics/GiDInterface).

Both solutions (7.0.2 and master branch) will require from your part an effort to [compile Kratos for macOs](https://github.com/KratosMultiphysics/Kratos/wiki/MacOS-Install), Maybe @roigcarlo can help with that

@bodhinandach and I were working on an example for the MPM GUI but it's a bit stacked

**Comment by vjagodnik** [comment]
Dear @jginternational,
Thank you for the detailed information.
* I had some issues yesterday with GiD 13. Under that circumstance i found out that there is a new developer version of GiD for mac. However, unfortunately i possess only the licence for version 13. Maybe i will find a way to get a licence upgrade. 
* After several try and errors, and after reading the link @VeronikaSinger replied earlier, i figured that it won't be that easy to use MPM with Kratos under mac (version 6.0.0). 

So, if I understood correctly, if Kratos is compiled I should be able to use it, by that I mean use the MPM module? 
Still, I will not be able to use compiled Kratos 7.0.2 via GiD?

Thank you all

**Comment by philbucher** [comment]
what is the status of this?

**Comment by vjagodnik** [comment]
No success. On macOS, I can only use Kratos 6.0 one GiD.
With kind regards

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
