### ISSUE TITLE
[ReadMaterials] Should submodelparts be able to have their own properties?

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#5782]
I have found that ReadMaterialsUtility throws an error if properties are assigned to both a child model part and its parent. I think that this could be allowed in some sittuations. 

For example, I think you might want to have a main model part with a property and then have an inlet model part that contains only conditions with a different property (with for example its own Heat Transfer Coefficient). Of course one solution could be to have the inlet and the rest of the main model part in the same level (so inlet is no longer a child of main), however that would be quite painful for us, as we would need to change all our input structure in @KratosMultiphysics/altair .

An intermediate solution could be maybe to throw a warning instead of an error. What do you think? @philbucher @KratosMultiphysics/altair @loumalouomega @KratosMultiphysics/design-committee

**Comment by loumalouomega** [comment]
I do not remember the reason it currently does that, it was discussed at the moment. I am OK with teh warning. BTW, ping https://github.com/KratosMultiphysics/Kratos/pull/2919

**Comment by philbucher** [comment]
Aren't all properties that are added to a submodelpart also added to its parent?

**Comment by ddiezrod** [comment]
Yes, I think properties added to the submodelpart are also present in the parent model part. But each element has only the property you assigned to it.

**Comment by ddiezrod** [comment]
I probably didnt explain myself very well. What I mean is that the elements/conditions of the submodelpart could have a different property from the one assigned to the elements that are in the parent model part. I understand this is not optimal, as you are overriding properties, however I think a warning could be enough and would give us more time to find a good solution.

**Comment by philbucher** [comment]
so you want the following?
~~~
Parent
    - Prop 1
    - Prop 2
    - Elem1 => Prop1
    - Elem2 => Prop1
    - Elem3 => Prop2
Sub
    - Prop 2
    - Elem3 => Prop2
~~~

**Comment by ddiezrod** [comment]
Thats correct, I am not sure if Prop 1 is also in ModelPart "Sub" but that would irrevelant anyway.

**Comment by philbucher** [comment]
But this already works. You can ofc assign different props to different Elements

**Comment by ddiezrod** [comment]
Not if one of them is a submodelpart of the other. You get this:
![image](https://user-images.githubusercontent.com/25667299/66843886-ae85f880-ef6d-11e9-9d25-4a36ecdc3622.png)

**Comment by philbucher** [comment]
ah now I get it :)
One sec, I will explain

**Comment by philbucher** [comment]
the problem is that in your json you define materials for "main", but you also define materials for "main.inlet"
The materials are always assigned to all elements or conditions in the modelpart that was given in the input. 
If you define materials for a modelpart twice, then you might overdefine it!
If you first assign "main.inlet" and then "main", then the first assignment doesn't make sense.

Looking at it know I see that the other way round would be valid, considering the overhead for assigning twice on the same elements.
I.e. first assigning on "main" and then on "main.inlet" would be a valid usecase, but I would still issue a warning telling the user abt the multiple assignment

If you want you can change it, or I can do it myself, which would take a few days

**Comment by ddiezrod** [comment]
Thats also my exact point. Thats why I think a warning is the best solution, I will create the MR with the change

**Comment by philbucher** [comment]
perfect, thx
