### ISSUE TITLE
Fixed/changing position of the inlet in a monolithic 2-phase solver

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#5792]
Dear colleagues,

it appears that the position of the inlet in the monolithic two-phase solver is fixed.
Moreover, there exists a non-zero transition radius within which the distance function of the level set is not updated.
This precludes the use of the solver for generating waves, because for a wave generator the inlet should permit variable heights.

So, there probably should be an ApplyWaveInlet process that permits variable height of the inlet. In terms of the formulation, is this going to cause any problem?

Kind regards

**Comment by rubenzorrilla** [comment]
Rather than creating a new inlet process, I'd enhance the current two fluids inlet process. Maybe adding a `update_according_to_level_set` could do the job.

At the end, it should be as simple as updating at each time step which are the nodes belonging to each one of the internal inlet processes. @playpaolo am I wrong?

**Comment by philbucher** [comment]
is this still active?

**Comment by playpaolo** [comment]
We can shut it down.
