### ISSUE TITLE
ModelPart.Elements().clear() does not free system memory.

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#605]
I don't know if it is the expected behaviour, but memory is not liberated when the elements are swapped or cleared in model part. If new elements are created with the same id range, no memory increase is experienced, but if the new elements Ids are larger than before, then the memory usage increases again.

This simple python script tests this behaviour step by step.

[test_create_and_delete_elements.py.zip](https://github.com/KratosMultiphysics/Kratos/files/1140404/test_create_and_delete_elements.py.zip)

Please can you give some feedback  @pooyan-dadvand @roigcarlo @maceligueta ...

Thank you in advance

**Comment by RiccardoRossi** [comment]
@josep-m-carbonell, i tried your test with valgrind massif, to obtain the following graph:

![image](https://user-images.githubusercontent.com/8059665/28104525-ce45a638-66db-11e7-8c76-9356985dfa6a.png)

there is some little memory increase in the bottom of the valleys, but i think this is due to massif doing sampling (that is, measuring only at some discrete time points, which might not coincide with the minimum of the valleys)

Your check is done in windows, right? Maybe the system allocator is caching the memory. Can u do the same test with the visual studio memory monitoring tool? (we can help if you need)

other than that, can u try replacing the clear by something like

     for elem in model_part.Elements:
         elem.Set(TO_ERASE)
     model_part.RemoveElementsFromAllLevels(TO_ERASE)

**Comment by RiccardoRossi** [comment]
just to add that if you happen to have submodelparts, the Remove... function is the way to go

**Comment by maceligueta** [comment]
Maybe some memory is still allocated after the clear(), it seems like capacity is not always set to 0 when the clear() is called...
http://www.cplusplus.com/reference/vector/vector/clear/

**Comment by josep-m-carbonell** [comment]
Thank you all, it seams that the system monitor is not a good reference for checking memory release. Valgrind massif is telling the correct behaviour, so there is no memory increment due to a bad clear of the vector.
