### ISSUE TITLE
Moving ROM B&S to Kratos Core

### ISSUE THREAD

**Issue by Rbravo555** [KratosMultiphysics/Kratos#6095]
In the light of the addition of Reduced Order Modelling capabilities into Kratos, there has been the discussion on WHERE TO PUT THE BUILDER AND SOLVER. 

Should an independent ROM Application be compiled, or can the builder and solver be put in the core?

I open this issue to discuss on that. For the time being, the RomApplication will contains its own B&S.

**Comment by philbucher** [comment]
for starters I would put it into an application
Once stable and generally usable I would be open to moving it to the core

I recommend adding suitable tests while developing, this will make a possible migration easier

**Comment by philbucher** [comment]
Also keep in mind that having it in the core right away will make your life much more difficult in terms of working on it, since changing things in the core takes longer

**Comment by RiccardoRossi** [comment]
@philbucher we were discussing together with @rubenzorrilla and we asked @Rbravo555 to open this issue exactly to discuss the topic.

The point is that that in order to use a standard solution strategy, essentially 2 things are needed:
1 - changing the builder and solver to use the ROM B&S
2 - do some extra operations in the reading phase.

Raul did all the initial testing deriving within his applications the different solvers. This is possible but not too convenient, since it implies deriving from each solver a ROM version.
@rubenzorrilla and myself believe that it would be quite convenient to add the B&S to the core, even when they are still in alpha shape (as they are now) since this would increase usability.

still of course this is open for discussion...

**Comment by philbucher** [comment]
I am reluctant (as usual :wink:) about adding things to the core that are not fully developed and useful for many.
I know that the current situation is annoying (also I had the same problems several times already)

However in the end I think the underlying problem lies a bit deeper, I think a clean solution would be to finally push / finish #2785 and #3185

what do you think?
(btw this is just my opinion, ofc I would not block)

**Comment by philbucher** [comment]
@Rbravo555 could you please describe the difference btw a regular simulation and a rom-simulation?
It would be good to know such that we can find a good solution for integrating it

I mean what riccardo described briefly, could you please explain in a bit more detail?
> The point is that that in order to use a standard solution strategy, essentially 2 things are needed:
1 - changing the builder and solver to use the ROM B&S
2 - do some extra operations in the reading phase.

**Comment by Rbravo555** [comment]
Sure,


A ROM simulation, as we have it conceived in Kratos, differs from a regular
one in the following:

One first imports to each node its corresponding “basis” (which was
obtained on a previous phase by running a series of regular simulations,
storing information and extracting the underlying structures). Then, during
the solving stage, Kratos will proceed in the same way as it would for a
regular simulation, with the only exception of the B&S. That is, the ROM
B&S will construct a dense and small system by projecting the algebraic
contribution of the elements and conditions, onto their corresponding
elemental basis.

That’s it. This B&S has been so far tested with static and dynamic thermal
and pseudo-static and dynamic structural examples.

**Comment by RiccardoRossi** [comment]
so @KratosMultiphysics/technical-committee decided to modify the 
"create_builder_and_solver" function in the base strategies (mechanical_strategy of the structural solver) to add something like

~~~py
if(builder_and_solvertype == "rom_builder_and_solver")
       import ROMApplication
       builder = ROMAppliction.ROMBuilder....
~~~

**Comment by philbucher** [comment]
Wait I thought we would add the builderAndSolver creation fct to https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/auxiliary_solver_utilities.py such that it can be used by different apps?

Or did I misunderstand?

**Comment by RiccardoRossi** [comment]
well, as i understood we should substitute it in 

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L412

now if we want to have a wrapper in the auxiliary_solver_utilities.py and use it at the line where i am pointing it is ok to me

**Comment by loumalouomega** [comment]
I remember that some auxiliar methods are defined in #4558...we should take a look in that in order to avoid conflicts...additionally the PR is almost one year old (aprovecho que el Pisuerga pasa por Valladolid...)

**Comment by roigcarlo** [comment]
@Rbravo555 this is on you ;-) (green light for the change)

**Comment by RiccardoRossi** [comment]
guess that since this is not merged yet, we should wait for the correction that allows structural elements to be reduced ( #6471 )

**Comment by roigcarlo** [comment]
I think this discussion if pretty outdated, please feel free to create a new one to keep discussing if we should merge the new rom app into the core.
