### ISSUE TITLE
[core] Error abs paths in time_based_ascii_file_writer_utility

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#6118]
Dear all,

@marcnunezc and I have faced the following issue.
We are currently running the process [ComputeBodyFittedDragProcess](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/python_scripts/compute_body_fitted_drag_process.py) and setting to [true](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/python_scripts/compute_drag_process.py#L34) the flag for saving a .dat at the end.

We have faced an issue trying to set an absolute path, and we attach a small example.

In the first scenario, we want to set the absolute path via "file_name", and as you can see when printing we just obtain "test.dat", which is relative path.

The second scenario sets the absolute path via "folder_name". As you can see, the resulting file name is "home/riccardo/folder/test.dat", which is relative path.

Is this the desired behavior?

Assigning the issue to the contributors of the core python class.
[test.zip](https://github.com/KratosMultiphysics/Kratos/files/3977646/test.zip)

**Comment by philbucher** [comment]
I don't know the expected behavior, but IMO it is time to unify this properly => #6120

**Comment by mpentek** [comment]
To be honest, I do not think that we tried it out with absolute path (nor was it the intention), as we generally work inside the project directory. In this sense I would also wait what the consensus will be with the unification. The relative path was originally as that it is how it is pretty much done by default, namely python creates files in the working directory. So it was mostly done inherently with that in mind. The reason we added a folder specifier (which even creates subfolders) to be able to better group output files (such as many point outputs from a line output) to be able to group-postprocess. Otherwise everything would have been created in the root of the working directory, which ends up being a mess pretty fast. 

In this sense, I do not consider it as an error, more a mis-labeling.  We could make clear that the folder name and file name refer to the relative path, the question is whether to add this note in the naming label (relative_folder_path), as a warning in the process, or somewhere else.
