### ISSUE TITLE
Eigensolver for 5.1 release

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#625]
Hi,

@loumalouomega asked about including the eigensolver. In case the eigensolver should be included in the release, here is a description of what the problem type would need:

Starting from the standard static analysis...

1) Modify the project parameters / problem type to set the following "solver_settings":

```
"solver_type"                        : "structural_mechanics_eigensolver",
"solution_type"                      : "Dynamic",
"analysis_type"                      : "Linear",
"eigensolver_settings":{
            "solver_type": "FEAST",
            "lambda_min": 0.0,
            "lambda_max": 1.0e7
        },
```

The user needs to be able to specify the minimum and maximum eigenvalues "lambda_min" and "lambda_max" in GiD.

2) Modify the MainKratos.py where gid_output.PrintOutput() is called by adding the lines

```
eigen_values = [ev for ev in main_model_part.ProcessInfo[EIGENVALUE_VECTOR]]
for ev, pos in zip(eigen_values, range(len(eigen_values))):
     main_model_part.ProcessInfo[TIME] = ev**0.5 / (2.0 * 3.141592653589793)
      EigenvectorToSolutionStepVariableTransferUtility().Transfer(main_model_part, pos, 0)  
      gid_output.PrintOutput() 
```

**Comment by pooyan-dadvand** [comment]
@roigcarlo Are you compiling the eigen solver (FEAST) in windows release?

**Comment by roigcarlo** [comment]
No. This was already discussed in #293, long story short, we need a FORTRAN compiler.

If we want that solver we will have to compile it ourselves and ship it along the release.
If it is required I can try to make a release using MinGW or find an implementation that does not include fortran code.

**Comment by pooyan-dadvand** [comment]
My idea was to provide the binaries for a certain version which is also used in the release.

**Comment by roigcarlo** [comment]
@pooyan-dadvand @msandre 
So, I've been fighting all weekend with this and the conclusion is: It will not be ready for the release.

Long story:
The library seems to compile OK with mingw in windows, both in 32 and 64 bits. In fact it is straightforward and, after the release, I'll upload a script to do it. The problem comes while trying to build something compatible with the MSVC compiler.

We have 2 options for that:

- The static version: I honestly do not know how to generate static libs compatible with MSVC and neither can find a tutorial that explains why is or not possible and how it works, so I went for the shared.

- The shared version. The trick here is to build a `.a.dll` and a `.dll`. We can use the former to generate a `.def` file ( which can be automatically in newer versions of cmake ) and use that `.deb` to generate the `.lib` file that VS needs. The problem is that particular library seems to use a name mangling not recognized by MSVC, resulting in a "corrupted library file" ( Also, not sure 100% that this is the cause of the problem ).
There should be a way to overcome this, but I am afraid I is my first time with a problem of this kind and I will need time to study it a bit further.

**Comment by pooyan-dadvand** [comment]
So long story short, it would be excluded in this release...

**Comment by msandre** [comment]
Thanks for trying. I'll close the issue then.

**Comment by pooyan-dadvand** [comment]
Sorry for inconveniences....
