### ISSUE TITLE
[Error] GeometryContainer compilation Clang 7.1.0

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#6270]
Compiling the current master branch with Clang 7.1.0 throws the next error 
`/home/rzorrilla/Kratos/kratos/containers/geometry_container.h:355:16: error: call to non-static member function without an object argument
        Flags::operator =(rOther);`

@tteschemacher it seems to be related to your last changes.

**Comment by loumalouomega** [comment]
As Travis is already using gcc, maybe the GitHub action should use clang in order to increase the number of checks

**Comment by philbucher** [comment]
> As Travis is already using gcc, maybe the GitHub action should use clang in order to increase the number of checks

once it works fully I would add both clang and gcc

**Comment by philbucher** [comment]
@rubenzorrilla +1 for using correct Lables  :D

**Comment by tteschemacher** [comment]
Guys,

I am sorry to tell you, but I might not be the bad guy, here. At least not to fix the CI error.

I fixed the bug which caused this error. #6274. Basically, it comes from a function which is not even being used and thus the other compilers don't recognize it.

I need to take off this label, because it is just for brilliant developments which are too advanced of being part of the master. :P
