### ISSUE TITLE
[Build] Creating a Kratos source script in the build process

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#6371]
Currently two paths have to be "manually" added to the environment, depending on the installation location of Kratos

https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md#adding-kratos-to-path

However these paths are known at build time, so it could be automated.

I am creating a source script for Kratos in my `configure.sh` script, using the variables from the build process (It can of course be improved to automate the `bin/Release` part as well).
```bash
# Create sourcing script
KRATOS_SOURCE_SCRIPT="${KRATOS_SOURCE}/bin/kratos.sh"
echo "export PYTHONPATH=${KRATOS_SOURCE}/bin/Release:\$PYTHONPATH" > $KRATOS_SOURCE_SCRIPT
echo "export LD_LIBRARY_PATH=${KRATOS_SOURCE}/bin/Release/libs:\$LD_LIBRARY_PATH"  >> $KRATOS_SOURCE_SCRIPT
```
All i have to do before running Kratos is sourcing this script
```bash
source bin/kratos.sh
```

I find quite useful, maybe it can help making the installation process easier for new Kratos users. 

Note: Don't know if his would be possible for Windows as well.

**Comment by oberbichler** [comment]
> Note: Don't know if his would be possible for Windows as well.

It is. Basically the same way.

**Comment by roigcarlo** [comment]
It is possible in win and also in linux.

If you are interested in the windows version, just `SET PATH=%PATH%;...`

Since changes in windows scripts are not scoped to the script itself but the session this is basically the same behavior as `echo "export"`.

That being said, this change cannot be in the default scripts because sadly is not a permanent one, it will expire as soon as you close the terminal and until you rerun the configure script again.

A lasting solution would be to export that into the windows path or append it to the .*rc file in linux, but in order to do it cleanly (without repeating entries) the script would need to parse the target system variable in order to find duplicates, modify it and then save it, which is far more complex than just export. 

In linux its even more an ordeal because we would need to identify which shell the user is using (bash is common but I use zsh for example, and many others exists)

#6778 Should remove the need of exporting the LD_LIBRARY_PATH in linux, but it still needs testing.
