### ISSUE TITLE
Release 8.0 Feature list

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#6495]
@KratosMultiphysics/all 

The next major release of Kratos is scheduled to be frozen at the beginning of May and we would invite all developers to add their list of features they want to be included in this release to the [milestone of release 8.0](https://github.com/KratosMultiphysics/Kratos/milestone/11).

Any comments or suggestions are also welcomed here.

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/all please remember to add your applications to this project: https://github.com/KratosMultiphysics/Kratos/projects/5 if you intend them to be in the release.

Also, please ensure the applications compile in the target OS you want them to be included. As for today, there are applications that do not compile.

**Comment by riccardotosi** [comment]
Dear all,

After speaking with @RiccardoRossi, we agree on commenting this on GitHub. If you think it is better to dedicate a separate issue for this, let me know and I will open it.

Under the ExaQUte project (which includes different teams), we are developing an Uncertainty Quantification python library. This library was firstly developed inside [MultilevelMonteCarloApplication](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/MultilevelMonteCarloApplication), and then part of it moved to this external repository.

Some relevant points regarding this Uncertainty Quantification library are the followings:
* It is naturally integrated with Kratos.
* It uses an external library called PyCOMPSs, but is not mandatory for running. A way for running without installing it is described in this [README](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MultilevelMonteCarloApplication/README.md). Basically, empty definitions of this library are used.
* The following python packages (which are not default python ones) are exploited by the library:
    * numpy,
    * scipy,
    * threadpoolctl: imported with "try except" mechanism, so not mandatory for running or if not installed in the machine.

Do you agree on including this library in the release, inside the MultilevelMonteCarlo application?

Please, feel free to share your thoughts on this.

**Comment by philbucher** [comment]
@riccardotosi are you proposing to add the `MultilevelMonteCarloApplication` to the release or to add an external library?

**Comment by riccardotosi** [comment]
To add an external library. Which, from my point of view, can be included in a sub-folder of `MultilevelMonteCarloApplication`.

**Comment by philbucher** [comment]
Ah you want to add the pycompass?
How large is it?

**Comment by riccardotosi** [comment]
No, I would like to add an Uncertainty Quantification library we have developed in an external repository.

This library is full python, and to run we can optionally use the pycompss library. Since we do not want to have the pycompss library added in Kratos, we have added "empty" definitions for running in [here](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/MultilevelMonteCarloApplication/python_scripts/exaqute).

So, to resume, we would like to add the Uncertainty Quantification library inside the MultilevelMonteCarlo application. This library is around 2 MB.

**Comment by philbucher** [comment]
Ok thx for the explanation, now I understand.
Do you only want to add it for the release or to master?

**Comment by riccardotosi** [comment]
Both, if possible. As far as I know, it is not possible to have in the release something that is not in the master.

**Comment by philbucher** [comment]
Ok
Well if you commit sth to the release branch only, then it won’t be in master

How about you make a PR for adding the library? Then it can be discussed there
Once it in master then it will automatically be in the release

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/all 

We are fixing a tentative date for the Release 8.0 **Freeze branch on the 27 of April** (Monday), and final **Release on the 29 of May** (Friday).

These periods are longer than usual, but due to the current situation we believe its important to have some more time of reaction in case anything happens. We that should give enough room to finish any feature that needs to be in the Release and test it according.

Understand please that dates may be subject to change depending on how the situation evolves.

**Comment by roigcarlo** [comment]
Closing since Release is done.
