### ISSUE TITLE
[dem] SearchFEMOperations is duplicated (continuum and discontinuum). Is it necessary?

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#6647]
We need to check if this duplication is needed or not and act accordingly.

**Comment by maceligueta** [comment]
We must consider that the continuum might have indentations with the FEM!

**Comment by rubenzorrilla** [comment]
@maceligueta is this active?

**Comment by maceligueta** [comment]
This was created as a reminder. As far as I remember, this was never addressed. Is there a different place on github where we can put pending tasks?

**Comment by rubenzorrilla** [comment]
Well, you can create a project and add a card for it, but I think it's not worth at all. If you're planning to address it I'd leave it open. If not, we can close it. Up to you :wink:

**Comment by ChengshunShang1996** [comment]
Hi @maceligueta, I have checked it. In my opinion, it is necessary to keep it.  Because we do not call  "continuum_sphere_strategy" and "(discontinuum) sphere_strategy" at the same time but we actually need to calculate the discontinuum force inside  of "continuum_sphere_strategy". So this function is not a duplication and we need it for particle-FEM contact detection in "continuum_sphere_strategy".

**Comment by maceligueta** [comment]
Apparently, this was addressed because I can no longer find SearchFEMOperations in ContinuumExplicitSolverStrategy. Good news! (but bad memory from my side). Closing.

**Comment by ChengshunShang1996** [comment]
Good news! I thought what you meant was we call it in ContinuumExplicitSolverStrategy.
