### ISSUE TITLE
Application dependencies

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#6765]
Hi all,

If I want to use some-other application's parts in another application, how should I proceed? For example, this can be either at python level, or c++ compiler level. I know application dependencies are not so good to have, so as the redundant codes. We cannot move all of them to the core as well.

One solution I see is, the way we do "trilinos_extension" for FluidDynamicsApplication. Is it the way to proceed? If it is going to be like "trilinos_extension", how should we do the python level linking? If we have python_scripts in "trilinos_extension" and we follow same procedure to install them, then the question is if some one tries to use parts from "trilinos_extension" without enabling "TrilinosApplication", then they won't see a meaningful error message. (This goes for c++ level as well)

**Comment by roigcarlo** [comment]
Maybe a little late but here is how it should look:

**Python Level:**
This is easy, if you have dependencies at python level it should be enough importing the application required in the `__init__.py` of your app.

Also you can add `kratos_add_dependency(${KRATOS_SOURCE_DIR}/applications/FooApplication)` to the cmake so it is enabled automatically if your application is enabled.

**C++ Level** 
Here you have to distinguish 2 cases:

- Header only functionalities:
If you inherit only functionalities that are in headers, you just have to add the include dir where those are located. For example: `include_directories( ${CMAKE_SOURCE_DIR}/applications/FooApplication )`

- Non header functionalities (implementations are in cpp)
Basically you have to do all the steps described previously, and also:

  1 - Make sure that you are linking your app against the dependency `target_link_libraries(KratosYourAppCore KratosFoorCore KratosCore)`

  2 - Endure that the header of the classes you will use are decorated with `KRATOS_API(YOUR_APP)`. Otherwise it won't work on windows.

  3 - If the class is templated, you need to instantiate it in the base clases with the arguments that you will use in the dependant app

**Mpi**
The case with the trilinos extensions are a little bit particular as the mpi library is need directly in the code, and that inclusion is quite intrusive. To prevent having an `#ifdef` every time that we compile (for example `#include "Epetra_MpiComm.h"` and all the blocks associated with it) the features that require are split into the extension. Its basically the same idea as the MPICore.

As for the problems with using the extensions without trilinos, essentially it is possible to do and compile, but other than importing the lib you will be unable to do anything useful unless you first import the TrilinosApplication as most of the processes solvers are there (Errors should look something like `"Unable to call TrilinosApplication.TrilinosBlockBuilderAndSolver() method not defined"` or similar.)

What could eventually be done is to derive extensions from other extensions, so if you have an application in which you need a trilinos extension because you are adding your own solvers, and for example that solver derives from a solver which is based in one that its defined in the extension of the main app. In that sense extensions are something more "horizontal" and derivations "vertical", and trilinos application goes on its own:

```
// Arrows represent dependencies, also omitting python level.

                             Trilinos Lib   ←  Trilinos Application
                                  ↑ 
   Kratos Core    ←        Kratos Mpi Core
       ↑                          ↑ 
   Main App       ←  Main App Trilinos Extension
       ↑                          ↑ (that may or may not exists)
   Derived App    ← Derived App Trilinios Extension
            
```

**Comment by philbucher** [comment]
I think this can be closed now as this has been adopted plenty of times now

please reopen if necessary
