### ISSUE TITLE
Calculate normals in MPI

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#6797]
Dear @KratosMultiphysics/technical-committee 

There is a problem with the `CalculateOnSimplex` function of the `normal_calculation_utilities.h`.

This function is overloaded for different set of cases, and in the documentation is well explain that some of them can give problems in MPI.

The recommended entry point:
```C++
    /// Calculates the area normal (vector oriented as the normal with a dimension proportional to the area).
    /** This is done on the base of the Conditions provided which should be
      * understood as the surface elements of the area of interest.
      * @param rModelPart ModelPart of the problem. Must have a set of conditions defining the "skin" of the domain
      * @param dimension Spatial dimension (2 or 3)
      * @note Use this fuction instead of its overload taking a Conditions array for MPI applications,
      * as it will take care of communication between partitions.
      */
    void CalculateOnSimplex(ModelPart& rModelPart,
                            int Dimension)
    {        
        this->CalculateOnSimplex(rModelPart.Conditions(),Dimension);
        rModelPart.GetCommunicator().AssembleCurrentData(NORMAL);
    }
```

Does enforce a AssembleCurrentData, but it does not take care of reseting all the nodes (only the ones which can be accesses through `rModelPart.Conditions()` inside the `CalculateOnSimplex` implementation, which cause orphan nodes in which belong to a condition in a process to have the values accumulated rather than synchronized if the function is called multiple times and the user does not manually reset the normal of such nodes before calling this.

In my opinion the current behavior is misleading.

I would change it so the normal are reset in this entry point instead of the `ComuteSimplex` implementation but as the function is public and exposed to python `typedef  void (NormalCalculationUtils::*CalcOnSimplexCondType)(NormalCalculationUtils::ConditionsArrayType&,int);`, I cannot remove the normal reset that takes place there as this would break, causing the loop to be duplicated.

If this is acceptable I will duplicate the normal reset loop, but at this point I think the correct solution would also be to deprecate the entry point with conditions. This is used only in the following locations:

- applications/ULFapplication/python_scripts/runge_kutta_frac_step_solver.py (1 use)
- applications/ULFapplication/python_scripts/SurfaceTension_monolithic_solver.py (2 uses)
- applications/ULFapplication/python_scripts/ulf_PGLASS.py (1 use)

The other solution would be to also pass the modelpart along with the condition list see we have access to all nodes and the reset can be correctly done there.

As I have not much experience using this I would like to ask what do you thing is the better solution.

**Comment by philbucher** [comment]
related: #2376

**Comment by loumalouomega** [comment]
> related: #2376

Yep, we should still unify the utilities...

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee delegates this PR to @KratosMultiphysics/implementation-committee and @roigcarlo  will assist on their decision.

**Comment by GuillermoCasas** [comment]
I find @RiccardoRossi 's summary of the reasons for going for the 4-variable approach reasonably convincing, especially when it seems this is common practice. 

Nonetheless, I wonder why the plain-strain element derives from ElasticIsotropic3D. It seems there is no ElasticIsotropic2D counterpart, which is probably for some intelligent reason (sorry, know little about structural FEM). Nonetheless, it occurred to me that perhaps it would make sense to have that 2D element from which the different versions of the 2D elements could derive. Recently, the need for a zz-component of the stress arose for modelling a slice of a long probe that is being axially compressed (#6437), even if in reality a single extra DOF for the hole domain was necessary due to the symmetry of the problem. Here we see other cases were the need for that extra variable arises.

Thus, could it be that there is a need for a general 2d element from which it may be easy to include all the different varieties being discussed without having to generalise the present ones?

**Comment by philbucher** [comment]
ping @roigcarlo

**Comment by ddiezrod** [comment]
I think @mohittyagi-k found a bug related to empty partitions. It should be easy to fix, right @mohittyagi-k ?

**Comment by mohittyagi-k** [comment]
Yes @ddiezrod. Please refer to https://github.com/KratosMultiphysics/Kratos/pull/7703

**Comment by roigcarlo** [comment]
Since the fix is merged I will close this. Thx @mohittyagi-k !
