### ISSUE TITLE
Build of newest commit fails 

### ISSUE THREAD

**Issue by e-dub** [KratosMultiphysics/Kratos#689]
CMakeFiles/Kratos.dir/python/kratos_python.cpp.o: In function `PyInit_Kratos':
kratos_python.cpp:(.text+0x189): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
kratos/CMakeFiles/Kratos.dir/build.make:1399: recipe for target 'kratos/Kratos.so' failed
make[2]: *** [kratos/Kratos.so] Error 1
CMakeFiles/Makefile2:432: recipe for target 'kratos/CMakeFiles/Kratos.dir/all' failed
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Details:
Ubuntu 16.04
Python 2.7.12

**Comment by jcotela** [comment]
In my experience, this error is produced by a mismatch between the python and boost-python versions (for example linking against python 2.7 and a boost compiled for python3). Can you verify if this is the case? (what does the boost found by configure.sh link against?)

**Comment by e-dub** [comment]
Thanks for your response!
Kratos built with no problems yesterday...

-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
Boost Include: /usr/include
Boost Linkdir: /usr/lib/x86_64-linux-gnu
Boostlib used: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5.2")

**Comment by jcotela** [comment]
So it looks like cmake has decided to use boost-python for python27 and a python35, which are incompatible. I'm afraid you'll need to specify which one you want to use manually in the configure script. Since you told us you want the Python 2.7 one, I'd try defining something like
```
-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7m.so   \
```
In your configure script (but please check that this file actually exists, I don't have ubuntu to verify and it could have a slightly different name on your system, maybe without the trailing 'm')

**Comment by e-dub** [comment]
:thumbsup:
