### ISSUE TITLE
[CFD] Periodic BCs

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#6905]
Hi,

A long-long time ago I was trying to use periodics BCs with FractionalStep - OpenMP and MPI. At that time at leas MPI had issues. Could someone help me out with the current state? Perhaps a snippet of how this should be applied? I am aware of how to prepare the GiD model such that nodes are matching. Perhaps recent developments with coupled BCs?

@rubenzorrilla @adityaghantasala 
@KratosMultiphysics/fluid-dynamics

**Comment by sunethwarna** [comment]
Eventhough what I'm saying is not related to FractionalStep, I would like to state them since they are related to PeriodicBCs.

1. TrilinosResidualCriteria doesnt work with PeriodicBCs (the nodes of periodic conditions can fall under different processes which causes the problem. I don't know how to use metis partitioner to include periodics also to have them all in one process).
2. ConnectivityPreserveModeller copies all the conditions from ModelPart(If someone successfully does metis partitioner with periodics, then they cannot use ConnectivityPreserveModeller to replace elements and conditions since they will replace conditions and wall conditions with respective given new condition which raise error due to mismatch in number of nodes (periodics have only 2 nodes, whereas other surface condiitons has 3 nodes) in each condition)

These are my observations regarding PeriodicBCs in MPI.

And, I also tried to get FractionalStep Periodics working, but was unsuccessfull. :/

**Comment by mpentek** [comment]
Seem the problem is more complicated to solve technically and the question arises whether the effort is worth it, as the usage of periodic BC's from a physical perspective might be questionable.

**Comment by mpentek** [comment]
Seems the problem is more complicated to solve technically and the question arises whether the effort is worth it, as the usage of periodic BC's from a physical perspective might be questionable.

**Comment by RiccardoRossi** [comment]
you can do it by MPCs, but you will have to find the pairs and the periodicity condition to be applied.

for example in RVE_analysis.py you will find an example of application of MPCs using a periodicity + jump term
