### ISSUE TITLE
Creating Tests for MPI

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#693]
Concerning the creation of MPI-tests:
I talked to @pooyan-dadvand a while ago and he told me that I should create nodes, elements and conditions on the fly when initializing the test, a certain number per core. 
This makes the test independent  of Metis, Trilinos and `ReadModelPart`

There are three main things that are to be discussed for this:
1. Creation of nodes, elements and their connectivities when the number of processes is unknown. 
2. Creating a Communicator to link the ModelPart across the ranks
3. Creating a manufactured solution to check against

I think this is relevant for any Application that uses MPI, only point 3 differs.

I talked to @roigcarlo and he said that the point 1 and 2 shouldn't be too difficult. Point 3 might require some more thinking.
How could we create a manufactured solution that depends on the size of the model?
Any ideas @RiccardoRossi, @KratosMultiphysics/fluid-dynamics, @KratosMultiphysics/structural-mechanics ?

**Comment by pooyan-dadvand** [comment]
I usually use `StructuredMeshGeneratorProcess` for creation of mesh in serial. My suggestion would be to implement a mpi version of that

**Comment by jcotela** [comment]
I don't have a strong opinion on point 1, but what @pooyan-dadvand is suggesting could be a solution.

Regarding 2, I think we actually need to move the Communicator creation to the core (not on the Metis application). I can take care of that (since I put it there in the first place 👎 )

Finally, regarding 3, I see 2 options: if the expected solution is reasonably simple (e.g. constant, given by a function,...) we can assing it on a different variable after generating the model in step 1.
For more complex cases (for example, reading a benchmark solution for a file), I'd consider reading the reference solution on all threads and using only the parts that correspond to the local solution.

**Comment by philbucher** [comment]
Thanks for your answers
Regarding point 1 what @pooyan-dadvand suggest seems to be a good solution. Then once the communicator is moved to the core, this process could also initialize it?

Regarding 3, the first option @jcotela suggests is rel. simple. However for the benchmark solution we have two cases: Either we keep the model dimensions constant and refine it (decrease element size) with more cores used or we keep the element size constant and make the model larger. If we refine the model, the solution might change, if we enlarge the model, the solution file might not work for all cases

**Comment by philbucher** [comment]
I looked into how to create the communicator and came across the following:
For example in the `TrilinosImportModelPartUtility`, the `SetMPICommunicatorProcess` @jcotela mentioned creates the `MPICommunicator` ([here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/python_scripts/trilinos_import_model_part_utility.py#L65))
In the next step the `ParallelFillCommunicator`  is used ([here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/python_scripts/trilinos_import_model_part_utility.py#L68))
Looking into the Implementation, the `ParallelFillCommunicator` also creates an `MPICommunicator` ([here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_utilities/parallel_fill_communicator.h#L320))
Is the `SetMPICommunicatorProcess` even necessary at all then, if afterwards anyway the `ParallelFillCommunicator` has to be called?

**Comment by jcotela** [comment]
SetMPICommunicatorProcess replaces the default serial Communicator of the ModelPart with an instance of MPICommunicator. The ParallelFillCommunicator then initializes the communication graph. Both are needed in the current implementation.

**Comment by philbucher** [comment]
Are you sure @jcotela?
The `ParallelFillCommunicator` [creates](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_utilities/parallel_fill_communicator.h#L320) and [replaces](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_utilities/parallel_fill_communicator.h#L321) the communicator too. 
It looks like it is the [exact same thing that is done](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/metis_application/custom_processes/set_mpi_communicator_process.h#L119) in the `SetMPICommunicatorProcess`

**Comment by jcotela** [comment]
Interesting... I didn't know that. Still, I'm unconvinced that you don't need to call the `SetMPIComunicatorProcess`. It actually depends on what you want to do with the model part. If you partition a model part using our interface to Metis, it will write separate files, each of them with a local partition and the corresponding communicator data. The big issue here is that the serial communicator is rather optimized (since it never actually does anything, it does not properly initialize its internal data). If you try to read a partitioned mdpa file to a model part with a serial communicator, I expect bad things to happen, since the serial communicator reuses quite a bit of memory internally (pointers that point to different memory addresses in the parallel implementation all point to the same addresses in the serial) and you could be inadvertently overriding stuff.

I'd say that the only scenario where you don't need the `SetMPICommunicatorProcess` is if you know that you won't get coloring data from the mdpa file (because you partition them by hand or in some other method not involving the heterogeneous graph partition process).

**Comment by philbucher** [comment]
ok thanks @jcotela

**Comment by philbucher** [comment]
Thanks for your ideas, I am closing this for the moment
