### ISSUE TITLE
prestressed modal analysis

### ISSUE THREAD

**Issue by hcirah** [KratosMultiphysics/Kratos#6932]
I am currently working on my Bachelor thesis at the Free University of Bozen-Bolzano. I would like to generate a Campbell diagram of a shell model using Kratos Multiphysics and the Structural Mechanics Application. But in order to do this I need to find a solution to apply forces on the modal analysis solver. My approach would be to calculate the stresses first and then solve for the Eigenfrequencies of a prestressed model. Is this possible? If so, is there an example or test case showing how to do this?

**Comment by RiccardoRossi** [comment]
@manuelmessmer i think this is very close to what you did. Could you share your opinion?

**Comment by manuelmessmer** [comment]
Not sure if I got it right. A Campbell diagram plots frequency over rpm, correct? Do you want to run a dynamic analysis before you evaluate the eigenvalue problem or does the applied forces imitate the inertia forces?

**Comment by hcirah** [comment]
Yes, thats correct. 
Well, I was thinking about adding some loads like a surface load and the self weight of the structure. My first approach would be trying to imitate inertial forces by expressing them as an additional function of the self weight of the model (mainly for centrifugal forces as a function of the rpm).  
Since most of this forces depend on the rotational speed of the structure (ie. not only the interial forces but also surface loads). I would then run the problem with increasing rpm in order to generate the campbell plot.

**Comment by manuelmessmer** [comment]
Ok, I see. Then yes I think I did something very similar. You need to run a nonlinear solution step with your centrifugal forces and after that you evaluate the eigenvalue problem?  You can have look here: #5938
It is almost the same expect that the eigenvalue problem looks different.  Anyway this will not work out of the box, but you have to write a new strategy. In my case there is no mass matrix for instance.

**Comment by manuelmessmer** [comment]
Not sure how well you know Kratos. Let me know if you need any help..

**Comment by philbucher** [comment]
Maybe @armingeiser also has a suggestion

**Comment by philbucher** [comment]
@manuelmessmer do you think this can be solved globally?
I mean this sounds like a common usecase to me

@emiroglu don‘t you do the same for your towers?

**Comment by emiroglu** [comment]
@philbucher Yes this is what I did already.

It is possible by purely making use of the python layer. If you perform an initial nonlinear analysis using elements with nonlinear formulations, the displacement history is saved in the model_part. Then you can perform a modal analysis by feeding the same model_part without generating another one. The prestresses are computed by making use of the initial displacements. This approach makes more sense since existing prestresses are actually the resultants of initial displacements.

I attached the python script that drives this procedure: [MainKratos.zip](https://github.com/KratosMultiphysics/Kratos/files/4675925/MainKratos.zip)

**Comment by philbucher** [comment]
Thanks @emiroglu this makes sense to me

**Comment by e-dub** [comment]
@emiroglu Many thanks! 
It should be noted that the JSON file for the modal analysis needs to be changed to keep the previous model:
```
        "model_import_settings"              : {
                    "input_type"       : "use_input_model_part"
                },
```

**Comment by emiroglu** [comment]
A remark: I recently noticed that the corotational shells use a linear Green-Lagrange strain measure for computing the stresses. Thus, the initial displacements may not be effective in the computation of the prestresses. The dependency of the stiffness matrix is a result of the change in the coordinate transformation matrices. @KlausBSautter also mentioned at some point that the mass matrix ends up being displacement dependent due to the coordinate transformations.

**Comment by e-dub** [comment]
If I understand you correctly, this means that the modal analysis is "only" seeing the changes in the system matrices based on the displaced nodal coordinates but not the stresses caused by the static analysis?

**Comment by emiroglu** [comment]
So they only include the changes in case there is a rotation-like displacement occurs in the elements. The in-plane deformations do not cause any change in the element stiffness matrices. So, the static deformation induced prestresses would not be taken into account.
