### ISSUE TITLE
Missing function call in ALE App

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#700]
Hi @KratosMultiphysics/ale, 

I noticed that in the master branch, the function "UpdateReferenceMesh()" dropped out from the python script "mesh_solver_structural_similarity". Hence the corresponding function on C++ level cannot be accessed anymore from within Python breaking some of my test examples. 

Is there a reason for this removal? Would it be possible to just take it in again?

Thanks and best regards,
Daniel

**Comment by msandre** [comment]
Hi Daniel,

The python solvers were recently restructured and the interface is now defined through the base mesh solver class. This is done to cut down on code copying and to keep the interfaces of different solvers from diverging by the addition of non-standard functions. To make a long story short, the UpdateReferenceMesh() function was removed because it is a non-standard function. You can still call it (and other non-standard functions) if you know you are using a strategy that implements the function by calling

solver.get_mesh_motion_solver().UpdateReferenceMesh()

This basically exposes the underlying strategy so you can call methods on it directly. Alternatively, we can consider making it part of the standard interface, but then the function should be implemented for all mesh motion solvers.

**Comment by dbaumgaertner** [comment]
Fair enough. Thanks @msandre. I was not aware that you can call it this way, too.
