### ISSUE TITLE
windows CI fails

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#7067]
The windows CI seems to be failing for many recent PRs
https://github.com/KratosMultiphysics/Kratos/pull/7045/checks?check_run_id=763838897#step:6:493

https://github.com/KratosMultiphysics/Kratos/pull/7066/checks?check_run_id=762126529#step:6:493

https://github.com/KratosMultiphysics/Kratos/pull/7064/checks?check_run_id=762248826#step:6:491

for example. Calling code doctors @philbucher @roigcarlo 🏥

**Comment by philbucher** [comment]
I know, but thx for reporting also for others to see
Once again the compiler in Win was updated (will post the version numbers later) and it seems like once again it fails with the newer one.
I couldn’t find out yet why, since it is a very recent version of the msvc compiler I couldn’t find a lot yet on google.
Also I am not the win expert

I think @roigcarlo is back next week, guess you have to hang in until then, sorry for the delay

I will try to find a solution for using a consistent version of the compiler such that this won’t happen again

**Comment by philbucher** [comment]
working version of the compiler: 19.26.2880**5**.0
non-working version: 19.26.2880**6**.0

@oberbichler do you have an idea how to prevent the auto-update of the compiler? I am not sure it is possible, at least I couldn't find anything on this topic

Probably since we use the latest "global" version of the compiler (i.e. MSVC 19) we get the updates right away
=> maybe we could avoid this by using a slightly older compiler (e.g. MSVC 18) that is more stable
This should work I guess since we anyway don't use the most new features of C++

**Comment by philbucher** [comment]
just for the record, this is the error:
~~~
 MSBUILD : error MSB1009: Project file does not exist.
Switch: zlibstatic.vcxproj
Failed with error #1.
~~~

Although I am not sure if this is related to zlib or by coincidence the zlib-output was the next to come
