### ISSUE TITLE
Inconsistent GetData vs Data

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#7322]
**Description**
Elements and conditions have different function name for the `Data()` and `GetData()` operation being non-const and const versions of the same functionality.

On the other hand nodes use only the `Data()` function name in both cases.

This is confusing and one of the alternatives should be used.

to be discussed by @KratosMultiphysics/technical-committee 

**Additional info**
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/node.h#L516-L524
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/geometrical_object.h#L210-L218

**Comment by philbucher** [comment]
this is directly related to #6481

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee fully delegates this issue to the @KratosMultiphysics/implementation-committee

**Comment by AlejandroCornejo** [comment]
Hi! I think that since lately the `const` approach has been the one selected (in other methods), maybe we should procedd with this one.

**Comment by inigolcanalejo** [comment]
The @KratosMultiphysics/implementation-committee  agrees with @roigcarlo that this is confusing has decided to use `GetData` as in the `Geometry` for both const and non-const versions. @KratosMultiphysics/technical-committee, please let us know if you agree with this change so that we can proceed.

**Comment by ddiezrod** [comment]
Just to extend a little the answer from @inigolcanalejo. We thought initially using `Data()` to have the same interface as the node. The problem is that we saw that in the `Geometry` we are using only `GetData()`, so to be consistent more changes will be needed in any case. As the `GeometricalObject` has a `SetData()` we think users would expect to also have its relative Get method. Thats why we think its better to stick to `GetData` and even consider in the future to also replace the `Data` method in the node with `GetData` .

**Comment by pooyan-dadvand** [comment]
Thanks to @KratosMultiphysics/implementation-committee for the decision and @KratosMultiphysics/technical-committee agrees with it.

Please go ahead!
