### ISSUE TITLE
GetDefault... is inconsistent btw Python and C++

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7431]
In Python it is `GetDefaultSettings`, in C++ it is `GetDefaultParameters`

I don't have a strong opinion except that they should be consistent

Since it is not a heavily used feature I think we could easily rename either of them

@KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
Agree. I would go for `GetDefaultParameters` since the class its name parameters...

**Comment by loumalouomega** [comment]
> Agree. I would go for `GetDefaultParameters` since the class its name parameters...

I would go also here as I created the method in first place for the Processes and it was `GetDefaultParameters`, I don't know who added the Python one, but it was not before 2016-2017 when I created the first Processes (mmg+metrics)  with `GetDefaultParameters`

**Comment by philbucher** [comment]
Ok then lets not make a big fuss and agree on `GetDefaultParameters` I suggest

if no other opinions are raised by end of week then I consider this decided :)

**Comment by pooyan-dadvand** [comment]
@philbucher and @roigcarlo I am truning back to this issue because it is very inconvenient to change an interface which is very largely used in an issue and a  PR in two days. Moreover, there is no blocking issue related to it, nor an apparent reason to fast forward it. It wasn't even depreacated. 

**This should have been approved by** @KratosMultiphysics/technical-committee and should have been passed by the deprecation and other notices mechanisms.
