### ISSUE TITLE
Reading multiple mdpa files

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#745]
For simulating a large Windturbine I would like to keep the main parts (blades, nacelle, tower) in separate files such that I can replace them without having to touch the other parts and/or the mdpa file. Also then I can create the parts separately which simplifies the process a lot.

So what I propose is to have sth like the [*INCLUDE](http://abaqus.software.polimi.it/v6.14/books/key/default.htm?startat=ch09abk14.html) feature of abaqus.
I think this is a helpful feature for large models and probably I am not the only one using this.

I tried to do this with the existing Implementation (`ModelPartIO` and `ReorderConsecutiveModelPartIO`), but it is not working.

To make this work in serial as well as in parallel I think we need a new `IO` class, that reads the input files sequentially and reorganizes the IDs.

The partitioner `MetisDivideHeterogeneousInputProcess` takes an `IO` object as input, therefore I think that the new `IO` class should take the list of input-files directly in the constructor (and not call the `ReadModelPart` function several times).

For now minor, but might also be interesting: A process for [affine transformations](https://en.wikipedia.org/wiki/Affine_transformation) such as translating, rotating, scaling,... a part

Any opinions @RiccardoRossi @pooyan-dadvand @jcotela ?

To further illustrate what I would like to do here are three input files:
* first_part.mdpa:
```
Begin ModelPartData
//  VARIABLE_NAME value
End ModelPartData

Begin Properties 0
End Properties

Begin Nodes
    1        1.0        0.000        0.00000
    2        2.0        0.000        0.00000
    3        3.0        0.000        0.00000
    4        4.0        0.000        0.00000
```
* second_part.mdpa:
```
Begin ModelPartData
//  VARIABLE_NAME value
End ModelPartData

Begin Properties 0
End Properties

Begin Nodes
    1        8.0        0.000        0.00000
    2        5.0        0.000        0.00000
    3        6.0        0.000        0.00000
    4        7.0        0.000        0.00000
```
* third_part.mdpa:
```
Begin ModelPartData
//  VARIABLE_NAME value
End ModelPartData

Begin Properties 0
End Properties

Begin Nodes
    1        1.0        1.000        0.00000
    2        2.0        2.000        0.00000
    3        3.0        3.000        0.00000
    4        4.0        4.000        0.00000
```

**Comment by RiccardoRossi** [comment]
Hi Philip,

once the reordering comes into play this becomes a very nasty issue.
also one of the problems is that parsing of the files is becoming increasingly difficult.

my personal view is that we should start moving out from our custom format and explore alternatives, which would hopefully make easier to read write in parallel.

i was originally very much in favour of hdf5 for this, but i am slowly becoming less convinced.

json instead of mdpa would also be an alternative (it would relieve the parsing problem)

having said all of this i think i don't have a real suggestion... and i think the one you rise is a major question that we should discuss alltogether

**Comment by maceligueta** [comment]
I am not sure if it will help at all, but in the DEM application we have this file:
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/DEM_application/custom_utilities/reorder_consecutive_from_given_ids_model_part_io.h
Which can reorder the Id's from a given int. So, if you know the last Id used in the previous mdpa, you can provide this number + 1 to the next read. The pyhon file gets longer because you have to find out whats the Max Id of the previous read before calling this IO for the read of the next mdpa...

**Comment by philbucher** [comment]
hi @RiccardoRossi 
I see, thanks for your answer. This sounds like there is not an easy solution to this

@maceligueta Thanks for the suggestion, I will try this! Have you tried to use it together with metis i.e. partitioning?

**Comment by maceligueta** [comment]
Together with @roigcarlo , we ran some computations with partitioning some time ago. But we only sent one modelpart for partitioning, the first one, where all ids are consecutive and start from 0. The rest of modelparts had also consecutive Ids, but only for postprocessing purposes, not partitioning.

**Comment by pooyan-dadvand** [comment]
The include would be a nice feature but for me it should do only include to be maintainable. For your problem I would go for reading one by one the sub model parts with given starting Ids as suggested by @maceligueta

**Comment by pooyan-dadvand** [comment]
Accidentally closed it

**Comment by philbucher** [comment]
I have not tried your suggestion yet, I will reopen this thread if I need help
Thanks for your help!
