### ISSUE TITLE
Error when compiling Kratos in Debug mode on Windows

### ISSUE THREAD

**Issue by rlrangel** [KratosMultiphysics/Kratos#7478]
I am trying to compile Kratos with PfemFluidDynamicsApplication and LinearSolversApplication in Debug and FullDebug modes on Windows, but it is giving me the following error:

LINK : fatal error LNK1104: cannot open file 'python38_d.lib' [C:\Users\rrangel\Desktop\kratos\kratos_git\build\FullDebug\kratos\run_kratos\runkratos.vcxproj]

I cannot find this file python38_d.lib.
Anyway, no error occur when I compile in Release or RelWithDebInfo modes.

**Comment by roigcarlo** [comment]
Hi @rlrangel 

In order to compile with debug on windows you need the debug libraries of python, those are not copied by default and you must select them during the installation. (see [Windows debug](https://github.com/KratosMultiphysics/Kratos/wiki/Debugging-Kratos-using-Visual-Studio))

If you are using python package from its webpage, there should be an option in the installer, if you are using the version that comes with visual studio, you should be able to add it through the visual studio installer, selecting the modify option ( there is a checkbox in the python extension).

Optionally you can add `-DINSTALL_RUNKRATOS=OFF` as an option in the configure file, that will prevent the `runkratos` executable from being compiled which is the lib that is demanding you that library. Notice that in this case you will have to run the scripts through `python.exe` directly.

**Comment by rlrangel** [comment]
Thank you @roigcarlo !
I got the Python debug libraries from the installer and it is working now.
