### ISSUE TITLE
How to set initial conditions?

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#7544]
I was discussing today with @mohittyagi-k how to set initial conditions. If I'm not wrong, surprisingly there is no standard way to impose them using processes. The trick we used was applying "interval" : [0.0 , 0.0] in the "assign_.._process.py". This is working right now but to do comparisons between doubles does not seem very safe and also looks quite dirty for such a basic thing as setting initial conditions. I think using "interval" : [0.0 , 1e-10] is not much better neither... 

Maybe there is another process to do this that we did not see? If not, I think we should have a common solution for this. though it might be a little painful considering how the number of "assign" processes grew.

@KratosMultiphysics/altair @KratosMultiphysics/design-committee @KratosMultiphysics/interface-committee

**Comment by loumalouomega** [comment]
We can add to the processes the flag `initial_condition`, false by default, that will obviate the interval and applied only in the `BeforeSolutionLoop`

**Comment by ddiezrod** [comment]
Well, it seems @vdivine found the solution. There is a ApplyConstantScalar/VectorProcess that does what we need, calling Execute only in Initialize. Its in cpp so that's why we forgot about it. I think we will use that one if it's not deprecated, sorry for the noise. Hopefully, this issue will help others in the future :)

**Comment by rubenzorrilla** [comment]
We had the same discussion not long ago. I see two possible straighforward solutions:
1. what @loumalouomega suggests
2. from each one of the main processes derive it's corresponding initial condition version that only implements the `ExecuteInitialize` and `ExecuteBeforeSolutionLoop` methods.

Another thing that comes to my mind is to create a new `initial_process` class. This class would have the same API as the `process` one but all the methods but the `ExecuteInitialize` and the `ExecuteBeforeSolutionLoop` must be non-virtual so they can be called using the standard process list but enforcing an empty implementation. Then, in the derived classes (e.g. assign_scalar_value_process_initial) we can make the standard processes (e.g. assign_scalar_value_process) friends of the initial classes, so we can reuse the standard processes implementation.

**Comment by mohittyagi-k** [comment]
Also, (in addition to what @ddiezrod mentioned), I have the following doubt. 

Shouldn't the following two processes have the same behavior, since the `Parameters` are identical (assuming we assume `constrained`  would imply the same thing as `is_fixed`, which may not be the case):

Process 1

           "kratos_module": "KratosMultiphysics",
            "python_module": "assign_scalar_variable_process",
            "process_name": "AssignScalarVariableProcess",
            "Parameters": {
              "model_part_name": "some_model_part_name",
              "variable_name": "VARIABLE",
              "value": 1,
              "constrained": false
            }

Process 2

            "kratos_module": "KratosMultiphysics",
            "python_module": "process_factory",
            "process_name": "ApplyConstantScalarValueProcess",
            "Parameters": {
              "model_part_name": "some_model_part_name",
              "variable_name": "VARIABLE",
              "value": 1,
              "is_fixed": false
            }

What is not obvious is that Process1 means that value of 1 is applied at the beginning of every time step and is not constrained during the time step, while the Process2 means the value of 1 is fixed for the entire simulation.

**Comment by philbucher** [comment]
I would not add yet another flag to the processes (that even contradicts another one!)

I however agree that we have a huge mess when it comes to the processes and I myself also don't fully get when to use what

probably it is time to clean up the mess, document it (I know some docs exists but I don't understand them)

#
**For this we need the basic requirements**
- Initial or over entire time/interval
- Where to apply:
    - Nodes historical
    - Nodes non-historical
    - Elements
    - Conditions
    - Constraints
- Should be conditional? => e.g. check against a `Flag`
- Fixity IMO should be done with a separate process (one of the few clean ones we have). Can be argued though, but this caused many many problems with the usage already in the past => consider that this anyway only makes sense for nodal historical

#

I am well aware that this is a huge effort that would also break existing stuff, but I think we need to do sth about it

IMO a viable solution approach would be:
1. Analyse the current situation, what do we have atm, where do we stand?
2. Which processes are duplicates? (I know there are some) => deprecate/remove duplicated ones
3. Identify missing things
4. last but not least: UNIFY THE SETTINGS (e.g. `constrained` vs `is_fixed`)

**Comment by loumalouomega** [comment]
> I would not add yet another flag to the processes (that even contradicts another one!)
 
We can just simply initialize the values always before the solution loop, and then the interval only needs to be set from 0.0 to 0.0, or to initialize just when interval is from 0.0 to 0.0

**Comment by pooyan-dadvand** [comment]
I agree with @philbucher 

Just to add my opinion after looking to how the process use evolved during this times. 

I feel that we have a rich layer of building block processes but few intermediate ones that internally combine them. Something like having ApplyFSIBoundaryCondition which sets several variables at once knowing the fixities and some other details and internally just call the other ones correctly, instead of adding all related processes one by one in the json. (I admit that this maybe is not the best example but just to show the purpose)

In fact, most of the time, we delegate this directly to the solver but we don't have something similar in the stage side.
