### ISSUE TITLE
MPI dependency of Kratos Core

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#781]
There are a few parts of the core of kratos (most notably the MPICommunicator class) that explicitly depend on MPI but, right now, the core is designed to never depend on the openmpi libraries, not even when compiling with MPI support. To sidestep this, we are "hiding" the mpi parts on derived applications that do link to openmpi:
- MPICommunicator is exported to python by the TrilinosApplication, even though the class files live in the core.
- SetMPICommunicatorProcess lives in the MetisApplication (see #693).

This is more than a bit ugly, and will become more prevalent as more MPI features that are not application-specific are added (I'm thinking MPI testing, for example), so I wanted to start a discussion on how to address this. Some options, after discussing with @pooyan-dadvand:
1. Leave as is (will get uglier as new features are added).
2. Have the core depend on MPI if Kratos is compiled with MPI support.
3. Create a new "extension" library to contain MPI-specific features of the core (`KratosCoreMPIExtension`)
4. Create a "replacement" core library: if one runs a non-mpi case, `KratosCore` is loaded, but a different `KratosMPICore` is loaded for MPI cases, containing the required extensions *and everything else*.

Opinions?

**Comment by loumalouomega** [comment]
KratosCoreMPIExtension 👌

**Comment by philbucher** [comment]
option 3 sounds good to me
Is this also where e.g. the MPISearchApplication would go into once it is finished? @roigcarlo

**Comment by roigcarlo** [comment]
I was moving it to the mpi_search_application but I also agree 3 sounds better. :+1:  for me as well.

**Comment by pooyan-dadvand** [comment]
As I told to @jcotela, I also prefer the option 3. @RiccardoRossi what is your opinion?

**Comment by maceligueta** [comment]
Option 3. And we should do the same in the apps, I guess.

**Comment by pooyan-dadvand** [comment]
Yes @maceligueta, in my opinion applications should do the same. So the MPI parts will be in separate files and CMake will decide to compile them or not.

**Comment by jcotela** [comment]
@pooyan-dadvand This would mean importing two things in python for each current Python import statement (altough we could hide this from the user if desired). What is the advantage of having two separate libraries per MPI-enabled application compared to the approach used (e.g.) in the MappingApplication (which is a single library with extra sources/linkage when mpi is enabled, similar to option 2 above)?

**Comment by philbucher** [comment]
Even though it is not the topic of this issue, I want to share my opinion regarding the organization of mpi in the apps.
I think it is not a good idea to have two applications for mpi and non-mpi. In addition to Jordis comment this is too much overhead, code repetition, harder to maintain, test,... I think as Pooyan suggested it is enough having the separation in CMake.
Afaik I am one of the few who has both in an app and this is my way of doing it:
I do/will do is separating in e.g. `custom_utilities` and `custom_utilities_mpi`. And/or `add_custom_utilities_to_python.cpp` and `add_custom_utilities_to_python_mpi.cpp. 
This way mpi is nicely separated from non-mpi and it is still easy to spot where mpi is used and where not.

**Comment by pooyan-dadvand** [comment]
Actually for me is equally eligible the  option 2 or 3 for applications. For me the important feature is to separate it in CMake as @philbucher also mention it.
Also I should add that for me even in KratosCore we can statically link the serial core to the MPI.... (similar to option 2)

**Comment by RiccardoRossi** [comment]
+1 for option 3

**Comment by RiccardoRossi** [comment]
one of the problems we have as of now is that in order to run in mpi one must set the correct settings in mpi AND launch with mpirun. there is currently no way to check that both things are done consistently, which triggers errors. 

what we could do is that when we launch with mpirun an extra argument, say MPIPARALLEL, has to be passed at the moment of running the script. this would allows us to do all of the consistency checking we want, as well as to load the correct version of the libraries.

this is to say that to launch in openmp  we would do

python3 main.py

to launch in mpj we would have to do

mpirun --np ... python3 main.py --MPIPARALLEL

at this point the main could verify if the settings are consistent with the use of mpi and also at the moment of loading make sure that the correct version of the libs is being loaded.

to make it clear, i don t particularly like the idea of adding an extra paramerer, however it appears that there is no portable way to detect if a script is being launched with mpi or not, since the mpi stansard does not prescribe jow the scropt is to be launched. what i found is only hackish solutions checking the values of environment variables set by the mpirun

**Comment by maceligueta** [comment]
I am sure you know this, @RiccardoRossi et al., but there's some environment variables that are defined only when you are running the script with MPI. However, these variables are different when you change the OS, or when you change the MPI library. I know it is not very elegant (definitely not portable) but this is the provisional solution we are using for the DEM application. No need to add arguments to the mpirun command then.

**Comment by RiccardoRossi** [comment]
yes, that would be the alternative way. however i don t know how to make it
portable

On Oct 22, 2017 2:33 PM, "Miguel Angel" <notifications@github.com> wrote:

I am sure you know this, @RiccardoRossi <https://github.com/riccardorossi>
et al., but there's some environment variables that are defined only when
you are running the script with MPI. However, these variables are different
when you change the OS, or when you change the MPI library. I know it is
not very elegant (definitely not portable) but this is the provisional
solution we are using for the DEM application. No need to add arguments to
the mpirun command then.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/KratosMultiphysics/Kratos/issues/781#issuecomment-338473995>,
or mute the thread

**Comment by RiccardoRossi** [comment]
@maceligueta , thinking about if we had something that works with openmpi, mpich and intelmpi that would be a good start.

does your solution comply with this?

**Comment by RiccardoRossi** [comment]
we could also define a runkratos_mpi definimg what we need...

**Comment by RiccardoRossi** [comment]
just storing a link which might be useful

https://stackoverflow.com/questions/12678337/how-can-my-program-detect-whether-it-was-launch-via-mpirun

**Comment by philbucher** [comment]
I like the idea of runkratos_mpi
We already have the runkratos cmd, so in my eyes it is consistent with what is there already from the user point of view
How would it be realized? As shortcut for mpiexec? I.e. instead of `mpiexec -np 4 python3 MainKratos.py` it would be `runkratos_mpi 4 MainkKratos.py`?

**Comment by pooyan-dadvand** [comment]
runkratos_mpi is not a bad idea. But I cannot estimate the effort we need to implement and maintain it.

**Comment by RiccardoRossi** [comment]
jeje i was not thinking grand :-D

my suggestion was
       
     mpirun --np 4 runkratos_mpi MainKratos.py

**Comment by pooyan-dadvand** [comment]
:smile: this would be easier to maintain!

**Comment by jcotela** [comment]
Adding it to the Technical Committee issues. I think at least the MPI extensions to the core could be implemented for the next release cycle.

**Comment by philbucher** [comment]
:+1:

**Comment by philbucher** [comment]
I found an [example on how to do MPI-testing in Travis](https://travis-ci.org/precice), seems to be not too difficult

**Comment by philbucher** [comment]
I think this can be closed ...?

**Comment by jcotela** [comment]
@philbucher the last step for this issue would be to "fix" the dependencies of the trilinos application, so I'd prefer to keep it open as a reminder that this is still needed.

**Comment by jcotela** [comment]
The MPI core is already working in the current master, closing this issue. Feel free to create new issues to discuss problems with it.
