### ISSUE TITLE
Compiling problems with the Kratos Tutorial (problems with conditions and element)

### ISSUE THREAD

**Issue by PhiHo-eng** [KratosMultiphysics/Kratos#7821]
Hi everyone,

I am still stuck at the [Kratos Tutorial](https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-For-Dummies:-Stationary-heat-transfer), like I mentioned in #7787.
But noe I seem to have problems with the element and conditions I created. At the moment I am not able to compile my new application. I get these errors when compiling: 

[error.txt](https://github.com/KratosMultiphysics/Kratos/files/5554409/error.txt)

There may be something I am not seeing. Does anyone know how to fix this or had a similar problem in the past?

Thanks in advance!

**Comment by marcnunezc** [comment]
Hi @PhiHo-eng,

It seems there is a missing closing statement

`}`

in the line
```
/home/philipp/opt/kratos/applications/MyLaplacianApplication/custom_elements/my_laplacian_element.cpp:575:1: error: expected ‘}’ at end of input
  575 | } // namespace Kratos.
      | ^
```

which causes the long chain of errors.


Apart from this, I have checked the tutorial and I have seen there are other errors, which are caused due to recent changes in the code. Sorry for the inconvenience. I have corrected them in the tutorial already, but I will list them here as well.

1. In my_laplacian_application.cpp. Replace the include `"#include "geometries/line_2d.h"` with `#include "geometries/line_2d_2.h"`

2. In my_laplacian_element.cpp (adding many **const**):
https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Element/_compare/f47daf4acebab121ecedcf86f6b7107d92681939...99dfaf1f4ee52528979c1c472712a9ab53b90b77

3. In my_laplacian_condition.cpp (adding many **const**):
https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Conditions/_compare/79d7486c8fbe20a252af9db4be371855d61c78ad...4ea259da024a83c9c8669584ca242fdd8fa7d75b

**Comment by PhiHo-eng** [comment]
Hi @marcnunezc, 

Yes this works! Thank you very much!

**Comment by marcnunezc** [comment]
Perfect! I will close the issue, feel free to open it again if you need it!
