### ISSUE TITLE
Availability/Status: Thermo-Fluid coupled solver

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#8074]
**Description**
I am interested in knowing if there is a possibility to solve thermo-fluid coupled problems (meaning solving for velocity, pressure and temperature)? From what I recall, a year or two ago there was a discussion going in this direction. Would appreciate an update on it.

For validation purposes there is a colleague at TUM who is doing research on thermal comfort and ventilation and would like to have a discussion going with a potential for a collaboration.

**Comment by philbucher** [comment]
I think @rubenzorrilla should b able to answer this

**Comment by rubenzorrilla** [comment]
The buoyancy solver has been working for many years. Since a few years ago it is also available in the GiD GUI (Fluid->Buoyancy). If I'm not wrong, it has a predefined example too, so it should be straightforward to try it (note that you will need to compile the `ConvectionDiffusionApplication`).

During the last months we have been improving a lot the compressible NS capabilities (unfortunately there is no GUI for these yet). In any case the incompressible NS + buoyancy is the one that better suits the HVAC applications.

**Comment by mpentek** [comment]
Thanks for the input!
