### ISSUE TITLE
[RANS] File names are too long

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#8205]
**Description**
We are having problems when we try to download kratos module in our CI machines in Altair. 

![image](https://user-images.githubusercontent.com/25667299/106726956-413b2280-660b-11eb-9423-a36678691954.png)

Some of the files used in tests are reaaally long, could you please make them shorter? @sunethwarna

**Comment by ddiezrod** [comment]
FYI @mohittyagi-k

**Comment by ddiezrod** [comment]
Here its complaining about two files, but I see there are more that are also quiet long. Please rename those too.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25667299/106727534-e0601a00-660b-11eb-91f3-9661aeadb393.png)

**Comment by sunethwarna** [comment]
I am on it

**Comment by ddiezrod** [comment]
Thanks a lot! I'd rename them myself but I have no idea what's going on there :)

**Comment by pooyan-dadvand** [comment]
@sunethwarna Thanks for cleaning up!

Meanwhile, I wanted to add some suggestions and tips:
1. To my understanding you are checking the results with many nodes for different models. I would suggest to only check again some relevant points (like near the inlet, in the outlet, near the wall, etc.) To my experience, this kind of all nodes checks gives more false negatives and headaches rather than helpful info. Please note taht unittests are about precision in telling what went wrong. It is good to have a couple of smoke tests for just in case but they are less helpfull in general.
2. Having to test with small number of nodes would make your comparison easier and you may even put important messages in your tests (like VELOCITY variable is not correct in near_the_wall_node) which gives a fast hint about the problem
3. In this way you may also reduce the size of the tests. (There are about 14Mb of them now)
4. Having small reference nodes, you may even put all of them in the same tests or in one json with the long labels instead of abusing the filenames.

I hope you find these tips helpful.

**Comment by sunethwarna** [comment]
Hi, I created #8209 to fix this. In this PR I am only shortening the filenames. 

@pooyan-dadvand Thanks for the tips. It makes perfect sense. I'll make the changes in a different PR in future, because it is a large change and it will have lots of conflicts with the branches I am working with.
