### ISSUE TITLE
Is the WindTurbineApplication still in development/use?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#823]
I saw that there is a WindTurbineApplication in Kratos. I don't really know the authors in the files except @pooyan-dadvand and @RiccardoRossi.
Can you say anything abt the purpose of this application, if it is still used/developed, or is it deprecated?
It seems not to be the most up-to-date code. 
Also there are not too many comments in the code regarding what it can do/is doing.
Help would be appreciated :D

**Comment by loumalouomega** [comment]
I think is totally deprecated, it was here when I arrived to CIMNE...

**Comment by pooyan-dadvand** [comment]
Actually the application is somehow old and done by Marco and afterward for some time was maintained by @jcotela. So he would give a better description of it.

**Comment by jcotela** [comment]
Just for the record, the application you mention was originally implemented by Enrico and both Marco and me contributed to it. I am its current maintainer. You have to keep in mind that, despite its name, it was designed to solve a very specific problem (body-fitted ALE simulation of a vertical axis wind turbine) for a project we worked in at the time. We can discuss the details if you are interested but, if I had to solve the same problem now, I would at least go with Chimera methods (or fully embedded if you are feeling brave), rather than doing body-fitted analysis.

**Comment by pooyan-dadvand** [comment]
Just to add, this shows that how putting names in headers would be misleading... Especially when people copy pastes...

**Comment by philbucher** [comment]
ok thx for the info
