### ISSUE TITLE
ContactStructuralMechanicsApplication Problem in Nightly builds

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#827]
Since this has proven to be a resilient bug. I will create a issue to follow it up. What we know so far:

- A test for the ContactStructuralMechanicsApplication causes a memory error in nightly builds.
- The error only happens on the nightly build machine
- The error does NOT happens if the tests are run separately from other tests
- The error does NOT happens if the maximum runtime is decreased on other tests

The current guess is that there is a memleak inside the application that may be using memory previously allocated by one of the previous tests. But we are not sure.

@loumalouomega Did you make a Pr with the fixed you did last Friday?

**Comment by loumalouomega** [comment]
#824

**Comment by roigcarlo** [comment]
:+1:

**Comment by RiccardoRossi** [comment]
can this be closed?

**Comment by loumalouomega** [comment]
Yep

El 28 oct. 2017 9:42 a. m., "Riccardo Rossi" <notifications@github.com>
escribió:

can this be closed?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/KratosMultiphysics/Kratos/issues/827#issuecomment-340157317>,
or mute the thread
