### ISSUE TITLE
[StructuralMechanicsApplication] Regsiter new CL variables discussion

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#8392]
**Description**
Dear @KratosMultiphysics/structural-mechanics @KratosMultiphysics/technical-committee , 

Recently @philbucher added the `ConstitutiveLawsApplication ` and I am wondering where to register the new variables needed for the models (or the currently used). 

1. Inside the SMA?
2. Inside the CnstitutiveLawsApp

Thank you,

Alejandro

**Comment by philbucher** [comment]
they should be added in the ConstitutiveLawsApp

In fact a leftover is to move the CLaw variables from the StructuralApp to the CLawApp

**Comment by RiccardoRossi** [comment]
To complete @philbucher 's answer, do take into account that if you need the variable to be called "with name" inside the structural mechanics, than you will not be able to do this. 

What will NOT be allowed is to include the constitutive_law_variables.h from within the structural mechanics (or from any other application)

**Comment by philbucher** [comment]
we just discussed this in the @KratosMultiphysics/technical-committee and I want to give a more elaborate answer :)

Currently the `ConstitutiveLawsApplication` depends on (aka includes & links against) the `StructuralMechanicsApplication`. This I did so that I could minimize the changes necessary in #8367 since it would have requires more refactoring. In the future we want to remove this dependency such that the `ConstitutiveLawsApplication` is completely standalone so that e.g. also @KratosMultiphysics/mpm can use it without having to deal with `StructuralMechanicsApplication`.

Now what does this mean for the variables that are needed for the ConstitutiveLawsApp?
- Variables that are only needed for internal purposes in constitutive laws (e.g.`CURVE_FITTING_PARAMETERS`) should be declared in the `ConstitutiveLawsApplication`
- Variables that are used both in the `ConstitutiveLawsApplication` and in the `StructuralMechanicsApplication` should be declared in both applications. 
**Note** that we currently have some problems with having variables defined in multiple apps (see e.g. #8050). Hence the current way is to have them only in the `StructuralMechanicsApplication` until those problems are fixed. 
So for this the roadmap is the following:
    - Fix the memory issues with variables defined in multiple apps
    - add the variables that are necessary in both applications to the `ConstitutiveLawsApplication`.
    - remove the dependency of the `ConstitutiveLawsApplication` on the `StructuralMechanicsApplication`

I hope this is more clear now

**Comment by philbucher** [comment]
@AlejandroCornejo could you please take a look at which variables are only used in the ConstitutiveLawsApp and move those?
thx

**Comment by AlejandroCornejo** [comment]
> 
> 
> @AlejandroCornejo could you please take a look at which variables are only used in the ConstitutiveLawsApp and move those?
> thx

@SergioJimenezReyes and me are developing new CL. In the PR of this CL we will move all this variables :)
