### ISSUE TITLE
Add Q_VALUE as variable for FluidDynamicsApplication

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#854]
In 
python_scripts/navier_stokes_base_solver.py

In function
    def AddVariables(self):

Add line
self.main_model_part.AddNodalSolutionStepVariable(KratosCFD.Q_VALUE)        # Q_VALUE  belongs to FluidDyanmicsApp -> Q-Criterion (for vortex visualization)

Otherwise Q_VALUE visualization is not possible.

**Comment by rubenzorrilla** [comment]
Is this Q_VALUE variable intended to be used in all fluid solvers? Otherwise, it can be added only in those solvers that need it.

**Comment by mpentek** [comment]
#855 As far as I know, it is something that each fluid solver could/should use.
It is already there in FluidDynamicsApplication/fluid_dynamics_application_variables.cpp so I think it was intended like this.

**Comment by rubenzorrilla** [comment]
@mpentek for me it's ok. Let's wait for @jcotela oppinion, he probably knows much more about the use of this variable.

**Comment by jcotela** [comment]
Hi @mpentek. The Q_VALUE is computed on integration points (for the fractional_step element and derived types, which, as far as I know, is the only element that currently supports it), so you should not need to add it as a NodalSolutionStepValue (only adding it to the list of variables on gauss points/calling the relevant gid_io method).
Can you clarify what would be needed to visualize it on nodes?

**Comment by mpentek** [comment]
@jcotela Indeed, I use it with fractional step. Also, the file
fluid_dynamics_application_variables.cpp had it, so I simply added it for me in
python_scripts/navier_stokes_base_solver.py
so that it works. It is most probably not the best way to go.

For the usage I also need some additions in the MainKratos.py, such as:
before the coputation loop:
gp_to_node_transform_util = IntegrationPointToNodeTransformationUtility3D()
and just before the git_output.PrintOutput():
gp_to_node_transform_util.TransformFromIntegrationPointsToNodes(Q_VALUE,main_model_part)

As you said, the GP value is mapped onto the nodes.

**Comment by jcotela** [comment]
@mpentek OK I see, thanks for the clarification.
Just to be clear, I think that we should add the Q_VALUE calculation for the other elements, too (or, even better, move it to an external utility that can be called independently of the fluid element), but this is not a concern for now. So the point is: should we add this for all elements (as in your PR) or only on the fractional step solver? I'd say let's add it for everyone (the cleaned-up version of the monolithic element currently under development supports Q_VALUE calculation, so we are solving a problem we'll have soon anyway).

@rubenzorrilla Does the current Process infrastructure support adding process-dependent variables? (is there an AddNodalSolutionStepVariables() type function for the process class?). If not, maybe this is something we could add, since it would help reduce errors with this kind of "extra" variables.

**Comment by rubenzorrilla** [comment]
@jcotela regarding the idea of adding variables inside a Process, right now there is no AddNodalSolutionStepVariables() method. Better than adding it, IMO it would be better to throw an error if a variable is missed. I think it is better to construct the processes after all the variables addition. Besides, I don't know if to add different variables to different submodelparts (something that might happen if we do it in this way) could yield some problems.

**Comment by jcotela** [comment]
Hi @rubenzorrilla. While I agree that we need to be careful with the submodelparts, I still think that it would be a good idea that processes can add their variables to the ModelPart. The idea is that the process should be self-contained: if the process is used correctly, the thing should work out of the box.

I think this PR is a good example of why this is important: to ensure that what @mpentek wants to do works, we are adding an extra variable for everyone. On the other hand, if we had a process for Q_VALUE calculation that could, when enabled, add the Q_VALUE variable to the nodes, we could add the extra variable only when needed. However, I think this is something we should discuss on a separate issue, so I'll close this one for now.

**Comment by pooyan-dadvand** [comment]
:+1: for add variables in processes.
