### ISSUE TITLE
Reduction and uninitialized arrays

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#8577]
**Description**
```array_1d``` is [deliberately](https://github.com/KratosMultiphysics/Kratos/blob/5f553c06dd7f4c680c397c27fd3557601f74c275/kratos/containers/array_1d.h#L105) uninitialized, and [reduction objects](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/reduction_utilities.h) don't initialize their [stored values](https://github.com/KratosMultiphysics/Kratos/blob/5f553c06dd7f4c680c397c27fd3557601f74c275/kratos/utilities/reduction_utilities.h#L42) either. Some compilers null-initialize any allocated array of built-in types but that behaviour is not standard, so reduced values are not guaranteed to be correct.

I have no idea how this hasn't bitten anyone else yet, but it gave me quite a bit of headache when working with drag calculation in #8512. I think appropriate initialization in reduction objects should be considered.

**Comment by RiccardoRossi** [comment]
what we are saying is that when you construct an array object or a vector it is uninitialized.
that is the desires behaviour for performance, and no compiler will initialize it to zero (although it might be zero, you cannot rely on it). this has nothing to do with reductions and cannot be changed (for example std::vector does zero initialize by design and it is slower for this reason)

can u post a simple code showing the problem that you are experiencing with reductions?

**Comment by philbucher** [comment]
@matekelemen we had the same issue already and solved it here:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.h#L1392-L1415

I forgot to move this code to the reduciton utilities, could you please do that in a separate PR? then you can directly use it

**Comment by matekelemen** [comment]
Yep that's what I meant. Sure, I'll open a PR tomorrow evening.
