### ISSUE TITLE
[Output] Line output point locator warning

### ISSUE THREAD

**Issue by demetrafabris** [KratosMultiphysics/Kratos#8659]
**Description**
Resolving a 2D CFD analysis of a bridge deck. I've obtained this error:
"RunetimeError: Error: There is no sub model part with name: "FluidModelPart.FluidParts_fluid" in model part "FluidModelPart""

**Scope**
Where in Kratos is this bug happening: resolution

**To Reproduce**
Run the MainKratos file

**Expected behavior**
To start the analysis

**Environment**
- OS: Ubuntu 20.10
- GiD: 14
- Python 3.9

![image](https://user-images.githubusercontent.com/81411661/115577639-e5586f80-a2c4-11eb-9027-6f15efe57196.png)

[ProjectParametersCustom.txt](https://github.com/KratosMultiphysics/Kratos/files/6351961/ProjectParametersCustom.txt)

**Comment by rubenzorrilla** [comment]
Hi! Can you attach the complete test case to have a look to the mdpa?

**Comment by demetrafabris** [comment]
Hi, yes for sure. Thanks

    Il mercoledì 21 aprile 2021, 17:20:36 CEST, Rubén Zorrilla ***@***.***> ha scritto:  
 
 


Hi! Can you attach the complete test case to have a look to the mdpa?

**Comment by demetrafabris** [comment]
[ponte prove_traverso solo  soletta_parapetto.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/6365743/ponte.prove_traverso.solo.soletta_parapetto.gid.zip)

**Comment by rubenzorrilla** [comment]
Hi. I've just tried the case with the current master branch and it runs without any problem in my machine (I tried with the `MainKratos.py` script in the attachment).

Is your Kratos version more or less recent?

**Comment by demetrafabris** [comment]
The script I'm having trouble with is MainKratos_custom_prova.py

**Comment by rubenzorrilla** [comment]
As described in the error, you need to prepend all the model part names in your `line_output_process`(es) with the father model part (in this case the `FluidModelPart`). Otherwise the `Model` container cannot retrieve them. I'm attaching the case with the corrected .json settings file.

BTW, I think that there are some of the points lying outside the domain as the point locator issues saying that no element was found for some points.

[ponte prove_traverso solo soletta_parapetto.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/6375811/ponte.prove_traverso.solo.soletta_parapetto.gid.zip)

**Comment by demetrafabris** [comment]
Ok thanks.
I know that there are some problems with some point, but I don't know why. I entered all the exact coordinates of the structure, but just in some case I've got some warnings, infact I would ask you how could I solve this problem.

**Comment by rubenzorrilla** [comment]
Honestly, I've never used this `line_output_process`. According to the warning message, what I'd try is to choose a point close to the structure but inside the domain (just to see if the warning is still issued).

Maybe @matekelemen can give some more hints here (as far as I know he uses it).

**Comment by rubenzorrilla** [comment]
BTW, I changed the issue title as I think that the terminal error should be fixed now. Feel free to revert the changes.

**Comment by philbucher** [comment]
@mpentek

**Comment by rubenzorrilla** [comment]
> @mpentek

Right, I pointed to the wrong Máté :smile:

**Comment by matekelemen** [comment]
Seems like some of the line begin/end points are slightly outside your domain (inside the bridge structure). I'd try either defining them with extra precision, or setting the [tolerance on the line search process](https://github.com/KratosMultiphysics/Kratos/blob/0c64bc0e8cf280a0775a35efa7c8583628687b81/kratos/python_scripts/line_output_process.py#L33) higher.

![bridge_full](https://user-images.githubusercontent.com/44344022/116226083-dce3b700-a752-11eb-8e8c-84ee078dfb8d.png)

![zoom](https://user-images.githubusercontent.com/44344022/116226103-e1a86b00-a752-11eb-9e0f-b6a80ecccdd3.png)

**Comment by mpentek** [comment]
With the line output you provide a start and the end point as well as number of sampling points. The process generates the actual sampling points which Kratos will try to locate in your model part. If any of these locations are not nodes or inside elements in Kratos you will receive a warning that the point is not found (and a respective output file saying point id -1). The simulation will proceed.

The typical reasons for not having the point inside the model part is:

- the location you are looking for is not inside your model part due to meshing and numerical precision
- distributed memory run (MPI) where the point is not inside one local model part (but part of another perhaps)

**Comment by mpentek** [comment]
> > @mpentek
> 
> Right, I pointed to the wrong Máté 😄

even better and the answer is correct @matekelemen

**Comment by demetrafabris** [comment]
I solved the problem using points close to the structure, but still inside the domain (for example, instead of 22.93152 [m] I took 22.93153 [m])
Thanks

**Comment by rubenzorrilla** [comment]
Closing the issue as it seems to be solved. @demetrafabris feel free to reopen it if needed.
