### ISSUE TITLE
Installation of kratos with MPI support on Linuxmint latest

### ISSUE THREAD

**Issue by anirudhnehra** [KratosMultiphysics/Kratos#8895]
**Description**
There are many pages regarding installation of kratos multiphysics with MPI. Some of them seem to be outdated. I am confused which ones to refer, for example somewhere it is mentioned that only BOOST library header files are necessary while somewhere its said that BOOST has to be compiled with MPI in order to use MPI in KRATOS.
Please indicate one true source of information page which I can follow in order to use KRATOS with MPI suppport.

Much Regards
Anirudh Nehra

**Scope**
Installing kratos with mpi

**Comment by RiccardoRossi** [comment]
compilation with boost is definitely not needed.

in essence compiling with mpi and telling -DUSE_MPI=ON in the cmake
configuration shall be enough

**Comment by anirudhnehra** [comment]
Hi,
Thanks for the reply. I have a few more queries:
1> Do I need to install SuperLU before installing for MPI support? as indicated here: http://kratos-wiki.cimne.upc.edu/index.php/How_to_compile_the_Boost_if_you_want_to_use_MPI
2> If I use the latest version of OpenMPI in a custom folder, How do I indicate kratos to look for that folder? Do I need to still install libopenMpi-dev from repositories? Is liboopenMpi-dev sufficient?
3> I have both Python2 and Python 3 installed. I have made alias python="path/to/python3" in .bashrc. Do I need any modification here? Should I remove the alias?
4> DO I need to install MMG3D application if I want to do remeshing? How do I indicate that during Kratos install? Should I follow instructions here: https://github.com/KratosMultiphysics/Kratos/wiki/%5BUtilities%5D-MMG-Process
5> Somewhere its mentioned to install a lot of libraries such as lapack, blas etc from repositories like libblas-dev, etc.. Do I need to install them before launching installer script?


Regards
Anirudh Nehra

**Comment by philbucher** [comment]
Hi,

I strongly suggest to only take a look at the documentation in this repo, everything else might be very outdated. In general we reduced the dependencies on external libs a lot in the past, so unless you have problems while compiling or running, I would not install aux libraries such as lapack

1. Check the [INSTALL.md](https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md) for instructions, this is the up to date version of the install guide
2. I am not quite sure, this depends on the compiler you use. This has actually nothing to do with Kratos. Normally it should find it (unless you have multiple versions installed)
3. I would not do that. I tried this myself in the past an messed up my system
4. MMG is used for remeshing. So yes, if you want to do that then you need it
5. As mentioned above I would not install it unless it doesn't work otherwise. Check the readme of the TrilinosApp
6. You need metis 5

Check our CI-Scripts, there you can see exactly what we use:
- [Docker](https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/docker_files/docker_file_ci_ubuntu_20_04/DockerFile) for dependencies
- [configure file](https://github.com/KratosMultiphysics/Kratos/blob/master/.github/workflows/configure.sh)

1

**Comment by anirudhnehra** [comment]
Hi,
Thank you for responding. 
I have a few queries.
Do I need these libraries beforehand for compiling kratos with mpi?
1-boost-compiled-with-mpi (I have installed boost with sudo apt install libboost-all-dev)
2-trilinos 
3-mmg for remedying
4- superlu

Do I need to modify LD_LIBRARY_PATH since boost is I'm usr/lib/x86_64-linux-gnu folder?


Regards
Anirudh Nehra

**Comment by philbucher** [comment]
Hi,
1. We only need headers from boost, hence it is not necessary to add anything to LD_LIB_PATH for boost
2. For trilinos you need to add it. (unless you installed it with the package manager like you did boost)
3. Same for MMG, you need to add it to LD_LIB_PATH
4. Same, although this one might not be needed as it is quite slow, depending on the problem you want to solve. I recommend using the AMGCL solver (iterative) if you can, it is much faster and come with the TrilinosApplication

Hope this helps,
Philipp
