### ISSUE TITLE
[CI] Nigthly still failing

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#8986]
**Description**
The CL app is failing again:

https://github.com/KratosMultiphysics/Kratos/runs/3111420245?check_suite_focus=true

The meshing app is failing due to the lack of the libmmg (so apparently the last change does not work properly)

**Scope**
- Nightly
- CLApp
- MeshingApp

**To Reproduce**
https://github.com/KratosMultiphysics/Kratos/runs/3111420245?check_suite_focus=true

**Expected behavior**
Fail

**Environment**
- CI machines

**Comment by marcnunezc** [comment]
Hmm yeseterday I run the normal CI and it worked.

https://github.com/KratosMultiphysics/Kratos/actions/runs/1044651779

As I understand the same environtment is used in the nightly. Let me check again in the docker with a clean build

**Comment by marcnunezc** [comment]
@loumalouomega , the nightly run you share in your post correponds to the manully run by @riccardotosi  in https://github.com/KratosMultiphysics/Kratos/pull/8960

Which probably did not have the correct master version with the change of the CLaw and MeshingApps.

The nighlty run that ran tonight is:

https://github.com/KratosMultiphysics/Kratos/actions/runs/1047306828

Which failed due to another reason, which is being fixed in https://github.com/KratosMultiphysics/Kratos/pull/8987

I think everything is working as expected, we got confused by the different nighlty runs

**Comment by loumalouomega** [comment]
Closing then
