### ISSUE TITLE
Kratos Technical Committee Election

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#9093]
After two years it is time to renew the 3 elected members of Kratos Technical Committee (KTC)

Nomination
Candidates should have sustained contributions to the open source part of the project. This includes not only the code itself but also the documentation, GUI, etc...

For announcing the nomination please reply in this issue using following template:

Full Name: To be used in election
@github user: as proof of membership and contribution
Who am I?: A short professional background
A message to voters (optionally) Why people should vote me
The deadline for nomination is September 30th at 12:00 CEST

Census
Any member of KratosMultiphysics project in GitHub can participate in this election.

Registering for Voting
It is important to register for voting by sending an email to  **kratosmultiphysics@gmail.com** with **subject** `Kratos Technical Committee` (an automatic filter will be used) and a message including your @github user and the email you want to use for voting.

The deadline for registration is September 30th at 12:00 CEST

Important dates
Nomination: The deadline for nomination is September 30th at 12:00 CEST
Registration The deadline for registeration is September 30th at 12:00 CEST
Election: From October 6th at 9:00 CEST to October 8th at 18:00 CEST

**EDIT:** For future elections we should do a separate issue for registering and nomination. Some members of the community missed the registering part in here. Editing this issue as the next KTC will probably use it to announce the future elections.

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/all

**Comment by rubenzorrilla** [comment]
Presenting for the KTC for the second time

Full name: Rubén Zorrilla @rubenzorrilla

Who am I?: My name is Rubén Zorrilla Martínez. I have a Bachelor in Engineering and Sciences of Building, a Bachelor in Construction Enginering, a M.Sc. in Numerical Methods and a Ph.D. in Civil Engineering. Right now I am a postdoctoral researcher at CIMNE and an associate lecturer at the UPC. Besides this, I am one of the elected members of the KTC since 2019. My research mainly focuses Computational Fluid Dynamics (CFD) as well as coupled problems involving CFD, such as Fluid-Structure Interaction (FSI), thermally-driven flows or Conjugate Heat Transfer (CHT).

Message/Slogan: Since I joined the community more than 5 years ago I've been one of the most active developers, being not only main developer and maintainer of several applications (`FluidDynamicsApplication`, `FSIApplication` and `ConvectionDiffusionApplication`) but eventual contributor another (`StructuralMechanicsApplication` or `LinearSolversApplication`).  Besides this, I've been always involved in the `KratosCore` development, being an active part of important enhancements, migrations and deprecations. This made me reach a wide knowledge and holistic perspective about Kratos. Joining the KTC in 2019 was a great opportunity to complement all this knowledge with a much more technical perspective, pushing me forward to learn the technicalities behind many low level Kratos features, boosting at the same time my C++ and Python knowledge.

There are many valuable things that are still pending in our KTC ToDo list (e.g. multistage analysis, full integration of adaptive mesh refinement, factories, ...) to which I'd like to have an active contribution. Furthermore, I think that I can still do many other valuable contributions to the KTC.

:metal: Make the Kratos great again :metal:

**Comment by RiccardoRossi** [comment]
ping @KratosMultiphysics/all

**Comment by sunethwarna** [comment]
Presenting for the KTC for the first time. 

**Full Name**: Suneth Warnakulasuriya @sunethwarna 

**Who am I?**: Hi, my name is Suneth. I have a Bachelor in Mechanical Engineering and a Masters in Computational Mechanics. Currently I am in the phase of writing my thesis to finish my PhD. I have been actively contributing to Kratos community since 2018, and am one of the main developers in few applications (FluidDynamicsApplication, RANSApplication, HDF5Application, StatisticsApplication) and I have also contributed towards developments in Kratos core and ShapeOptmizationApplication. My main focus is on developing sensitivities/adaptive mesh refinement/turbulence modelling for fluid and structure related problems such as Fluid-Structure-Interaction (FSI), Conjugate Heat Transfer (CHT). 

**Message / Slogan**: I am fascinated with the modularism and HPC compatibility since I joined the Kratos community. It is helpful in tackling large complex problems related to fluid. I have been always trying to implement/modify existing/new functionalities keeping in mind the modularity, extensibility, HPC concepts, and user friendliness (to developers as well as users) to my best knowledge. So, I would like to keep on contributing to Kratos community with the same mindset while learning from it to enhance my knowledge. KTC gives me a great opportunity to do so and to work closely with the core conceptual developments to provide better KratosMultiphysics framework for everyone. :metal:

**Comment by AlejandroCornejo** [comment]
Presenting for the KTC for the first time

**Full Name:** Alejandro Cornejo Velázquez @AlejandroCornejo

**Who am I?:** 

Hi! My name is Alejandro Cornejo. I am a civil engineer (BSC and MSC) by the Politechnical University of Catalonia (UPC) and I have a PhD in Structural Analysis in the same university. Currently a postdoctoral researcher at CIMNE (Barcelona) and associate professor at the UPC. My main lines of research (all of them using Kratos) are Fracture mechanics and FSI inside the `FemToDemApp` (coupling `StructuralMechanicsApp`, `DEMApp `and `PFEMFluidDynamicsApp`), solid constitutive modelling (`ConstitutiveLawsApp`), remeshing capabilities (`MeshingApp`) and introducing to contact mechanics in `ContactStructuralMechanicsApp`. Besides this, I have been also adding some complementary capabilities to the Kratos core and a current member of the implementation subcommittee.


**A message to voters:**

Since joining Kratos in 2016, I have enjoyed continuous learning not only in the numerical field but also in programming related topics. My interest in numerical methods has motivated me to add many capabilities to Kratos: a multitude of solid constitutive models, coupled solvers, among others, being one of the most active developers. All this years of experience have shown to me that characteristics like modularity, friendlyness, robustness and efficiency are of primal importance, and some work is still required to achieve this in our beloved code. That said, I would like to propose my candidacy to further deepen my knowledge in Kratos capabilities (c++ and python) while participating in all maintenance, development and review tasks for the GitHub community.

**Comment by philbucher** [comment]
I will not be applying again for the KTC as my time as a phd student is approaching its end and it is uncertain whether or not I will continue to work with Kratos.
Thanks everyone for the good work and the support over the years, Kratos has grown and improved a lot!

To continue representing Germany in the KTC, I want to endorse @sunethwarna as my successor in the KTC. We have been colleagues for years now and I think he will be a very good fit for the KTC.

**Comment by rubenzorrilla** [comment]
Ping @KratosMultiphysics/all

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/all You should have already received the voting links in the email addresses you provided. Please ensure that you did and in case you don't have them please double check your spam folder.

Remember that the voting starts tomorrow at 8:00 CET and will last until October 8 at 17:00 CET. (If everyone votes before the end date the poll will close automatically and the results will be published)

Good luck everyone!
