### ISSUE TITLE
[Structural] allow structural solver to use a submodelpart as computing model part

### ISSUE THREAD

**Issue by pablobecker** [KratosMultiphysics/Kratos#9130]
**Description**
I am running a (multistage) structural analysis, and in one of the stages i only want to use one of the submodelparts of the main_model_part.

When I try to do this with the structural solver (, I get the error "Please don't use names containing (".") when creating a ModelPart (used in "main_model_part.XX") , triggered [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L80) . 

So the problem is that it's checking if the model part exists and creating one  in the constructor of the solver, before the solver had the time to load mdpa/modeler. 

Would it be possible to move this model part check and creation from the constructor to the Initialize() ? 

ping @philbucher

**Comment by philbucher** [comment]
Without remembering the exact reasons I would say this is not possible, as otherwise there are some chicken-egg problems IIRC

I am out for a week, then I can try to think of this a bit more in detail

I am sure we can come up with a solution, but it should be thought through as it is a sensitive thing

BTW the fluid does the same

**Comment by pablobecker** [comment]
Thanks Phil, I was just checking that.

@RiccardoRossi I noticed that this is done like this in all the apps, so it's more a kratos issue than a structural app issue.. Problem here is that the init is doing things it should not do. Any ideas?

**Comment by philbucher** [comment]
another thing preventing the usage of SubModelParts is the allocation of the Nodal-Vars: This has to be done before reading anything, as it is not possible to add them after the nodes are created
How do you intend to solve this?

**Comment by RiccardoRossi** [comment]
I am honestly not sure of this implications of this at the level of creation/destruction.

I am pretty sure however  that if you try to do computations with a submodelpart and with the root modelpart at the same time you will have a problem with the dofs equation Ids, which are assigned in the SetupSystem (which is called only once)

in order to allow this kind of usage we would have to call the builder and solver's SetupSystem at the beginning of every SolveSolutionStep

**Comment by ddiezrod** [comment]
> I am honestly not sure of this implications of this at the level of creation/destruction.
> 
> I am pretty sure however that if you try to do computations with a submodelpart and with the root modelpart at the same time you will have a problem with the dofs equation Ids, which are assigned in the SetupSystem (which is called only once)
> 
> in order to allow this kind of usage we would have to call the builder and solver's SetupSystem at the beginning of every SolveSolutionStep

I think its easier than this. @pablobecker always wants to use only the submodelpart as "computing" model part in this stage, he just wants to forget about the rest of submodelparts in the mdpa. You can maybe think in this problem in the following way:
"How could we currently run a structural mechanics stage where the model part I want to compute is a submodelpart in the mdpa?" I think there is no way to do that right now which seems like a big drawback to me. 

Adding more people @AlejandroCornejo @loumalouomega

**Comment by loumalouomega** [comment]
I thought we get rid of the computational model part

**Comment by RiccardoRossi** [comment]
@ddiezrod in essence what you want is to add the capability of doing

~~~py
my_solving_strategy = MySpecialStrategy(   ... with a submodelpart ...)
my_solving_strategy.Solve() ##well this "Solve" divided in the substeps we have
~~~

and i would be positive about this since the ComputingModelPart is essentially not being used any longer in the structural mechanics.

the think i am telling is that if we allow this (and i agree we should)

right after someone will do something on the line of 

~~~py
strategy1 = MySpecialStrategy(   ... Root.Part1 ...)
strategy2 = MySpecialStrategy(   ... Root.Part2 ...)
strategy1.Solve() 
strategy2.Solve() 
strategy1.Solve() #BUM! (we have dofs in common between 1 and 2, and the Ids were reassigned in 1 
~~~

I appreciate that this was not your question, however as a part of the support we need to handle this

**Comment by loumalouomega** [comment]
> I thought we get rid of the computational model part

Would be smarter to use several modelparts inside a Model, will be more consistent

**Comment by RiccardoRossi** [comment]
no, i think that the use of the submodelparts is quite clever.

think for example that you want to solve an entire building, or just a beam out of it. You may solve the building first, freeze it, and then just focus on one of the beams. This is automatically done if you have the same root but not otherwise

**Comment by loumalouomega** [comment]
> no, i think that the use of the submodelparts is quite clever.
> 
> think for example that you want to solve an entire building, or just a beam out of it. You may solve the building first, freeze it, and then just focus on one of the beams. This is automatically done if you have the same root but not otherwise

Okay (this makes sense)

**Comment by pooyan-dadvand** [comment]
The example use case is very similar to example of  @RiccardoRossi:

In the first stage we want to solve the entire model part which is the print part and its supports and in the spring back stage only the print part without support

The workaround of interpreting the input modelpart name (with "." path to sub modelpart) is relatively easy to do but I think that conceptually is not correct to do this in the constructor of the stage. In fact, now we have modeler and this should be done in the PrepareModelPart method there rather than in the construction

**Comment by pooyan-dadvand** [comment]
After discussing it in @KratosMultiphysics/technical-committee we arrived to the conclusion that as long term solution we should do the following changes:
1. Have a `ModelPartIOModeler `which reads a mdpa and puts it in a ModelPart with name given in PP in its `PrepareModelPart()` method
2. Deprecate the `ImportModelPart `in the solver and use the modeler lists in PP.json to create the necessary ModelParts for the solver
3. Change `AnalysisStage._GetSolver()` and decompose it into` _CreateSolver()` and` _GetSolver()` (with error if solver is not created) 

Please note that this implies a change in all solvers and now the user should know (instead of how many mdpa a solver needs) how many modelpart should be created by the modelers before starting the solver

@pablobecker as a workaround you may proceed with changing the `Create()` method of the Model to create the entire path to a sub modelpart if doesn't exist

**Comment by loumalouomega** [comment]
> After discussing it in @KratosMultiphysics/technical-committee we arrived to the conclusion that as long term solution we should do the following changes:
> 
>     1. Have a `ModelPartIOModeler `which reads a mdpa and puts it in a ModelPart with name given in PP in its `PrepareModelPart()` method
> 
>     2. Deprecate the `ImportModelPart `in the solver and use the modeler lists in PP.json to create the necessary ModelParts for the solver
> 
>     3. Change `AnalysisStage._GetSolver()` and decompose it into` _CreateSolver()` and` _GetSolver()` (with error if solver is not created)
> 
> 
> Please note that this implies a change in all solvers and now the user should know (instead of how many mdpa a solver needs) how many modelpart should be created by the modelers before starting the solver
> 
> @pablobecker as a workaround you may proceed with changing the `Create()` method of the Model to create the entire path to a sub modelpart if doesn't exist

These changes could be related with #8806? (maybe we can apply some of these changes there)

**Comment by RiccardoRossi** [comment]
no, these are fundamental changes, essentially to switch the ModelPartImporting from the solver into the AnalysisStage (through a modeler),

If we intend the "combinator" in #8806 as a modeler, than that would also be compatible with the proposal modification
