### ISSUE TITLE
MeshingApplication vs DelaunayMeshingApplication

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#9211]
**Description**
While helping develop a new application based on the PFEM, I saw that it was using the MeshingApplication. However, I can observe in the repository that other apps are using DelaunayMeshingApplication for a similar purpose.
Which one should be used for PFEM? Are both of them being maintained? 
I also see that DelaunayMeshingApplication contains an automatic download of Tetgen in case it is not provided externally, which I found an elegant solution. Can this mechanism be copied into the MeshingApplication?
@AFranci @josep-m-carbonell @AlejandroCornejo @playpaolo @juliobarna

**Comment by RiccardoRossi** [comment]
after discussing in the @KratosMultiphysics/technical-committee we believe that downloading tetgen **cannot be silent**.

the cmake file of the  MeshingApplication will need to be modified so that the user provides AT COMPILE TIME the link from where the tetgen needs eventually to be downloaded. something on the line of 

-DDOWNLOAD_TETGEN_TPL_FROM="...web address from which the zip can be retrieved ..."

if the tetegen is not available, the MeshingApplications should compile anyway deactivating the features that are not available.

**Comment by roigcarlo** [comment]
I will close this one as now you can compile the meshing with tetgent support bia the new TPL, if you still have issues, please reopen.
