### ISSUE TITLE
PoromechanicsApplcation MPI linkage

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#9353]
**Description**
PoromechanicsApplication is directly linking Trilinos if MPI is enabled.

**Scope**
PoromechanicsApplication

**Expected behavior**
MPI should be separated into a dedicated module (see FluidDynamics extension)

**Environment**
Any

**Comment by ipouplana** [comment]
Thanks @roigcarlo
I am aware that this needs to be done... I even had a branch open for this but had to leave it half way because of lack of time...
Since I still don't have time to fix it, do you think it is convenient that I open a quick PR just deleting everything related to MPI ? (we are not using it lately)

**Comment by roigcarlo** [comment]
If current MPI implementation is working (or can be saved) and you don't have time to fix we can leave it like this adding a flag to skip the mpi part for this app (mainly to prevent affect others that depend on poro) until someone does.

If there is no way to save it or no one will do it in a foreseeable future, then probably is better to remove it.

**Comment by ipouplana** [comment]
Well, I think current MPI implementation is not working, but since I have a branch open with this in mind, maybe it is better to remove it from the master branch.

**Comment by ipouplana** [comment]
I close this as PR is already merged
