### ISSUE TITLE
FullDebug Windows Compilation Issue

### ISSUE THREAD

**Issue by MZecchetto** [KratosMultiphysics/Kratos#9404]
Dear all,
I am facing troubles when compiling the latest master branch in FullDebug under windows. The configure file is attached together with the linking error.

[my_configure.txt](https://github.com/KratosMultiphysics/Kratos/files/7608826/my_configure.txt)

![error_fulldebug](https://user-images.githubusercontent.com/50821222/143583583-52129e43-75f5-4764-bad9-bb7fc1181018.png)

[error_fulldebug.txt](https://github.com/KratosMultiphysics/Kratos/files/7608816/error_fulldebug.txt)
 
Same my_configure.bat, but in `Release` compiled fine.

Any hint?

**Scope**
- Compilation

**Environment**
- OS: Windows 10
- Branch: master
- Python 3.10

**Comment by roigcarlo** [comment]
Hi @MZecchetto. You need to install the python debug libraries.

When installing python it should be under advanced setting. You can also use the same installer you used to install python (or the visual studio installed if you installed it along Vs) to modify your current installation and add those

**Comment by MZecchetto** [comment]
Hi @roigcarlo! Thanks for your swift reply!
I think I've installed them, see screenshots hereafter.

![python lib](https://user-images.githubusercontent.com/50821222/143677658-8b44bcbc-0b5e-4f31-bad0-dd787b99dd2c.png)
![options](https://user-images.githubusercontent.com/50821222/143677663-fb517d00-e4e9-472a-a1d7-f65b2f56a912.png)

Am I missing something?

**Comment by roigcarlo** [comment]
Hi, that's odd, you do in fact have all the necessary components and the configure seems to correctly detect the python installation you are showing.

Since the problem seems to appear in the zlib binaries I've disabled those (they are really not necessary). 

If you want to try yourself before the PR is merged just comment the last few lines (233-eof) from `external_libraries/zlib/CMakeLists.txt`.

**Comment by MZecchetto** [comment]
@roigcarlo I switched to `hotfix/remove-zlib-examples` branch and got the following error:

![error](https://user-images.githubusercontent.com/50821222/143846117-b79e8e55-1190-4827-9b49-3ae6cbbdab15.png)

any clue?

**Comment by roigcarlo** [comment]
Hi @MZecchetto 

Seems that for some reason is not finding python now.

Since you changed the branch and you come from a faulty compilation I suggest the following:
- Close and open the powershell terminal (windows remembers changes in the env that happen inside scripts and this may be causing problems)
- Move back to the master
- Delete both the `build` and `bin` folders from Kratos root
- Change the python line in the config file to: `set PYTHON_EXECUTABLE=C:\Users\Massimiliano\AppData\Local\Programs\Python\Python310\python.exe`

If this still gives you problem, please set this flag in the cmake options (you will have to run using the python interpreter):
`-DINSTALL_RUNKRATOS=OFF`

Or directly add the library into the project that triggers the python_d.lib error:
- Right click on the project in Visual Studio -> Linker -> Input -> Additional Dependencies

**Comment by MZecchetto** [comment]
Hi @roigcarlo,
I moved back to current master, clean up `bin` and `build` folders and I got the initial error.

![error](https://user-images.githubusercontent.com/50821222/144426128-7df16149-e8cc-4eae-ad73-d8bbbdecb3dc.png)

I am using another workstation and Python 3.9.

Most-likely I am missing something basic, but I cannot figure out what.

**Comment by roigcarlo** [comment]
Hi @MZecchetto ,

Try to add `-DINSTALL_RUNKRATOS=OFF` in the cmake flags of the configure. That should prevent the compilation of our internal embedded interpreter.

**Comment by MZecchetto** [comment]
it works @roigcarlo , thank you very much for the support!
