### ISSUE TITLE
Nightly build failing (Swimming DEM)

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#9461]
**Description**
Apparently the Nightly build is failing, the `SwimmingDEM `tests are not passing. Just mentioning @GuillermoCasas for your interest.

**Comment by rubenzorrilla** [comment]
@GuillermoCasas @jgonzalezusua any advance in this regard?

**Comment by philbucher** [comment]
this test is failing now for a long time already
@GuillermoCasas @maceligueta is it ok to disable it until you have time to fix it?
Note that this shows the build as failing on the main page of the repo which is not a good image for us :/

**Comment by ddiezrod** [comment]
It seems CI complains because nightly tests take too long. Just for reference, these are the tests that are taking more time to run (on my machine)
Ran 13 tests in 30.241s

OK
Test Execution Times:
test_execution (NightTests.gentle_erasure_test)  12.71 [sec]
test_execution (NightTests.periodic_backward_coupling)  9.20 [sec]
test_execution (NightTests.gentle_injection_test)  4.59 [sec]
test_execution (SmallTests.porosity_field_conservation_test)  1.07 [sec]
test_execution (SmallTests.analytic_multiple_ghosts_test)  0.58 [sec]
test_execution (SmallTests.CFD_DEM_two_way_test_DVMS)  0.38 [sec]
test_execution (SmallTests.fluid_dem_coupling_one_way_test)  0.37 [sec]
test_execution (SmallTests.CFD_DEM_two_way_test)  0.34 [sec]
test_execution (SmallTests.chien_drag_test)  0.22 [sec]
test_execution (SmallTests.interpolation_test_nonlinear_time_no_substepping)  0.21 [sec]
test_execution (SmallTests.backward_coupling_two_balls_periodic_no_time_filter)  0.20 [sec]
test_execution (SmallTests.interpolation_test_linear)  0.18 [sec]
test_execution (SmallTests.backward_coupling_single_particle_no_time_filter)  0.10 [sec]

**Comment by rubenzorrilla** [comment]
Considering the recent changes in #9796 I think that this no longer makes sense.
