### ISSUE TITLE
TIME_STEPS vs STEP

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#947]
I have been looking at gid_output_process.py and the step variable used is `STEP` but in many scripts, and in my case I use `TIME_STEPS`. Should we remove this duplication?

**Comment by RiccardoRossi** [comment]
what you say sounds interesting.
could you expand on it, maybe pointing to the relevant code?

**Comment by loumalouomega** [comment]
I meant the gid_output_process.py, I don't know any other file, but we can start a discussion with just that

**Comment by jcotela** [comment]
@loumalouomega: if I recall correctly, the idea at the time was to have "simple" names for the binary output and restart files (so instead of a "messy" fractional time step you get a nice integer in the filename). I don't think it replaces the `TIME` ProcessInfo variable, which is used internally by the strategy as usual. If I recall correctly, it is stored in ProcessInfo just to ensure that it can be read/written during a restart (otherwise it could just be a class variable of the process?).

**Comment by RiccardoRossi** [comment]
@jcotela i have the feeling it has issues with the GiD animation windows. i will show you tomorrow

**Comment by maceligueta** [comment]
At @KratosMultiphysics/technical-committee  we think STEP is a more general options. We thought of load steps, time steps, etc. STEP should be adopted when possible. Closing. Do not hesitate to reopen if relevant arguments can be brought in.

**Comment by loumalouomega** [comment]
Do I change everything I have using TIME_STEP intead of STEP?

**Comment by maceligueta** [comment]
Yes please, unless you find technical or semantic problems with that.
