### ISSUE TITLE
Does anyone understand what is wrong with this PR?

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/Kratos#9470]
**Description**
In my previous PR #9403 I was passing a number of arguments to a function using pybind (basically giving access to OMP_DEMSearch) for testing purposes.

I decided to pass one more argument to the function in order to expand the test in #9465, so I modified the add_custom_strategies_to_python.cpp accordingly. The extra parameter is an additional python list, just as the second last argument, which was already a list. 

Unfortunately, with this extra parameter a run-time error pops up upon running the test that calls the function. The funny part is that neither in my computer, neither in my colleague's it fails to run. 

Can anyone help?

**Scope**
- SmallTests
- pybind

**Comment by jgonzalezusua** [comment]
Maybe @roigcarlo can help us

**Comment by philbucher** [comment]
What is the error?

**Comment by jgonzalezusua** [comment]
The error is in #9465. When running small tests, CI throws an error related to incompatiblities with the argument of a function. However, everything work well in our local machines.

**Comment by roigcarlo** [comment]
I am not sure but If I had to guess I would say there is something strange with:

`DEM.VectorResultNodesContainer()`
`DEM.VectorDistances()`

When looking at the error it reports failing because types ares:

`arg3: List[List[Kratos.Node]], arg4: List[List[float]]`

invoked with:

`<KratosDEMApplication.VectorResultNodesContainer object at 0x7fadcc549cf0>, <KratosDEMApplication.VectorDistances object at 0x7fadcc549a30>`

In the interface those are:

```C++
VectorResultNodesContainerType & d;
VectorDistanceType & e;

// Which expanded are

std::vector<std::vector<NodePointerType>>
std::vector<std::vector<double>>
```

My guess is that because of the unitary build, the `pybind11/stl.h` is being included in your source, which is making `std::vector<std::vector<Foo>>` being seen as `List<List<Foo>>` by python.

To solve it, try to add this after the target `KratosDEMApplication` is created in the DEM CMake:

```CMake
if(CMAKE_UNITY_BUILD MATCHES ON)
    ## Kratos cannot be compiled with just one unity build as it takes way too much ram
    set_source_files_properties (${CMAKE_CURRENT_SOURCE_DIR}/custom_python/add_custom_strategies_to_python.cpp PROPERTIES SKIP_UNITY_BUILD_INCLUSION TRUE)
endif(CMAKE_UNITY_BUILD MATCHES ON)
```

**Comment by GuillermoCasas** [comment]
Ah, OK! What is strange is that it worked before, since these two objects were there already! Thank you for proving that indeed it works too (#9465).
