### ISSUE TITLE
GPU powered calculations in Kratos?

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#9553]
**Description**
Greetings to the community! 

There is a lot of talk about **GPU** computing lately, especially in our field. My question is, Kratos is planning to jump on the GPU computing trend or has it been discarded? 

I understand that the implementations would not be valid to a different CUDA c++ architecture but I am interested to know everyone's opinion.

**Comment by RiccardoRossi** [comment]
well, we have limited support for gpus.

if you compile with CUDA enabled (or opencl) than you can use GPUs in solving the system of equation through the AMGCL library. (you need to set the option use_gpgpu=True)

i guess however that you are thinking into a more pervasive use. can u maybe tell a little more what you are thinking into conretely?

**Comment by maceligueta** [comment]
In my conversations with programmers who coded DEM for GPUs, they usually tell me that the data structure needed by the GPU is probably very different from the one we are using (object oriented). The data format transformation is too expensive to be done at every time step in DEM, but maybe for a structures solver could be profitable if solving the system is much faster. I thought of communicating the DEM data with the GPU one out of many time steps, maybe that would be possible.

**Comment by loumalouomega** [comment]
(As Riccardo said, we have a limited support. Said do)

I have done some formations in CUDA (with NVIDIA workshops) and OpenACC (with PRACE workshops). First, coding for the GPU requires some time to understand, because the main killer is the memory copy/transfer, which requires some time to master (that's why the Apple M1 are unified memory, you have less memory, but you avoid the bottlenecks of the memory copy). Cuda only works in NVIDIA GPU, but if you know what you do it gives the best performance (and requires time to master).  OpenACC is more similar to OpenMP, and it works for many architectures, in fact, in the background it generates the CUDA code if you are using an NVIDIA card. It will never give as good code as if you do pure CUDA (unless you are very bad in CUDA coding...).

The problem of the two cases (and I know that there are many other alternatives), is that if you code thinking in the architecture you are using, and what type of code you want to do, it is not hardware-agnostic. That's why the other day I shared this from NVIDIA:

https://developer.nvidia.com/blog/developing-accelerated-code-with-standard-language-parallelism/?utm_source=pocket_mylist

In here, it speaks of the use of the STL parallel for hardware-agnostic parallelism. The STL is the approach we are initially integrating in the `parallel_utilities`, and once we move to C++17 we can integrate this STL hardware-agnostic acceleration mentioned in the post.

**Comment by loumalouomega** [comment]
> In my conversations with programmers who coded DEM for GPUs, they usually tell me that the data structure needed by the GPU is probably very different from the one we are using (object oriented). The data format transformation is too expensive to be done at every time step in DEM, but maybe for a structures solver could be profitable if solving the system is much faster. I thought of communicating the DEM data with the GPU one out of many time steps, maybe that would be possible.

Indeed, OOP, if the objects are heavy, are a killer for GPU, because of the copy cost.

**Comment by RiccardoRossi** [comment]
I think that for the structural problems OO programming is very advantageous.

for fluid-type problems we made some experiments quite many years back (based on mantaining an ad-hoc data structure on the gpu)

if you are curious, you can take a look here

https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.3302

and here

https://www.sciencedirect.com/science/article/abs/pii/S0045793013001576

speedup by then was around 3 wrt the cpu using openmp (but the cpu only had 4 cores)

**Comment by RiccardoRossi** [comment]
sorry, just to add that we also did some experimenting using amgcl on the gpu for the solution of the system of equations (well...i don't want to take any merit, it was @ddemidov who did it) and it pays of of a factor up to 5

**Comment by maceligueta** [comment]
Is this 5 factor relative to just the solver?

**Comment by rubenzorrilla** [comment]
> Is this 5 factor relative to just the solver?

I think yes, as far as I know this only concerns the linear solver. Not negligible in any case.

**Comment by RiccardoRossi** [comment]
once you factor in all the transfers it typically reduces.

You get the factor 5 for problems in which you need A LOT of iterations

**Comment by loumalouomega** [comment]
> for fluid-type problems we made some experiments quite many years back (based on mantaining an ad-hoc data structure on the gpu)

Of course, this is the key, but it is not straightforward as other parallel loops we have done previously. Requires some extra effort.

Additionally, the speed-up will depend in addition to the implementation on the hardware used. For example, a Jetson (an NVIDIA SBC), has better GPU than CPU in comparison, in that case will be more notifiable
