### ISSUE TITLE
Codacy ignores .pydocstyle config file 

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#9646]
**Description**
The pydocstyle config file states
https://github.com/KratosMultiphysics/Kratos/blob/b4dcd379e5d711b787a2d75791d9ef5f37cc9d0f/.pydocstyle#L3

however codacy still raises errors for D212. See [here](https://app.codacy.com/gh/KratosMultiphysics/Kratos/pullRequest?prid=8848792) for an example.

I seem to remember this error was on codacy's side, but I thought I would bring it up since I am not sure.

**Scope**
Codacy check

**To Reproduce**
Push a python file into a branch with an open PR containing a funcction with a multiline docstring starting at the second line, such as:
```Python
def foo(bar):
    """
    Lorem ipsum dolor sit amet

    consectetur adipiscing elit
    """"
    return bar
```

**Expected behavior**
No error.

**Environment**
Codacy.

**Comment by roigcarlo** [comment]
Hi @EduardGomezEscandell we are aware, the problem is that codacy does pretty much whatever it wants. Specifically with this the problem is that is either this or having D212 and D213 enabled at the same time (which means that one has to fail because are exclusive...).

I stop bothering with Codacy some time ago, if you want I can give you the credentials in case they have fixed something

**Comment by EduardGomezEscandell** [comment]
Hmm I've never used Codacy before so I won't take on your offer at this time.

Closing since the problem is not on our side.

**Comment by marandra** [comment]
Just for reference, same issue in #8816
